/* This file is auto-generated. Do not edit. */

#ifndef ACTORS_ENUM_H
#define ACTORS_ENUM_H

enum ActorTypes {
    ACTOR_TYPE_RED_GOOMBA                            = 0x00,
    ACTOR_TYPE_RED_PARAGOOMBA                        = 0x01,
    ACTOR_TYPE_GLOOMBA                               = 0x02,
    ACTOR_TYPE_PARAGLOOMBA                           = 0x03,
    ACTOR_TYPE_SPIKED_GLOOMBA                        = 0x04,
    ACTOR_TYPE_DARK_KOOPA                            = 0x05,
    ACTOR_TYPE_DARK_PARATROOPA                       = 0x06,
    ACTOR_TYPE_GOOMBA                                = 0x07,
    ACTOR_TYPE_PARAGOOMBA                            = 0x08,
    ACTOR_TYPE_SPIKED_GOOMBA                         = 0x09,
    ACTOR_TYPE_FUZZY                                 = 0x0A,
    ACTOR_TYPE_KOOPA_TROOPA                          = 0x0B,
    ACTOR_TYPE_PARATROOPA                            = 0x0C,
    ACTOR_TYPE_BOB_OMB                               = 0x0D,
    ACTOR_TYPE_BOB_OMB_DUP                           = 0x0E,
    ACTOR_TYPE_BULLET_BILL                           = 0x0F,
    ACTOR_TYPE_BILL_BLASTER                          = 0x10,
    ACTOR_TYPE_CLEFT                                 = 0x11,
    ACTOR_TYPE_MONTY_MOLE                            = 0x12,
    ACTOR_TYPE_BANDIT                                = 0x13,
    ACTOR_TYPE_POKEY                                 = 0x14,
    ACTOR_TYPE_POKEY_MUMMY                           = 0x15,
    ACTOR_TYPE_SWOOPER                               = 0x16,
    ACTOR_TYPE_BUZZY_BEETLE                          = 0x17,
    ACTOR_TYPE_STONE_CHOMP                           = 0x18,
    ACTOR_TYPE_PIRANHA_PLANT                         = 0x19,
    ACTOR_TYPE_FOREST_FUZZY                          = 0x1A,
    ACTOR_TYPE_HYPER_GOOMBA                          = 0x1B,
    ACTOR_TYPE_HYPER_PARAGOOMBA                      = 0x1C,
    ACTOR_TYPE_HYPER_CLEFT                           = 0x1D,
    ACTOR_TYPE_CLUBBA                                = 0x1E,
    ACTOR_TYPE_SHY_GUY                               = 0x1F,
    ACTOR_TYPE_GROOVE_GUY                            = 0x20,
    ACTOR_TYPE_SKY_GUY                               = 0x21,
    ACTOR_TYPE_MEDI_GUY                              = 0x22,
    ACTOR_TYPE_PYRO_GUY                              = 0x23,
    ACTOR_TYPE_SPY_GUY                               = 0x24,
    ACTOR_TYPE_FUZZIPEDE                             = 0x25,
    ACTOR_TYPE_HURT_PLANT                            = 0x26,
    ACTOR_TYPE_M_BUSH                                = 0x27,
    ACTOR_TYPE_AQUA_FUZZY                            = 0x28,
    ACTOR_TYPE_JUNGLE_FUZZY                          = 0x29,
    ACTOR_TYPE_SPEAR_GUY                             = 0x2A,
    ACTOR_TYPE_LAVA_BUBBLE                           = 0x2B,
    ACTOR_TYPE_SPIKE_TOP                             = 0x2C,
    ACTOR_TYPE_PUTRID_PIRANHA                        = 0x2D,
    ACTOR_TYPE_LAKITU                                = 0x2E,
    ACTOR_TYPE_SPINY                                 = 0x2F,
    ACTOR_TYPE_MONTY_MOLE_BOSS                       = 0x30,
    ACTOR_TYPE_BZZAP                                 = 0x31,
    ACTOR_TYPE_CRAZEE_DAYZEE                         = 0x32,
    ACTOR_TYPE_AMAZY_DAYZEE                          = 0x33,
    ACTOR_TYPE_RUFF_PUFF                             = 0x34,
    ACTOR_TYPE_SPIKE                                 = 0x35,
    ACTOR_TYPE_GULPIT                                = 0x36,
    ACTOR_TYPE_GULPIT_ROCKS                          = 0x37,
    ACTOR_TYPE_WHITE_CLUBBA                          = 0x38,
    ACTOR_TYPE_FROST_PIRANHA                         = 0x39,
    ACTOR_TYPE_SWOOPULA                              = 0x3A,
    ACTOR_TYPE_DUPLIGHOST                            = 0x3B,
    ACTOR_TYPE_GHOST_GOOMBARIO                       = 0x3C,
    ACTOR_TYPE_GHOST_KOOPER                          = 0x3D,
    ACTOR_TYPE_GHOST_BOMBETTE                        = 0x3E,
    ACTOR_TYPE_GHOST_PARAKARRY                       = 0x3F,
    ACTOR_TYPE_GHOST_BOW                             = 0x40,
    ACTOR_TYPE_GHOST_WATT                            = 0x41,
    ACTOR_TYPE_GHOST_SUSHIE                          = 0x42,
    ACTOR_TYPE_GHOST_LAKILESTER                      = 0x43,
    ACTOR_TYPE_ALBINO_DINO                           = 0x44,
    ACTOR_TYPE_EMBER                                 = 0x45,
    ACTOR_TYPE_BONY_BEETLE                           = 0x46,
    ACTOR_TYPE_DRY_BONES                             = 0x47,
    ACTOR_TYPE_DRY_BONES2                            = 0x48,
    ACTOR_TYPE_BOMBSHELL_BLASTER                     = 0x49,
    ACTOR_TYPE_BOMBSHELL_BILL                        = 0x4A,
    ACTOR_TYPE_HAMMER_BROS                           = 0x4B,
    ACTOR_TYPE_KOOPATROL                             = 0x4C,
    ACTOR_TYPE_MAGIKOOPA                             = 0x4D,
    ACTOR_TYPE_FLYING_MAGIKOOPA                      = 0x4E,
    ACTOR_TYPE_MAGICLONE                             = 0x4F,
    ACTOR_TYPE_FLYING_MAGICLONE                      = 0x50,
    ACTOR_TYPE_RED_MAGIKOOPA                         = 0x51,
    ACTOR_TYPE_FLYING_RED_MAGIKOOPA                  = 0x52,
    ACTOR_TYPE_GREEN_MAGIKOOPA                       = 0x53,
    ACTOR_TYPE_FLYING_GREEN_MAGIKOOPA                = 0x54,
    ACTOR_TYPE_YELLOW_MAGIKOOPA                      = 0x55,
    ACTOR_TYPE_FLYING_YELLOW_MAGIKOOPA               = 0x56,
    ACTOR_TYPE_GRAY_MAGIKOOPA                        = 0x57,
    ACTOR_TYPE_FLYING_GRAY_MAGIKOOPA                 = 0x58,
    ACTOR_TYPE_WHITE_MAGIKOOPA                       = 0x59,
    ACTOR_TYPE_FLYING_WHITE_MAGIKOOPA                = 0x5A,
    ACTOR_TYPE_UNUSED_5B                             = 0x5B,
    ACTOR_TYPE_UNUSED_5C                             = 0x5C,
    ACTOR_TYPE_UNUSED_5D                             = 0x5D,
    ACTOR_TYPE_UNUSED_5E                             = 0x5E,
    ACTOR_TYPE_UNUSED_5F                             = 0x5F,
    ACTOR_TYPE_UNUSED_60                             = 0x60,
    ACTOR_TYPE_UNUSED_61                             = 0x61,
    ACTOR_TYPE_UNUSED_62                             = 0x62,
    ACTOR_TYPE_UNUSED_63                             = 0x63,
    ACTOR_TYPE_UNUSED_64                             = 0x64,
    ACTOR_TYPE_UNUSED_65                             = 0x65,
    ACTOR_TYPE_UNUSED_66                             = 0x66,
    ACTOR_TYPE_UNUSED_67                             = 0x67,
    ACTOR_TYPE_UNUSED_68                             = 0x68,
    ACTOR_TYPE_UNUSED_69                             = 0x69,
    ACTOR_TYPE_UNUSED_6A                             = 0x6A,
    ACTOR_TYPE_MONTY_HOLE                            = 0x6B,
    ACTOR_TYPE_UNUSED_6C                             = 0x6C,
    ACTOR_TYPE_UNUSED_6D                             = 0x6D,
    ACTOR_TYPE_PLAYER                                = 0x6E,
    ACTOR_TYPE_GOOMBARIO                             = 0x6F,
    ACTOR_TYPE_KOOPER                                = 0x70,
    ACTOR_TYPE_BOMBETTE                              = 0x71,
    ACTOR_TYPE_PARAKARRY                             = 0x72,
    ACTOR_TYPE_BOW                                   = 0x73,
    ACTOR_TYPE_WATT                                  = 0x74,
    ACTOR_TYPE_SUSHIE                                = 0x75,
    ACTOR_TYPE_LAKILESTER                            = 0x76,
    ACTOR_TYPE_TWINK                                 = 0x77,
    ACTOR_TYPE_UNUSED_78                             = 0x78,
    ACTOR_TYPE_UNUSED_79                             = 0x79,
    ACTOR_TYPE_THE_MASTER_1                          = 0x7A,
    ACTOR_TYPE_THE_MASTER_2                          = 0x7B,
    ACTOR_TYPE_THE_MASTER_3                          = 0x7C,
    ACTOR_TYPE_CHAN                                  = 0x7D,
    ACTOR_TYPE_LEE                                   = 0x7E,
    ACTOR_TYPE_LEE_GOOMBARIO                         = 0x7F,
    ACTOR_TYPE_LEE_KOOPER                            = 0x80,
    ACTOR_TYPE_LEE_BOMBETTE                          = 0x81,
    ACTOR_TYPE_LEE_PARAKARRY                         = 0x82,
    ACTOR_TYPE_LEE_BOW                               = 0x83,
    ACTOR_TYPE_LEE_WATT                              = 0x84,
    ACTOR_TYPE_LEE_SUSHIE                            = 0x85,
    ACTOR_TYPE_LEE_LAKILESTER                        = 0x86,
    ACTOR_TYPE_KAMMY_KOOPA                           = 0x87,
    ACTOR_TYPE_JR_TROOPA_1                           = 0x88,
    ACTOR_TYPE_JR_TROOPA_2                           = 0x89,
    ACTOR_TYPE_JR_TROOPA_3                           = 0x8A,
    ACTOR_TYPE_JR_TROOPA_4                           = 0x8B,
    ACTOR_TYPE_JR_TROOPA_5                           = 0x8C,
    ACTOR_TYPE_JR_TROOPA_6                           = 0x8D,
    ACTOR_TYPE_JR_TROOPA_DUP1                        = 0x8E,
    ACTOR_TYPE_JR_TROOPA_DUP2                        = 0x8F,
    ACTOR_TYPE_BLUE_GOOMBA_BOSS                      = 0x90,
    ACTOR_TYPE_RED_GOOMBA_BOSS                       = 0x91,
    ACTOR_TYPE_GOOMBA_KING                           = 0x92,
    ACTOR_TYPE_GOOMNUT_TREE                          = 0x93,
    ACTOR_TYPE_GOOMBARIO_TUTOR1                      = 0x94,
    ACTOR_TYPE_MAGIKOOPA_BOSS                        = 0x95,
    ACTOR_TYPE_FLYING_MAGIKOOPA_BOSS                 = 0x96,
    ACTOR_TYPE_MAGIKOOPA_DUP1                        = 0x97,
    ACTOR_TYPE_MAGIKOOPA_DUP2                        = 0x98,
    ACTOR_TYPE_FAKE_BOWSER                           = 0x99,
    ACTOR_TYPE_KOOPA_BROS                            = 0x9A,
    ACTOR_TYPE_GREEN_NINJAKOOPA                      = 0x9B,
    ACTOR_TYPE_RED_NINJAKOOPA                        = 0x9C,
    ACTOR_TYPE_BLACK_NINJAKOOPA                      = 0x9D,
    ACTOR_TYPE_YELLOW_NINJAKOOPA                     = 0x9E,
    ACTOR_TYPE_ELDSTAR                               = 0x9F,
    ACTOR_TYPE_BUZZAR                                = 0xA0,
    ACTOR_TYPE_TUTANKOOPA                            = 0xA1,
    ACTOR_TYPE_CHOMP                                 = 0xA2,
    ACTOR_TYPE_TUBBA_BLUBBA_INVINCIBLE               = 0xA3,
    ACTOR_TYPE_TUBBA_BLUBBA                          = 0xA4,
    ACTOR_TYPE_TUBBA_HEART                           = 0xA5,
    ACTOR_TYPE_STILT_GUY                             = 0xA6,
    ACTOR_TYPE_SHY_STACK                             = 0xA7,
    ACTOR_TYPE_SHY_SQUAD                             = 0xA8,
    ACTOR_TYPE_GENERAL_GUY                           = 0xA9,
    ACTOR_TYPE_TOY_TANK                              = 0xAA,
    ACTOR_TYPE_LIGHT_BULB                            = 0xAB,
    ACTOR_TYPE_SIGNAL_GUY                            = 0xAC,
    ACTOR_TYPE_SHY_SQUAD_REDUX                       = 0xAD,
    ACTOR_TYPE_SHY_SQUAD_STUB                        = 0xAE,
    ACTOR_TYPE_ANTI_GUY_OMO                          = 0xAF,
    ACTOR_TYPE_ANTI_GUY_KPA                          = 0xB0,
    ACTOR_TYPE_BIG_LANTERN_GHOST                     = 0xB1,
    ACTOR_TYPE_GOOMBA_KING_DUP                       = 0xB2,
    ACTOR_TYPE_LAVA_PIRANHA_PHASE_1                  = 0xB3,
    ACTOR_TYPE_LAVA_PIRANHA_PHASE_2                  = 0xB4,
    ACTOR_TYPE_LAVA_BUD_PHASE_1                      = 0xB5,
    ACTOR_TYPE_LAVA_BUD_PHASE_2                      = 0xB6,
    ACTOR_TYPE_PETIT_PIRANHA                         = 0xB7,
    ACTOR_TYPE_PETIT_PIRANHA_BOMB                    = 0xB8,
    ACTOR_TYPE_KENT_C_KOOPA                          = 0xB9,
    ACTOR_TYPE_HUFF_N_PUFF                           = 0xBA,
    ACTOR_TYPE_TUFF_PUFF                             = 0xBB,
    ACTOR_TYPE_MONSTAR                               = 0xBC,
    ACTOR_TYPE_CRYSTAL_KING                          = 0xBD,
    ACTOR_TYPE_CRYSTAL_CLONE                         = 0xBE,
    ACTOR_TYPE_CRYSTAL_BIT                           = 0xBF,
    ACTOR_TYPE_INTRO_BOWSER                          = 0xC0,
    ACTOR_TYPE_HALLWAY_BOWSER                        = 0xC1,
    ACTOR_TYPE_HALLWAY_BOWSER_DUP                    = 0xC2,
    ACTOR_TYPE_FINAL_BOWSER_1                        = 0xC3,
    ACTOR_TYPE_FINAL_BOWSER_1_DUP                    = 0xC4,
    ACTOR_TYPE_FINAL_BOWSER_2                        = 0xC5,
    ACTOR_TYPE_FINAL_BOWSER_2_DUP                    = 0xC6,
    ACTOR_TYPE_BLOOPER                               = 0xC7,
    ACTOR_TYPE_ELECTRO_BLOOPER1                      = 0xC8,
    ACTOR_TYPE_ELECTRO_BLOOPER2                      = 0xC9,
    ACTOR_TYPE_SUPER_BLOOPER1                        = 0xCA,
    ACTOR_TYPE_SUPER_BLOOPER2                        = 0xCB,
    ACTOR_TYPE_BLOOPER_BABY                          = 0xCC,
    ACTOR_TYPE_LAKILESTER_DUP                        = 0xCD,
    ACTOR_TYPE_SLOT_MACHINE_START                    = 0xCE,
    ACTOR_TYPE_SLOT_MACHINE_STOP                     = 0xCF,
    ACTOR_TYPE_WHACKA                                = 0xD0,
    ACTOR_TYPE_SLOT_MACHINE_START_DUP1               = 0xD1,
    ACTOR_TYPE_SLOT_MACHINE_START_DUP2               = 0xD2,
    ACTOR_TYPE_SLOT_MACHINE_START_DUP3               = 0xD3,
};

#define ACTOR_LEVEL_NONE                             99
#define ACTOR_LEVEL_RED_GOOMBA                       6
#define ACTOR_LEVEL_RED_PARAGOOMBA                   6
#define ACTOR_LEVEL_GLOOMBA                          11
#define ACTOR_LEVEL_PARAGLOOMBA                      11
#define ACTOR_LEVEL_SPIKED_GLOOMBA                   12
#define ACTOR_LEVEL_DARK_KOOPA                       18
#define ACTOR_LEVEL_DARK_PARATROOPA                  18
#define ACTOR_LEVEL_GOOMBA                           5
#define ACTOR_LEVEL_PARAGOOMBA                       6
#define ACTOR_LEVEL_SPIKED_GOOMBA                    6
#define ACTOR_LEVEL_FUZZY                            6
#define ACTOR_LEVEL_KOOPA_TROOPA                     6
#define ACTOR_LEVEL_PARATROOPA                       6
#define ACTOR_LEVEL_BOB_OMB                          6
#define ACTOR_LEVEL_BOB_OMB_DUP                      6
#define ACTOR_LEVEL_BULLET_BILL                      5
#define ACTOR_LEVEL_BILL_BLASTER                     10
#define ACTOR_LEVEL_CLEFT                            10
#define ACTOR_LEVEL_MONTY_MOLE                       8
#define ACTOR_LEVEL_BANDIT                           9
#define ACTOR_LEVEL_POKEY                            9
#define ACTOR_LEVEL_POKEY_MUMMY                      10
#define ACTOR_LEVEL_SWOOPER                          10
#define ACTOR_LEVEL_BUZZY_BEETLE                     10
#define ACTOR_LEVEL_STONE_CHOMP                      14
#define ACTOR_LEVEL_PIRANHA_PLANT                    11
#define ACTOR_LEVEL_FOREST_FUZZY                     11
#define ACTOR_LEVEL_HYPER_GOOMBA                     12
#define ACTOR_LEVEL_HYPER_PARAGOOMBA                 12
#define ACTOR_LEVEL_HYPER_CLEFT                      15
#define ACTOR_LEVEL_CLUBBA                           13
#define ACTOR_LEVEL_SHY_GUY                          14
#define ACTOR_LEVEL_GROOVE_GUY                       15
#define ACTOR_LEVEL_SKY_GUY                          14
#define ACTOR_LEVEL_MEDI_GUY                         14
#define ACTOR_LEVEL_PYRO_GUY                         15
#define ACTOR_LEVEL_SPY_GUY                          15
#define ACTOR_LEVEL_FUZZIPEDE                        43
#define ACTOR_LEVEL_HURT_PLANT                       16
#define ACTOR_LEVEL_M_BUSH                           16
#define ACTOR_LEVEL_AQUA_FUZZY                       16
#define ACTOR_LEVEL_JUNGLE_FUZZY                     16
#define ACTOR_LEVEL_SPEAR_GUY                        16
#define ACTOR_LEVEL_LAVA_BUBBLE                      17
#define ACTOR_LEVEL_SPIKE_TOP                        17
#define ACTOR_LEVEL_PUTRID_PIRANHA                   17
#define ACTOR_LEVEL_LAKITU                           20
#define ACTOR_LEVEL_SPINY                            19
#define ACTOR_LEVEL_MONTY_MOLE_BOSS                  19
#define ACTOR_LEVEL_BZZAP                            19
#define ACTOR_LEVEL_CRAZEE_DAYZEE                    19
#define ACTOR_LEVEL_AMAZY_DAYZEE                     100
#define ACTOR_LEVEL_RUFF_PUFF                        19
#define ACTOR_LEVEL_SPIKE                            40
#define ACTOR_LEVEL_GULPIT                           22
#define ACTOR_LEVEL_GULPIT_ROCKS                     0
#define ACTOR_LEVEL_WHITE_CLUBBA                     23
#define ACTOR_LEVEL_FROST_PIRANHA                    22
#define ACTOR_LEVEL_SWOOPULA                         22
#define ACTOR_LEVEL_DUPLIGHOST                       23
#define ACTOR_LEVEL_GHOST_GOOMBARIO                  23
#define ACTOR_LEVEL_GHOST_KOOPER                     23
#define ACTOR_LEVEL_GHOST_BOMBETTE                   23
#define ACTOR_LEVEL_GHOST_PARAKARRY                  23
#define ACTOR_LEVEL_GHOST_BOW                        23
#define ACTOR_LEVEL_GHOST_WATT                       23
#define ACTOR_LEVEL_GHOST_SUSHIE                     23
#define ACTOR_LEVEL_GHOST_LAKILESTER                 23
#define ACTOR_LEVEL_ALBINO_DINO                      23
#define ACTOR_LEVEL_EMBER                            24
#define ACTOR_LEVEL_BONY_BEETLE                      25
#define ACTOR_LEVEL_DRY_BONES                        30
#define ACTOR_LEVEL_DRY_BONES2                       30
#define ACTOR_LEVEL_BOMBSHELL_BLASTER                27
#define ACTOR_LEVEL_BOMBSHELL_BILL                   24
#define ACTOR_LEVEL_HAMMER_BROS                      27
#define ACTOR_LEVEL_KOOPATROL                        25
#define ACTOR_LEVEL_MAGIKOOPA                        26
#define ACTOR_LEVEL_FLYING_MAGIKOOPA                 26
#define ACTOR_LEVEL_MAGICLONE                        26
#define ACTOR_LEVEL_FLYING_MAGICLONE                 26
#define ACTOR_LEVEL_RED_MAGIKOOPA                    21
#define ACTOR_LEVEL_FLYING_RED_MAGIKOOPA             21
#define ACTOR_LEVEL_GREEN_MAGIKOOPA                  21
#define ACTOR_LEVEL_FLYING_GREEN_MAGIKOOPA           21
#define ACTOR_LEVEL_YELLOW_MAGIKOOPA                 21
#define ACTOR_LEVEL_FLYING_YELLOW_MAGIKOOPA          21
#define ACTOR_LEVEL_GRAY_MAGIKOOPA                   21
#define ACTOR_LEVEL_FLYING_GRAY_MAGIKOOPA            21
#define ACTOR_LEVEL_WHITE_MAGIKOOPA                  21
#define ACTOR_LEVEL_FLYING_WHITE_MAGIKOOPA           21
#define ACTOR_LEVEL_UNUSED_5B                        0
#define ACTOR_LEVEL_UNUSED_5C                        0
#define ACTOR_LEVEL_UNUSED_5D                        0
#define ACTOR_LEVEL_UNUSED_5E                        0
#define ACTOR_LEVEL_UNUSED_5F                        0
#define ACTOR_LEVEL_UNUSED_60                        0
#define ACTOR_LEVEL_UNUSED_61                        0
#define ACTOR_LEVEL_UNUSED_62                        0
#define ACTOR_LEVEL_UNUSED_63                        0
#define ACTOR_LEVEL_UNUSED_64                        0
#define ACTOR_LEVEL_UNUSED_65                        0
#define ACTOR_LEVEL_UNUSED_66                        0
#define ACTOR_LEVEL_UNUSED_67                        0
#define ACTOR_LEVEL_UNUSED_68                        0
#define ACTOR_LEVEL_UNUSED_69                        0
#define ACTOR_LEVEL_UNUSED_6A                        0
#define ACTOR_LEVEL_MONTY_HOLE                       9
#define ACTOR_LEVEL_UNUSED_6C                        0
#define ACTOR_LEVEL_UNUSED_6D                        0
#define ACTOR_LEVEL_PLAYER                           0
#define ACTOR_LEVEL_GOOMBARIO                        0
#define ACTOR_LEVEL_KOOPER                           0
#define ACTOR_LEVEL_BOMBETTE                         0
#define ACTOR_LEVEL_PARAKARRY                        0
#define ACTOR_LEVEL_BOW                              0
#define ACTOR_LEVEL_WATT                             0
#define ACTOR_LEVEL_SUSHIE                           0
#define ACTOR_LEVEL_LAKILESTER                       0
#define ACTOR_LEVEL_TWINK                            0
#define ACTOR_LEVEL_UNUSED_78                        0
#define ACTOR_LEVEL_UNUSED_79                        0
#define ACTOR_LEVEL_THE_MASTER_1                     0
#define ACTOR_LEVEL_THE_MASTER_2                     0
#define ACTOR_LEVEL_THE_MASTER_3                     0
#define ACTOR_LEVEL_CHAN                             0
#define ACTOR_LEVEL_LEE                              0
#define ACTOR_LEVEL_LEE_GOOMBARIO                    0
#define ACTOR_LEVEL_LEE_KOOPER                       0
#define ACTOR_LEVEL_LEE_BOMBETTE                     0
#define ACTOR_LEVEL_LEE_PARAKARRY                    0
#define ACTOR_LEVEL_LEE_BOW                          0
#define ACTOR_LEVEL_LEE_WATT                         0
#define ACTOR_LEVEL_LEE_SUSHIE                       0
#define ACTOR_LEVEL_LEE_LAKILESTER                   0
#define ACTOR_LEVEL_KAMMY_KOOPA                      99
#define ACTOR_LEVEL_JR_TROOPA_1                      41
#define ACTOR_LEVEL_JR_TROOPA_2                      44
#define ACTOR_LEVEL_JR_TROOPA_3                      52
#define ACTOR_LEVEL_JR_TROOPA_4                      59
#define ACTOR_LEVEL_JR_TROOPA_5                      65
#define ACTOR_LEVEL_JR_TROOPA_6                      74
#define ACTOR_LEVEL_JR_TROOPA_DUP1                   74
#define ACTOR_LEVEL_JR_TROOPA_DUP2                   74
#define ACTOR_LEVEL_BLUE_GOOMBA_BOSS                 20
#define ACTOR_LEVEL_RED_GOOMBA_BOSS                  20
#define ACTOR_LEVEL_GOOMBA_KING                      49
#define ACTOR_LEVEL_GOOMNUT_TREE                     1
#define ACTOR_LEVEL_GOOMBARIO_TUTOR1                 99
#define ACTOR_LEVEL_MAGIKOOPA_BOSS                   32
#define ACTOR_LEVEL_FLYING_MAGIKOOPA_BOSS            32
#define ACTOR_LEVEL_MAGIKOOPA_DUP1                   0
#define ACTOR_LEVEL_MAGIKOOPA_DUP2                   0
#define ACTOR_LEVEL_FAKE_BOWSER                      0
#define ACTOR_LEVEL_KOOPA_BROS                       0
#define ACTOR_LEVEL_GREEN_NINJAKOOPA                 16
#define ACTOR_LEVEL_RED_NINJAKOOPA                   17
#define ACTOR_LEVEL_BLACK_NINJAKOOPA                 17
#define ACTOR_LEVEL_YELLOW_NINJAKOOPA                16
#define ACTOR_LEVEL_ELDSTAR                          99
#define ACTOR_LEVEL_BUZZAR                           35
#define ACTOR_LEVEL_TUTANKOOPA                       55
#define ACTOR_LEVEL_CHOMP                            14
#define ACTOR_LEVEL_TUBBA_BLUBBA_INVINCIBLE          70
#define ACTOR_LEVEL_TUBBA_BLUBBA                     0
#define ACTOR_LEVEL_TUBBA_HEART                      0
#define ACTOR_LEVEL_STILT_GUY                        0
#define ACTOR_LEVEL_SHY_STACK                        0
#define ACTOR_LEVEL_SHY_SQUAD                        0
#define ACTOR_LEVEL_GENERAL_GUY                      73
#define ACTOR_LEVEL_TOY_TANK                         0
#define ACTOR_LEVEL_LIGHT_BULB                       0
#define ACTOR_LEVEL_SIGNAL_GUY                       0
#define ACTOR_LEVEL_SHY_SQUAD_REDUX                  0
#define ACTOR_LEVEL_SHY_SQUAD_STUB                   0
#define ACTOR_LEVEL_ANTI_GUY_OMO                     42
#define ACTOR_LEVEL_ANTI_GUY_KPA                     42
#define ACTOR_LEVEL_BIG_LANTERN_GHOST                42
#define ACTOR_LEVEL_GOOMBA_KING_DUP                  49
#define ACTOR_LEVEL_LAVA_PIRANHA_PHASE_1             45
#define ACTOR_LEVEL_LAVA_PIRANHA_PHASE_2             45
#define ACTOR_LEVEL_LAVA_BUD_PHASE_1                 0
#define ACTOR_LEVEL_LAVA_BUD_PHASE_2                 0
#define ACTOR_LEVEL_PETIT_PIRANHA                    0
#define ACTOR_LEVEL_PETIT_PIRANHA_BOMB               0
#define ACTOR_LEVEL_KENT_C_KOOPA                     55
#define ACTOR_LEVEL_HUFF_N_PUFF                      80
#define ACTOR_LEVEL_TUFF_PUFF                        0
#define ACTOR_LEVEL_MONSTAR                          45
#define ACTOR_LEVEL_CRYSTAL_KING                     85
#define ACTOR_LEVEL_CRYSTAL_CLONE                    0
#define ACTOR_LEVEL_CRYSTAL_BIT                      0
#define ACTOR_LEVEL_INTRO_BOWSER                     0
#define ACTOR_LEVEL_HALLWAY_BOWSER                   100
#define ACTOR_LEVEL_HALLWAY_BOWSER_DUP               100
#define ACTOR_LEVEL_FINAL_BOWSER_1                   0
#define ACTOR_LEVEL_FINAL_BOWSER_1_DUP               0
#define ACTOR_LEVEL_FINAL_BOWSER_2                   0
#define ACTOR_LEVEL_FINAL_BOWSER_2_DUP               0
#define ACTOR_LEVEL_BLOOPER                          44
#define ACTOR_LEVEL_ELECTRO_BLOOPER1                 50
#define ACTOR_LEVEL_ELECTRO_BLOOPER2                 50
#define ACTOR_LEVEL_SUPER_BLOOPER1                   65
#define ACTOR_LEVEL_SUPER_BLOOPER2                   65
#define ACTOR_LEVEL_BLOOPER_BABY                     0
#define ACTOR_LEVEL_LAKILESTER_DUP                   0
#define ACTOR_LEVEL_SLOT_MACHINE_START               99
#define ACTOR_LEVEL_SLOT_MACHINE_STOP                99
#define ACTOR_LEVEL_WHACKA                           0
#define ACTOR_LEVEL_SLOT_MACHINE_START_DUP1          0
#define ACTOR_LEVEL_SLOT_MACHINE_START_DUP2          0
#define ACTOR_LEVEL_SLOT_MACHINE_START_DUP3          0

#endif // ACTORS_ENUM_H
