// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_ALTBANDIT_H_
#define _NPC_SPRITE_ALTBANDIT_H_

#include "types.h"

#define SPR_AltBandit 0x9C

#define SPR_PAL_AltBandit_Blue 0x0
#define SPR_PAL_AltBandit_Red 0x1
#define SPR_PAL_AltBandit_Smoke 0x2

#define ANIM_AltBandit_Blue_Still                               0x9C0000
#define ANIM_AltBandit_Blue_Idle                                0x9C0001
#define ANIM_AltBandit_Blue_CarryIdle                           0x9C0002
#define ANIM_AltBandit_Blue_Walk                                0x9C0003
#define ANIM_AltBandit_Blue_CarryWalk                           0x9C0004
#define ANIM_AltBandit_Blue_Run                                 0x9C0005
#define ANIM_AltBandit_Blue_CarryRun                            0x9C0006
#define ANIM_AltBandit_Blue_Hurt                                0x9C0007
#define ANIM_AltBandit_Blue_BurnHurt                            0x9C0008
#define ANIM_AltBandit_Blue_BurnStill                           0x9C0009
#define ANIM_AltBandit_Blue_SmokeCloud                          0x9C000A
#define ANIM_AltBandit_Blue_Tackle                              0x9C000B
#define ANIM_AltBandit_Blue_LookUp                              0x9C000C
#define ANIM_AltBandit_Blue_Taunt                               0x9C000D
#define ANIM_AltBandit_Blue_Talk                                0x9C000E

#define ANIM_AltBandit_Red_Still                                0x9C0100
#define ANIM_AltBandit_Red_Idle                                 0x9C0101
#define ANIM_AltBandit_Red_CarryIdle                            0x9C0102
#define ANIM_AltBandit_Red_Walk                                 0x9C0103
#define ANIM_AltBandit_Red_CarryWalk                            0x9C0104
#define ANIM_AltBandit_Red_Run                                  0x9C0105
#define ANIM_AltBandit_Red_CarryRun                             0x9C0106
#define ANIM_AltBandit_Red_Hurt                                 0x9C0107
#define ANIM_AltBandit_Red_BurnHurt                             0x9C0108
#define ANIM_AltBandit_Red_BurnStill                            0x9C0109
#define ANIM_AltBandit_Red_SmokeCloud                           0x9C010A
#define ANIM_AltBandit_Red_Tackle                               0x9C010B
#define ANIM_AltBandit_Red_LookUp                               0x9C010C
#define ANIM_AltBandit_Red_Taunt                                0x9C010D
#define ANIM_AltBandit_Red_Talk                                 0x9C010E

#define ANIM_AltBandit_Smoke_Still                              0x9C0200
#define ANIM_AltBandit_Smoke_Idle                               0x9C0201
#define ANIM_AltBandit_Smoke_CarryIdle                          0x9C0202
#define ANIM_AltBandit_Smoke_Walk                               0x9C0203
#define ANIM_AltBandit_Smoke_CarryWalk                          0x9C0204
#define ANIM_AltBandit_Smoke_Run                                0x9C0205
#define ANIM_AltBandit_Smoke_CarryRun                           0x9C0206
#define ANIM_AltBandit_Smoke_Hurt                               0x9C0207
#define ANIM_AltBandit_Smoke_BurnHurt                           0x9C0208
#define ANIM_AltBandit_Smoke_BurnStill                          0x9C0209
#define ANIM_AltBandit_Smoke_SmokeCloud                         0x9C020A
#define ANIM_AltBandit_Smoke_Tackle                             0x9C020B
#define ANIM_AltBandit_Smoke_LookUp                             0x9C020C
#define ANIM_AltBandit_Smoke_Taunt                              0x9C020D
#define ANIM_AltBandit_Smoke_Talk                               0x9C020E

#endif
