// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_BARTENDER_H_
#define _NPC_SPRITE_BARTENDER_H_

#include "types.h"

#define SPR_Bartender 0xAC

#define SPR_PAL_Bartender 0x0

#define ANIM_Bartender_Still                                    0xAC0000
#define ANIM_Bartender_Idle                                     0xAC0001
#define ANIM_Bartender_Walk                                     0xAC0002
#define ANIM_Bartender_Run                                      0xAC0003
#define ANIM_Bartender_StrumGuitar                              0xAC0004
#define ANIM_Bartender_Talk                                     0xAC0005

#endif
