// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_BATTLEKOLORADO_H_
#define _NPC_SPRITE_BATTLEKOLORADO_H_

#include "types.h"

#define SPR_BattleKolorado 0xB7

#define SPR_PAL_BattleKolorado 0x0

#define ANIM_BattleKolorado_Idle                                0xB70000
#define ANIM_BattleKolorado_ShoutStill                          0xB70001
#define ANIM_BattleKolorado_WalkSad                             0xB70002
#define ANIM_BattleKolorado_Run                                 0xB70003
#define ANIM_BattleKolorado_Shout                               0xB70004
#define ANIM_BattleKolorado_Hurt                                0xB70005
#define ANIM_BattleKolorado_Injured                             0xB70006

#endif
