// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_BATTLEKALMAR_H_
#define _NPC_SPRITE_BATTLEKALMAR_H_

#include "types.h"

#define SPR_BattleKalmar 0x1F

#define SPR_PAL_BattleKalmar 0x0
#define SPR_PAL_BattleKalmar_Glowing 0x1

#define ANIM_BattleKalmar_Still                                 0x1F0000
#define ANIM_BattleKalmar_Idle                                  0x1F0001
#define ANIM_BattleKalmar_Shout                                 0x1F0002

#define ANIM_BattleKalmar_Glowing_Still                         0x1F0100
#define ANIM_BattleKalmar_Glowing_Idle                          0x1F0101
#define ANIM_BattleKalmar_Glowing_Shout                         0x1F0102

#endif
