// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_BATTLESKOLAR_H_
#define _NPC_SPRITE_BATTLESKOLAR_H_

#include "types.h"

#define SPR_BattleSkolar 0x1B

#define SPR_PAL_BattleSkolar 0x0
#define SPR_PAL_BattleSkolar_Glowing 0x1

#define ANIM_BattleSkolar_Still                                 0x1B0000
#define ANIM_BattleSkolar_Idle                                  0x1B0001
#define ANIM_BattleSkolar_Shout                                 0x1B0002

#define ANIM_BattleSkolar_Glowing_Still                         0x1B0100
#define ANIM_BattleSkolar_Glowing_Idle                          0x1B0101
#define ANIM_BattleSkolar_Glowing_Shout                         0x1B0102

#endif
