// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_BATTLEMUSKULAR_H_
#define _NPC_SPRITE_BATTLEMUSKULAR_H_

#include "types.h"

#define SPR_BattleMuskular 0x1C

#define SPR_PAL_BattleMuskular 0x0
#define SPR_PAL_BattleMuskular_Glowing 0x1

#define ANIM_BattleMuskular_Still                               0x1C0000
#define ANIM_BattleMuskular_Idle                                0x1C0001
#define ANIM_BattleMuskular_Shout                               0x1C0002

#define ANIM_BattleMuskular_Glowing_Still                       0x1C0100
#define ANIM_BattleMuskular_Glowing_Idle                        0x1C0101
#define ANIM_BattleMuskular_Glowing_Shout                       0x1C0102

#endif
