// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_BATTLEMAMAR_H_
#define _NPC_SPRITE_BATTLEMAMAR_H_

#include "types.h"

#define SPR_BattleMamar 0x1A

#define SPR_PAL_BattleMamar 0x0
#define SPR_PAL_BattleMamar_Glowing 0x1

#define ANIM_BattleMamar_Still                                  0x1A0000
#define ANIM_BattleMamar_Idle                                   0x1A0001
#define ANIM_BattleMamar_Shout                                  0x1A0002

#define ANIM_BattleMamar_Glowing_Still                          0x1A0100
#define ANIM_BattleMamar_Glowing_Idle                           0x1A0101
#define ANIM_BattleMamar_Glowing_Shout                          0x1A0102

#endif
