// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_BOO_H_
#define _NPC_SPRITE_BOO_H_

#include "types.h"

#define SPR_Boo 0x95

#define SPR_PAL_Boo 0x0
#define SPR_PAL_Boo_Tan 0x1

#define ANIM_Boo_Still                                          0x950000
#define ANIM_Boo_Idle                                           0x950001
#define ANIM_Boo_Walk                                           0x950002
#define ANIM_Boo_Run                                            0x950003
#define ANIM_Boo_Talk                                           0x950004
#define ANIM_Boo_Wave                                           0x950005
#define ANIM_Boo_Flail                                          0x950006
#define ANIM_Boo_Conceal                                        0x950007
#define ANIM_Boo_Spook                                          0x950008
#define ANIM_Boo_Cower                                          0x950009
#define ANIM_Boo_Confused                                       0x95000A
#define ANIM_Boo_Throw                                          0x95000B
#define ANIM_Boo_CarryStill                                     0x95000C
#define ANIM_Boo_CarryIdle                                      0x95000D
#define ANIM_Boo_CarryWalk                                      0x95000E
#define ANIM_Boo_CarryRun                                       0x95000F
#define ANIM_Boo_CarryTalk                                      0x950010
#define ANIM_Boo_CarryHappy                                     0x950011

#define ANIM_Boo_Tan_Still                                      0x950100
#define ANIM_Boo_Tan_Idle                                       0x950101
#define ANIM_Boo_Tan_Walk                                       0x950102
#define ANIM_Boo_Tan_Run                                        0x950103
#define ANIM_Boo_Tan_Talk                                       0x950104
#define ANIM_Boo_Tan_Wave                                       0x950105
#define ANIM_Boo_Tan_Flail                                      0x950106
#define ANIM_Boo_Tan_Conceal                                    0x950107
#define ANIM_Boo_Tan_Spook                                      0x950108
#define ANIM_Boo_Tan_Cower                                      0x950109
#define ANIM_Boo_Tan_Confused                                   0x95010A
#define ANIM_Boo_Tan_Throw                                      0x95010B
#define ANIM_Boo_Tan_CarryStill                                 0x95010C
#define ANIM_Boo_Tan_CarryIdle                                  0x95010D
#define ANIM_Boo_Tan_CarryWalk                                  0x95010E
#define ANIM_Boo_Tan_CarryRun                                   0x95010F
#define ANIM_Boo_Tan_CarryTalk                                  0x950110
#define ANIM_Boo_Tan_CarryHappy                                 0x950111

#endif
