// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_BOOTLER_H_
#define _NPC_SPRITE_BOOTLER_H_

#include "types.h"

#define SPR_Bootler 0xBF

#define SPR_PAL_Bootler 0x0

#define ANIM_Bootler_Still                                      0xBF0000
#define ANIM_Bootler_Idle                                       0xBF0001
#define ANIM_Bootler_Walk                                       0xBF0002
#define ANIM_Bootler_Run                                        0xBF0003
#define ANIM_Bootler_Talk                                       0xBF0004
#define ANIM_Bootler_Shock                                      0xBF0005
#define ANIM_Bootler_Panic                                      0xBF0006
#define ANIM_Bootler_Dejected                                   0xBF0007
#define ANIM_Bootler_Quaver                                     0xBF0008
#define ANIM_Bootler_Spook                                      0xBF0009
#define ANIM_Bootler_SpookStill                                 0xBF000A
#define ANIM_Bootler_Flail                                      0xBF000B
#define ANIM_Bootler_TapChest                                   0xBF000C

#endif
