// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_BUBULB_H_
#define _NPC_SPRITE_BUBULB_H_

#include "types.h"

#define SPR_Bubulb 0x99

#define SPR_PAL_Bubulb_Pink 0x0
#define SPR_PAL_Bubulb_Purple 0x1
#define SPR_PAL_Bubulb_Green 0x2
#define SPR_PAL_Bubulb_Yellow 0x3
#define SPR_PAL_Bubulb_Lighter 0x4
#define SPR_PAL_Bubulb_Hole 0x5
#define SPR_PAL_Bubulb_Darker 0x6
#define SPR_PAL_Bubulb_Unused1 0x7
#define SPR_PAL_Bubulb_Unused2 0x8
#define SPR_PAL_Bubulb_Unused3 0x9

#define ANIM_Bubulb_Pink_Still                                  0x990000
#define ANIM_Bubulb_Pink_BuriedStill                            0x990001
#define ANIM_Bubulb_Pink_Idle                                   0x990002
#define ANIM_Bubulb_Pink_Talk                                   0x990003
#define ANIM_Bubulb_Pink_HappyUpbeat                            0x990004
#define ANIM_Bubulb_Pink_PopUp                                  0x990005
#define ANIM_Bubulb_Pink_Bloom                                  0x990006
#define ANIM_Bubulb_Pink_BuriedIdle                             0x990007
#define ANIM_Bubulb_Pink_HappyGentle                            0x990008
#define ANIM_Bubulb_Pink_HappyTalk                              0x990009
#define ANIM_Bubulb_Pink_EmbedIdle                              0x99000A
#define ANIM_Bubulb_Pink_DarkWalk                               0x99000B
#define ANIM_Bubulb_Pink_DarkStepLeft                           0x99000C
#define ANIM_Bubulb_Pink_DarkStepRight                          0x99000D
#define ANIM_Bubulb_Pink_Walk                                   0x99000E
#define ANIM_Bubulb_Pink_Run                                    0x99000F

#define ANIM_Bubulb_Purple_Still                                0x990100
#define ANIM_Bubulb_Purple_BuriedStill                          0x990101
#define ANIM_Bubulb_Purple_Idle                                 0x990102
#define ANIM_Bubulb_Purple_Talk                                 0x990103
#define ANIM_Bubulb_Purple_HappyUpbeat                          0x990104
#define ANIM_Bubulb_Purple_PopUp                                0x990105
#define ANIM_Bubulb_Purple_Bloom                                0x990106
#define ANIM_Bubulb_Purple_BuriedIdle                           0x990107
#define ANIM_Bubulb_Purple_HappyGentle                          0x990108
#define ANIM_Bubulb_Purple_HappyTalk                            0x990109
#define ANIM_Bubulb_Purple_EmbedIdle                            0x99010A
#define ANIM_Bubulb_Purple_DarkWalk                             0x99010B
#define ANIM_Bubulb_Purple_DarkStepLeft                         0x99010C
#define ANIM_Bubulb_Purple_DarkStepRight                        0x99010D
#define ANIM_Bubulb_Purple_Walk                                 0x99010E
#define ANIM_Bubulb_Purple_Run                                  0x99010F

#define ANIM_Bubulb_Green_Still                                 0x990200
#define ANIM_Bubulb_Green_BuriedStill                           0x990201
#define ANIM_Bubulb_Green_Idle                                  0x990202
#define ANIM_Bubulb_Green_Talk                                  0x990203
#define ANIM_Bubulb_Green_HappyUpbeat                           0x990204
#define ANIM_Bubulb_Green_PopUp                                 0x990205
#define ANIM_Bubulb_Green_Bloom                                 0x990206
#define ANIM_Bubulb_Green_BuriedIdle                            0x990207
#define ANIM_Bubulb_Green_HappyGentle                           0x990208
#define ANIM_Bubulb_Green_HappyTalk                             0x990209
#define ANIM_Bubulb_Green_EmbedIdle                             0x99020A
#define ANIM_Bubulb_Green_DarkWalk                              0x99020B
#define ANIM_Bubulb_Green_DarkStepLeft                          0x99020C
#define ANIM_Bubulb_Green_DarkStepRight                         0x99020D
#define ANIM_Bubulb_Green_Walk                                  0x99020E
#define ANIM_Bubulb_Green_Run                                   0x99020F

#define ANIM_Bubulb_Yellow_Still                                0x990300
#define ANIM_Bubulb_Yellow_BuriedStill                          0x990301
#define ANIM_Bubulb_Yellow_Idle                                 0x990302
#define ANIM_Bubulb_Yellow_Talk                                 0x990303
#define ANIM_Bubulb_Yellow_HappyUpbeat                          0x990304
#define ANIM_Bubulb_Yellow_PopUp                                0x990305
#define ANIM_Bubulb_Yellow_Bloom                                0x990306
#define ANIM_Bubulb_Yellow_BuriedIdle                           0x990307
#define ANIM_Bubulb_Yellow_HappyGentle                          0x990308
#define ANIM_Bubulb_Yellow_HappyTalk                            0x990309
#define ANIM_Bubulb_Yellow_EmbedIdle                            0x99030A
#define ANIM_Bubulb_Yellow_DarkWalk                             0x99030B
#define ANIM_Bubulb_Yellow_DarkStepLeft                         0x99030C
#define ANIM_Bubulb_Yellow_DarkStepRight                        0x99030D
#define ANIM_Bubulb_Yellow_Walk                                 0x99030E
#define ANIM_Bubulb_Yellow_Run                                  0x99030F

#define ANIM_Bubulb_Lighter_Still                               0x990400
#define ANIM_Bubulb_Lighter_BuriedStill                         0x990401
#define ANIM_Bubulb_Lighter_Idle                                0x990402
#define ANIM_Bubulb_Lighter_Talk                                0x990403
#define ANIM_Bubulb_Lighter_HappyUpbeat                         0x990404
#define ANIM_Bubulb_Lighter_PopUp                               0x990405
#define ANIM_Bubulb_Lighter_Bloom                               0x990406
#define ANIM_Bubulb_Lighter_BuriedIdle                          0x990407
#define ANIM_Bubulb_Lighter_HappyGentle                         0x990408
#define ANIM_Bubulb_Lighter_HappyTalk                           0x990409
#define ANIM_Bubulb_Lighter_EmbedIdle                           0x99040A
#define ANIM_Bubulb_Lighter_DarkWalk                            0x99040B
#define ANIM_Bubulb_Lighter_DarkStepLeft                        0x99040C
#define ANIM_Bubulb_Lighter_DarkStepRight                       0x99040D
#define ANIM_Bubulb_Lighter_Walk                                0x99040E
#define ANIM_Bubulb_Lighter_Run                                 0x99040F

#define ANIM_Bubulb_Hole_Still                                  0x990500
#define ANIM_Bubulb_Hole_BuriedStill                            0x990501
#define ANIM_Bubulb_Hole_Idle                                   0x990502
#define ANIM_Bubulb_Hole_Talk                                   0x990503
#define ANIM_Bubulb_Hole_HappyUpbeat                            0x990504
#define ANIM_Bubulb_Hole_PopUp                                  0x990505
#define ANIM_Bubulb_Hole_Bloom                                  0x990506
#define ANIM_Bubulb_Hole_BuriedIdle                             0x990507
#define ANIM_Bubulb_Hole_HappyGentle                            0x990508
#define ANIM_Bubulb_Hole_HappyTalk                              0x990509
#define ANIM_Bubulb_Hole_EmbedIdle                              0x99050A
#define ANIM_Bubulb_Hole_DarkWalk                               0x99050B
#define ANIM_Bubulb_Hole_DarkStepLeft                           0x99050C
#define ANIM_Bubulb_Hole_DarkStepRight                          0x99050D
#define ANIM_Bubulb_Hole_Walk                                   0x99050E
#define ANIM_Bubulb_Hole_Run                                    0x99050F

#define ANIM_Bubulb_Darker_Still                                0x990600
#define ANIM_Bubulb_Darker_BuriedStill                          0x990601
#define ANIM_Bubulb_Darker_Idle                                 0x990602
#define ANIM_Bubulb_Darker_Talk                                 0x990603
#define ANIM_Bubulb_Darker_HappyUpbeat                          0x990604
#define ANIM_Bubulb_Darker_PopUp                                0x990605
#define ANIM_Bubulb_Darker_Bloom                                0x990606
#define ANIM_Bubulb_Darker_BuriedIdle                           0x990607
#define ANIM_Bubulb_Darker_HappyGentle                          0x990608
#define ANIM_Bubulb_Darker_HappyTalk                            0x990609
#define ANIM_Bubulb_Darker_EmbedIdle                            0x99060A
#define ANIM_Bubulb_Darker_DarkWalk                             0x99060B
#define ANIM_Bubulb_Darker_DarkStepLeft                         0x99060C
#define ANIM_Bubulb_Darker_DarkStepRight                        0x99060D
#define ANIM_Bubulb_Darker_Walk                                 0x99060E
#define ANIM_Bubulb_Darker_Run                                  0x99060F

#define ANIM_Bubulb_Unused1_Still                               0x990700
#define ANIM_Bubulb_Unused1_BuriedStill                         0x990701
#define ANIM_Bubulb_Unused1_Idle                                0x990702
#define ANIM_Bubulb_Unused1_Talk                                0x990703
#define ANIM_Bubulb_Unused1_HappyUpbeat                         0x990704
#define ANIM_Bubulb_Unused1_PopUp                               0x990705
#define ANIM_Bubulb_Unused1_Bloom                               0x990706
#define ANIM_Bubulb_Unused1_BuriedIdle                          0x990707
#define ANIM_Bubulb_Unused1_HappyGentle                         0x990708
#define ANIM_Bubulb_Unused1_HappyTalk                           0x990709
#define ANIM_Bubulb_Unused1_EmbedIdle                           0x99070A
#define ANIM_Bubulb_Unused1_DarkWalk                            0x99070B
#define ANIM_Bubulb_Unused1_DarkStepLeft                        0x99070C
#define ANIM_Bubulb_Unused1_DarkStepRight                       0x99070D
#define ANIM_Bubulb_Unused1_Walk                                0x99070E
#define ANIM_Bubulb_Unused1_Run                                 0x99070F

#define ANIM_Bubulb_Unused2_Still                               0x990800
#define ANIM_Bubulb_Unused2_BuriedStill                         0x990801
#define ANIM_Bubulb_Unused2_Idle                                0x990802
#define ANIM_Bubulb_Unused2_Talk                                0x990803
#define ANIM_Bubulb_Unused2_HappyUpbeat                         0x990804
#define ANIM_Bubulb_Unused2_PopUp                               0x990805
#define ANIM_Bubulb_Unused2_Bloom                               0x990806
#define ANIM_Bubulb_Unused2_BuriedIdle                          0x990807
#define ANIM_Bubulb_Unused2_HappyGentle                         0x990808
#define ANIM_Bubulb_Unused2_HappyTalk                           0x990809
#define ANIM_Bubulb_Unused2_EmbedIdle                           0x99080A
#define ANIM_Bubulb_Unused2_DarkWalk                            0x99080B
#define ANIM_Bubulb_Unused2_DarkStepLeft                        0x99080C
#define ANIM_Bubulb_Unused2_DarkStepRight                       0x99080D
#define ANIM_Bubulb_Unused2_Walk                                0x99080E
#define ANIM_Bubulb_Unused2_Run                                 0x99080F

#define ANIM_Bubulb_Unused3_Still                               0x990900
#define ANIM_Bubulb_Unused3_BuriedStill                         0x990901
#define ANIM_Bubulb_Unused3_Idle                                0x990902
#define ANIM_Bubulb_Unused3_Talk                                0x990903
#define ANIM_Bubulb_Unused3_HappyUpbeat                         0x990904
#define ANIM_Bubulb_Unused3_PopUp                               0x990905
#define ANIM_Bubulb_Unused3_Bloom                               0x990906
#define ANIM_Bubulb_Unused3_BuriedIdle                          0x990907
#define ANIM_Bubulb_Unused3_HappyGentle                         0x990908
#define ANIM_Bubulb_Unused3_HappyTalk                           0x990909
#define ANIM_Bubulb_Unused3_EmbedIdle                           0x99090A
#define ANIM_Bubulb_Unused3_DarkWalk                            0x99090B
#define ANIM_Bubulb_Unused3_DarkStepLeft                        0x99090C
#define ANIM_Bubulb_Unused3_DarkStepRight                       0x99090D
#define ANIM_Bubulb_Unused3_Walk                                0x99090E
#define ANIM_Bubulb_Unused3_Run                                 0x99090F

#endif
