// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_BUSHBASIC_H_
#define _NPC_SPRITE_BUSHBASIC_H_

#include "types.h"

#define SPR_BushBasic 0x5B

#define SPR_PAL_BushBasic 0x0

#define ANIM_BushBasic_Still                                    0x5B0000
#define ANIM_BushBasic_Shake                                    0x5B0001

#endif
