// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_BUSHBLOCKY_H_
#define _NPC_SPRITE_BUSHBLOCKY_H_

#include "types.h"

#define SPR_BushBlocky 0x5C

#define SPR_PAL_BushBlocky 0x0

#define ANIM_BushBlocky_Still                                   0x5C0000
#define ANIM_BushBlocky_Shake                                   0x5C0001

#endif
