// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_BUSHDRY_H_
#define _NPC_SPRITE_BUSHDRY_H_

#include "types.h"

#define SPR_BushDry 0x5D

#define SPR_PAL_BushDry 0x0

#define ANIM_BushDry_Still                                      0x5D0000
#define ANIM_BushDry_Shake                                      0x5D0001

#endif
