// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_BUSHMATTED_H_
#define _NPC_SPRITE_BUSHMATTED_H_

#include "types.h"

#define SPR_BushMatted 0x5F

#define SPR_PAL_BushMatted 0x0

#define ANIM_BushMatted_Still                                   0x5F0000
#define ANIM_BushMatted_Shake                                   0x5F0001

#endif
