// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_BZZAP_H_
#define _NPC_SPRITE_BZZAP_H_

#include "types.h"

#define SPR_Bzzap 0x4B

#define SPR_PAL_Bzzap 0x0
#define SPR_PAL_Bzzap_Poisoned 0x1
#define SPR_PAL_Bzzap_Dizzy 0x2
#define SPR_PAL_Bzzap_Shocked 0x3
#define SPR_PAL_Bzzap_Burnt 0x4

#define ANIM_Bzzap_Anim00                                       0x4B0000
#define ANIM_Bzzap_Anim01                                       0x4B0001
#define ANIM_Bzzap_Anim02                                       0x4B0002
#define ANIM_Bzzap_Anim03                                       0x4B0003
#define ANIM_Bzzap_Anim04                                       0x4B0004
#define ANIM_Bzzap_Anim05                                       0x4B0005
#define ANIM_Bzzap_Anim06                                       0x4B0006
#define ANIM_Bzzap_Anim07                                       0x4B0007
#define ANIM_Bzzap_Anim08                                       0x4B0008
#define ANIM_Bzzap_Anim09                                       0x4B0009
#define ANIM_Bzzap_Anim0A                                       0x4B000A
#define ANIM_Bzzap_Anim0B                                       0x4B000B

#define ANIM_Bzzap_Poisoned_Anim00                              0x4B0100
#define ANIM_Bzzap_Poisoned_Anim01                              0x4B0101
#define ANIM_Bzzap_Poisoned_Anim02                              0x4B0102
#define ANIM_Bzzap_Poisoned_Anim03                              0x4B0103
#define ANIM_Bzzap_Poisoned_Anim04                              0x4B0104
#define ANIM_Bzzap_Poisoned_Anim05                              0x4B0105
#define ANIM_Bzzap_Poisoned_Anim06                              0x4B0106
#define ANIM_Bzzap_Poisoned_Anim07                              0x4B0107
#define ANIM_Bzzap_Poisoned_Anim08                              0x4B0108
#define ANIM_Bzzap_Poisoned_Anim09                              0x4B0109
#define ANIM_Bzzap_Poisoned_Anim0A                              0x4B010A
#define ANIM_Bzzap_Poisoned_Anim0B                              0x4B010B

#define ANIM_Bzzap_Dizzy_Anim00                                 0x4B0200
#define ANIM_Bzzap_Dizzy_Anim01                                 0x4B0201
#define ANIM_Bzzap_Dizzy_Anim02                                 0x4B0202
#define ANIM_Bzzap_Dizzy_Anim03                                 0x4B0203
#define ANIM_Bzzap_Dizzy_Anim04                                 0x4B0204
#define ANIM_Bzzap_Dizzy_Anim05                                 0x4B0205
#define ANIM_Bzzap_Dizzy_Anim06                                 0x4B0206
#define ANIM_Bzzap_Dizzy_Anim07                                 0x4B0207
#define ANIM_Bzzap_Dizzy_Anim08                                 0x4B0208
#define ANIM_Bzzap_Dizzy_Anim09                                 0x4B0209
#define ANIM_Bzzap_Dizzy_Anim0A                                 0x4B020A
#define ANIM_Bzzap_Dizzy_Anim0B                                 0x4B020B

#define ANIM_Bzzap_Shocked_Anim00                               0x4B0300
#define ANIM_Bzzap_Shocked_Anim01                               0x4B0301
#define ANIM_Bzzap_Shocked_Anim02                               0x4B0302
#define ANIM_Bzzap_Shocked_Anim03                               0x4B0303
#define ANIM_Bzzap_Shocked_Anim04                               0x4B0304
#define ANIM_Bzzap_Shocked_Anim05                               0x4B0305
#define ANIM_Bzzap_Shocked_Anim06                               0x4B0306
#define ANIM_Bzzap_Shocked_Anim07                               0x4B0307
#define ANIM_Bzzap_Shocked_Anim08                               0x4B0308
#define ANIM_Bzzap_Shocked_Anim09                               0x4B0309
#define ANIM_Bzzap_Shocked_Anim0A                               0x4B030A
#define ANIM_Bzzap_Shocked_Anim0B                               0x4B030B

#define ANIM_Bzzap_Burnt_Anim00                                 0x4B0400
#define ANIM_Bzzap_Burnt_Anim01                                 0x4B0401
#define ANIM_Bzzap_Burnt_Anim02                                 0x4B0402
#define ANIM_Bzzap_Burnt_Anim03                                 0x4B0403
#define ANIM_Bzzap_Burnt_Anim04                                 0x4B0404
#define ANIM_Bzzap_Burnt_Anim05                                 0x4B0405
#define ANIM_Bzzap_Burnt_Anim06                                 0x4B0406
#define ANIM_Bzzap_Burnt_Anim07                                 0x4B0407
#define ANIM_Bzzap_Burnt_Anim08                                 0x4B0408
#define ANIM_Bzzap_Burnt_Anim09                                 0x4B0409
#define ANIM_Bzzap_Burnt_Anim0A                                 0x4B040A
#define ANIM_Bzzap_Burnt_Anim0B                                 0x4B040B

#endif
