// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_CHAN_H_
#define _NPC_SPRITE_CHAN_H_

#include "types.h"

#define SPR_Chan 0xA3

#define SPR_PAL_Chan 0x0
#define SPR_PAL_Chan_Poisoned 0x1
#define SPR_PAL_Chan_Dizzy 0x2
#define SPR_PAL_Chan_Shocked 0x3
#define SPR_PAL_Chan_Burnt 0x4

#define ANIM_Chan_Still                                         0xA30000
#define ANIM_Chan_Idle                                          0xA30001
#define ANIM_Chan_Toppled                                       0xA30002
#define ANIM_Chan_Walk                                          0xA30003
#define ANIM_Chan_Run                                           0xA30004
#define ANIM_Chan_ShellSpin                                     0xA30005
#define ANIM_Chan_Hurt                                          0xA30006
#define ANIM_Chan_ToppledHurt                                   0xA30007
#define ANIM_Chan_HurtAlt                                       0xA30008
#define ANIM_Chan_ShellStill                                    0xA30009
#define ANIM_Chan_Sleep                                         0xA3000A
#define ANIM_Chan_Dizzy                                         0xA3000B
#define ANIM_Chan_EnterShell                                    0xA3000C
#define ANIM_Chan_ExitShell                                     0xA3000D
#define ANIM_Chan_ToppledHurtAlt                                0xA3000E
#define ANIM_Chan_ToppledStill                                  0xA3000F
#define ANIM_Chan_ToppledSleep                                  0xA30010
#define ANIM_Chan_ToppledDizzy                                  0xA30011
#define ANIM_Chan_Empty                                         0xA30012
#define ANIM_Chan_EmptyStill                                    0xA30013
#define ANIM_Chan_ToppledBurnHurt                               0xA30014
#define ANIM_Chan_ToppledBurnStill                              0xA30015

#define ANIM_Chan_Poisoned_Still                                0xA30100
#define ANIM_Chan_Poisoned_Idle                                 0xA30101
#define ANIM_Chan_Poisoned_Toppled                              0xA30102
#define ANIM_Chan_Poisoned_Walk                                 0xA30103
#define ANIM_Chan_Poisoned_Run                                  0xA30104
#define ANIM_Chan_Poisoned_ShellSpin                            0xA30105
#define ANIM_Chan_Poisoned_Hurt                                 0xA30106
#define ANIM_Chan_Poisoned_ToppledHurt                          0xA30107
#define ANIM_Chan_Poisoned_HurtAlt                              0xA30108
#define ANIM_Chan_Poisoned_ShellStill                           0xA30109
#define ANIM_Chan_Poisoned_Sleep                                0xA3010A
#define ANIM_Chan_Poisoned_Dizzy                                0xA3010B
#define ANIM_Chan_Poisoned_EnterShell                           0xA3010C
#define ANIM_Chan_Poisoned_ExitShell                            0xA3010D
#define ANIM_Chan_Poisoned_ToppledHurtAlt                       0xA3010E
#define ANIM_Chan_Poisoned_ToppledStill                         0xA3010F
#define ANIM_Chan_Poisoned_ToppledSleep                         0xA30110
#define ANIM_Chan_Poisoned_ToppledDizzy                         0xA30111
#define ANIM_Chan_Poisoned_Empty                                0xA30112
#define ANIM_Chan_Poisoned_EmptyStill                           0xA30113
#define ANIM_Chan_Poisoned_ToppledBurnHurt                      0xA30114
#define ANIM_Chan_Poisoned_ToppledBurnStill                     0xA30115

#define ANIM_Chan_Dizzy_Still                                   0xA30200
#define ANIM_Chan_Dizzy_Idle                                    0xA30201
#define ANIM_Chan_Dizzy_Toppled                                 0xA30202
#define ANIM_Chan_Dizzy_Walk                                    0xA30203
#define ANIM_Chan_Dizzy_Run                                     0xA30204
#define ANIM_Chan_Dizzy_ShellSpin                               0xA30205
#define ANIM_Chan_Dizzy_Hurt                                    0xA30206
#define ANIM_Chan_Dizzy_ToppledHurt                             0xA30207
#define ANIM_Chan_Dizzy_HurtAlt                                 0xA30208
#define ANIM_Chan_Dizzy_ShellStill                              0xA30209
#define ANIM_Chan_Dizzy_Sleep                                   0xA3020A
#define ANIM_Chan_Dizzy_Dizzy                                   0xA3020B
#define ANIM_Chan_Dizzy_EnterShell                              0xA3020C
#define ANIM_Chan_Dizzy_ExitShell                               0xA3020D
#define ANIM_Chan_Dizzy_ToppledHurtAlt                          0xA3020E
#define ANIM_Chan_Dizzy_ToppledStill                            0xA3020F
#define ANIM_Chan_Dizzy_ToppledSleep                            0xA30210
#define ANIM_Chan_Dizzy_ToppledDizzy                            0xA30211
#define ANIM_Chan_Dizzy_Empty                                   0xA30212
#define ANIM_Chan_Dizzy_EmptyStill                              0xA30213
#define ANIM_Chan_Dizzy_ToppledBurnHurt                         0xA30214
#define ANIM_Chan_Dizzy_ToppledBurnStill                        0xA30215

#define ANIM_Chan_Shocked_Still                                 0xA30300
#define ANIM_Chan_Shocked_Idle                                  0xA30301
#define ANIM_Chan_Shocked_Toppled                               0xA30302
#define ANIM_Chan_Shocked_Walk                                  0xA30303
#define ANIM_Chan_Shocked_Run                                   0xA30304
#define ANIM_Chan_Shocked_ShellSpin                             0xA30305
#define ANIM_Chan_Shocked_Hurt                                  0xA30306
#define ANIM_Chan_Shocked_ToppledHurt                           0xA30307
#define ANIM_Chan_Shocked_HurtAlt                               0xA30308
#define ANIM_Chan_Shocked_ShellStill                            0xA30309
#define ANIM_Chan_Shocked_Sleep                                 0xA3030A
#define ANIM_Chan_Shocked_Dizzy                                 0xA3030B
#define ANIM_Chan_Shocked_EnterShell                            0xA3030C
#define ANIM_Chan_Shocked_ExitShell                             0xA3030D
#define ANIM_Chan_Shocked_ToppledHurtAlt                        0xA3030E
#define ANIM_Chan_Shocked_ToppledStill                          0xA3030F
#define ANIM_Chan_Shocked_ToppledSleep                          0xA30310
#define ANIM_Chan_Shocked_ToppledDizzy                          0xA30311
#define ANIM_Chan_Shocked_Empty                                 0xA30312
#define ANIM_Chan_Shocked_EmptyStill                            0xA30313
#define ANIM_Chan_Shocked_ToppledBurnHurt                       0xA30314
#define ANIM_Chan_Shocked_ToppledBurnStill                      0xA30315

#define ANIM_Chan_Burnt_Still                                   0xA30400
#define ANIM_Chan_Burnt_Idle                                    0xA30401
#define ANIM_Chan_Burnt_Toppled                                 0xA30402
#define ANIM_Chan_Burnt_Walk                                    0xA30403
#define ANIM_Chan_Burnt_Run                                     0xA30404
#define ANIM_Chan_Burnt_ShellSpin                               0xA30405
#define ANIM_Chan_Burnt_Hurt                                    0xA30406
#define ANIM_Chan_Burnt_ToppledHurt                             0xA30407
#define ANIM_Chan_Burnt_HurtAlt                                 0xA30408
#define ANIM_Chan_Burnt_ShellStill                              0xA30409
#define ANIM_Chan_Burnt_Sleep                                   0xA3040A
#define ANIM_Chan_Burnt_Dizzy                                   0xA3040B
#define ANIM_Chan_Burnt_EnterShell                              0xA3040C
#define ANIM_Chan_Burnt_ExitShell                               0xA3040D
#define ANIM_Chan_Burnt_ToppledHurtAlt                          0xA3040E
#define ANIM_Chan_Burnt_ToppledStill                            0xA3040F
#define ANIM_Chan_Burnt_ToppledSleep                            0xA30410
#define ANIM_Chan_Burnt_ToppledDizzy                            0xA30411
#define ANIM_Chan_Burnt_Empty                                   0xA30412
#define ANIM_Chan_Burnt_EmptyStill                              0xA30413
#define ANIM_Chan_Burnt_ToppledBurnHurt                         0xA30414
#define ANIM_Chan_Burnt_ToppledBurnStill                        0xA30415

#endif
