// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_COIN_H_
#define _NPC_SPRITE_COIN_H_

#include "types.h"

#define SPR_Coin 0xD5

#define SPR_PAL_Coin 0x0
#define SPR_PAL_Coin_Unused1 0x1
#define SPR_PAL_Coin_Unused2 0x2
#define SPR_PAL_Coin_Unused3 0x3

#define ANIM_Coin_Rotate                                        0xD50000

#define ANIM_Coin_Unused1_Rotate                                0xD50100

#define ANIM_Coin_Unused2_Rotate                                0xD50200

#define ANIM_Coin_Unused3_Rotate                                0xD50300

#endif
