// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_CONDUCTORTOAD_H_
#define _NPC_SPRITE_CONDUCTORTOAD_H_

#include "types.h"

#define SPR_ConductorToad 0x8B

#define SPR_PAL_ConductorToad 0x0

#define ANIM_ConductorToad_Still                                0x8B0000
#define ANIM_ConductorToad_Idle                                 0x8B0001
#define ANIM_ConductorToad_Walk                                 0x8B0002
#define ANIM_ConductorToad_Run                                  0x8B0003
#define ANIM_ConductorToad_Talk                                 0x8B0004
#define ANIM_ConductorToad_BlowWhistle                          0x8B0005

#endif
