// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_DARKTOAD_H_
#define _NPC_SPRITE_DARKTOAD_H_

#include "types.h"

#define SPR_DarkToad 0x65

#define SPR_PAL_DarkToad_Black 0x0
#define SPR_PAL_DarkToad_Red 0x1
#define SPR_PAL_DarkToad_Yellow 0x2
#define SPR_PAL_DarkToad_Green 0x3

#define ANIM_DarkToad_Black_Still                               0x650000
#define ANIM_DarkToad_Black_Idle                                0x650001
#define ANIM_DarkToad_Black_Walk                                0x650002
#define ANIM_DarkToad_Black_Run                                 0x650003
#define ANIM_DarkToad_Black_Talk                                0x650004
#define ANIM_DarkToad_Black_Dismiss                             0x650005
#define ANIM_DarkToad_Black_Hurt                                0x650006

#define ANIM_DarkToad_Red_Still                                 0x650100
#define ANIM_DarkToad_Red_Idle                                  0x650101
#define ANIM_DarkToad_Red_Walk                                  0x650102
#define ANIM_DarkToad_Red_Run                                   0x650103
#define ANIM_DarkToad_Red_Talk                                  0x650104
#define ANIM_DarkToad_Red_Dismiss                               0x650105
#define ANIM_DarkToad_Red_Hurt                                  0x650106

#define ANIM_DarkToad_Yellow_Still                              0x650200
#define ANIM_DarkToad_Yellow_Idle                               0x650201
#define ANIM_DarkToad_Yellow_Walk                               0x650202
#define ANIM_DarkToad_Yellow_Run                                0x650203
#define ANIM_DarkToad_Yellow_Talk                               0x650204
#define ANIM_DarkToad_Yellow_Dismiss                            0x650205
#define ANIM_DarkToad_Yellow_Hurt                               0x650206

#define ANIM_DarkToad_Green_Still                               0x650300
#define ANIM_DarkToad_Green_Idle                                0x650301
#define ANIM_DarkToad_Green_Walk                                0x650302
#define ANIM_DarkToad_Green_Run                                 0x650303
#define ANIM_DarkToad_Green_Talk                                0x650304
#define ANIM_DarkToad_Green_Dismiss                             0x650305
#define ANIM_DarkToad_Green_Hurt                                0x650306

#endif
