// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_DAYZEE_H_
#define _NPC_SPRITE_DAYZEE_H_

#include "types.h"

#define SPR_Dayzee 0x48

#define SPR_PAL_Dayzee 0x0
#define SPR_PAL_Dayzee_Amazy 0x1
#define SPR_PAL_Dayzee_Poisoned 0x2
#define SPR_PAL_Dayzee_Amazy_Poisoned 0x3
#define SPR_PAL_Dayzee_Dizzy 0x4
#define SPR_PAL_Dayzee_Amazy_Dizzy 0x5
#define SPR_PAL_Dayzee_Shocked 0x6
#define SPR_PAL_Dayzee_Amazy_Shocked 0x7
#define SPR_PAL_Dayzee_Burnt 0x8

#define ANIM_Dayzee_Anim00                                      0x480000
#define ANIM_Dayzee_Anim01                                      0x480001
#define ANIM_Dayzee_Anim02                                      0x480002
#define ANIM_Dayzee_Anim03                                      0x480003
#define ANIM_Dayzee_Anim04                                      0x480004
#define ANIM_Dayzee_Anim05                                      0x480005
#define ANIM_Dayzee_Anim06                                      0x480006
#define ANIM_Dayzee_Anim07                                      0x480007
#define ANIM_Dayzee_Anim08                                      0x480008
#define ANIM_Dayzee_Anim09                                      0x480009
#define ANIM_Dayzee_Anim0A                                      0x48000A
#define ANIM_Dayzee_Anim0B                                      0x48000B
#define ANIM_Dayzee_Anim0C                                      0x48000C
#define ANIM_Dayzee_Anim0D                                      0x48000D
#define ANIM_Dayzee_Anim0E                                      0x48000E
#define ANIM_Dayzee_Anim0F                                      0x48000F

#define ANIM_Dayzee_Amazy_Anim00                                0x480100
#define ANIM_Dayzee_Amazy_Anim01                                0x480101
#define ANIM_Dayzee_Amazy_Anim02                                0x480102
#define ANIM_Dayzee_Amazy_Anim03                                0x480103
#define ANIM_Dayzee_Amazy_Anim04                                0x480104
#define ANIM_Dayzee_Amazy_Anim05                                0x480105
#define ANIM_Dayzee_Amazy_Anim06                                0x480106
#define ANIM_Dayzee_Amazy_Anim07                                0x480107
#define ANIM_Dayzee_Amazy_Anim08                                0x480108
#define ANIM_Dayzee_Amazy_Anim09                                0x480109
#define ANIM_Dayzee_Amazy_Anim0A                                0x48010A
#define ANIM_Dayzee_Amazy_Anim0B                                0x48010B
#define ANIM_Dayzee_Amazy_Anim0C                                0x48010C
#define ANIM_Dayzee_Amazy_Anim0D                                0x48010D
#define ANIM_Dayzee_Amazy_Anim0E                                0x48010E
#define ANIM_Dayzee_Amazy_Anim0F                                0x48010F

#define ANIM_Dayzee_Poisoned_Anim00                             0x480200
#define ANIM_Dayzee_Poisoned_Anim01                             0x480201
#define ANIM_Dayzee_Poisoned_Anim02                             0x480202
#define ANIM_Dayzee_Poisoned_Anim03                             0x480203
#define ANIM_Dayzee_Poisoned_Anim04                             0x480204
#define ANIM_Dayzee_Poisoned_Anim05                             0x480205
#define ANIM_Dayzee_Poisoned_Anim06                             0x480206
#define ANIM_Dayzee_Poisoned_Anim07                             0x480207
#define ANIM_Dayzee_Poisoned_Anim08                             0x480208
#define ANIM_Dayzee_Poisoned_Anim09                             0x480209
#define ANIM_Dayzee_Poisoned_Anim0A                             0x48020A
#define ANIM_Dayzee_Poisoned_Anim0B                             0x48020B
#define ANIM_Dayzee_Poisoned_Anim0C                             0x48020C
#define ANIM_Dayzee_Poisoned_Anim0D                             0x48020D
#define ANIM_Dayzee_Poisoned_Anim0E                             0x48020E
#define ANIM_Dayzee_Poisoned_Anim0F                             0x48020F

#define ANIM_Dayzee_Amazy_Poisoned_Anim00                       0x480300
#define ANIM_Dayzee_Amazy_Poisoned_Anim01                       0x480301
#define ANIM_Dayzee_Amazy_Poisoned_Anim02                       0x480302
#define ANIM_Dayzee_Amazy_Poisoned_Anim03                       0x480303
#define ANIM_Dayzee_Amazy_Poisoned_Anim04                       0x480304
#define ANIM_Dayzee_Amazy_Poisoned_Anim05                       0x480305
#define ANIM_Dayzee_Amazy_Poisoned_Anim06                       0x480306
#define ANIM_Dayzee_Amazy_Poisoned_Anim07                       0x480307
#define ANIM_Dayzee_Amazy_Poisoned_Anim08                       0x480308
#define ANIM_Dayzee_Amazy_Poisoned_Anim09                       0x480309
#define ANIM_Dayzee_Amazy_Poisoned_Anim0A                       0x48030A
#define ANIM_Dayzee_Amazy_Poisoned_Anim0B                       0x48030B
#define ANIM_Dayzee_Amazy_Poisoned_Anim0C                       0x48030C
#define ANIM_Dayzee_Amazy_Poisoned_Anim0D                       0x48030D
#define ANIM_Dayzee_Amazy_Poisoned_Anim0E                       0x48030E
#define ANIM_Dayzee_Amazy_Poisoned_Anim0F                       0x48030F

#define ANIM_Dayzee_Dizzy_Anim00                                0x480400
#define ANIM_Dayzee_Dizzy_Anim01                                0x480401
#define ANIM_Dayzee_Dizzy_Anim02                                0x480402
#define ANIM_Dayzee_Dizzy_Anim03                                0x480403
#define ANIM_Dayzee_Dizzy_Anim04                                0x480404
#define ANIM_Dayzee_Dizzy_Anim05                                0x480405
#define ANIM_Dayzee_Dizzy_Anim06                                0x480406
#define ANIM_Dayzee_Dizzy_Anim07                                0x480407
#define ANIM_Dayzee_Dizzy_Anim08                                0x480408
#define ANIM_Dayzee_Dizzy_Anim09                                0x480409
#define ANIM_Dayzee_Dizzy_Anim0A                                0x48040A
#define ANIM_Dayzee_Dizzy_Anim0B                                0x48040B
#define ANIM_Dayzee_Dizzy_Anim0C                                0x48040C
#define ANIM_Dayzee_Dizzy_Anim0D                                0x48040D
#define ANIM_Dayzee_Dizzy_Anim0E                                0x48040E
#define ANIM_Dayzee_Dizzy_Anim0F                                0x48040F

#define ANIM_Dayzee_Amazy_Dizzy_Anim00                          0x480500
#define ANIM_Dayzee_Amazy_Dizzy_Anim01                          0x480501
#define ANIM_Dayzee_Amazy_Dizzy_Anim02                          0x480502
#define ANIM_Dayzee_Amazy_Dizzy_Anim03                          0x480503
#define ANIM_Dayzee_Amazy_Dizzy_Anim04                          0x480504
#define ANIM_Dayzee_Amazy_Dizzy_Anim05                          0x480505
#define ANIM_Dayzee_Amazy_Dizzy_Anim06                          0x480506
#define ANIM_Dayzee_Amazy_Dizzy_Anim07                          0x480507
#define ANIM_Dayzee_Amazy_Dizzy_Anim08                          0x480508
#define ANIM_Dayzee_Amazy_Dizzy_Anim09                          0x480509
#define ANIM_Dayzee_Amazy_Dizzy_Anim0A                          0x48050A
#define ANIM_Dayzee_Amazy_Dizzy_Anim0B                          0x48050B
#define ANIM_Dayzee_Amazy_Dizzy_Anim0C                          0x48050C
#define ANIM_Dayzee_Amazy_Dizzy_Anim0D                          0x48050D
#define ANIM_Dayzee_Amazy_Dizzy_Anim0E                          0x48050E
#define ANIM_Dayzee_Amazy_Dizzy_Anim0F                          0x48050F

#define ANIM_Dayzee_Shocked_Anim00                              0x480600
#define ANIM_Dayzee_Shocked_Anim01                              0x480601
#define ANIM_Dayzee_Shocked_Anim02                              0x480602
#define ANIM_Dayzee_Shocked_Anim03                              0x480603
#define ANIM_Dayzee_Shocked_Anim04                              0x480604
#define ANIM_Dayzee_Shocked_Anim05                              0x480605
#define ANIM_Dayzee_Shocked_Anim06                              0x480606
#define ANIM_Dayzee_Shocked_Anim07                              0x480607
#define ANIM_Dayzee_Shocked_Anim08                              0x480608
#define ANIM_Dayzee_Shocked_Anim09                              0x480609
#define ANIM_Dayzee_Shocked_Anim0A                              0x48060A
#define ANIM_Dayzee_Shocked_Anim0B                              0x48060B
#define ANIM_Dayzee_Shocked_Anim0C                              0x48060C
#define ANIM_Dayzee_Shocked_Anim0D                              0x48060D
#define ANIM_Dayzee_Shocked_Anim0E                              0x48060E
#define ANIM_Dayzee_Shocked_Anim0F                              0x48060F

#define ANIM_Dayzee_Amazy_Shocked_Anim00                        0x480700
#define ANIM_Dayzee_Amazy_Shocked_Anim01                        0x480701
#define ANIM_Dayzee_Amazy_Shocked_Anim02                        0x480702
#define ANIM_Dayzee_Amazy_Shocked_Anim03                        0x480703
#define ANIM_Dayzee_Amazy_Shocked_Anim04                        0x480704
#define ANIM_Dayzee_Amazy_Shocked_Anim05                        0x480705
#define ANIM_Dayzee_Amazy_Shocked_Anim06                        0x480706
#define ANIM_Dayzee_Amazy_Shocked_Anim07                        0x480707
#define ANIM_Dayzee_Amazy_Shocked_Anim08                        0x480708
#define ANIM_Dayzee_Amazy_Shocked_Anim09                        0x480709
#define ANIM_Dayzee_Amazy_Shocked_Anim0A                        0x48070A
#define ANIM_Dayzee_Amazy_Shocked_Anim0B                        0x48070B
#define ANIM_Dayzee_Amazy_Shocked_Anim0C                        0x48070C
#define ANIM_Dayzee_Amazy_Shocked_Anim0D                        0x48070D
#define ANIM_Dayzee_Amazy_Shocked_Anim0E                        0x48070E
#define ANIM_Dayzee_Amazy_Shocked_Anim0F                        0x48070F

#define ANIM_Dayzee_Burnt_Anim00                                0x480800
#define ANIM_Dayzee_Burnt_Anim01                                0x480801
#define ANIM_Dayzee_Burnt_Anim02                                0x480802
#define ANIM_Dayzee_Burnt_Anim03                                0x480803
#define ANIM_Dayzee_Burnt_Anim04                                0x480804
#define ANIM_Dayzee_Burnt_Anim05                                0x480805
#define ANIM_Dayzee_Burnt_Anim06                                0x480806
#define ANIM_Dayzee_Burnt_Anim07                                0x480807
#define ANIM_Dayzee_Burnt_Anim08                                0x480808
#define ANIM_Dayzee_Burnt_Anim09                                0x480809
#define ANIM_Dayzee_Burnt_Anim0A                                0x48080A
#define ANIM_Dayzee_Burnt_Anim0B                                0x48080B
#define ANIM_Dayzee_Burnt_Anim0C                                0x48080C
#define ANIM_Dayzee_Burnt_Anim0D                                0x48080D
#define ANIM_Dayzee_Burnt_Anim0E                                0x48080E
#define ANIM_Dayzee_Burnt_Anim0F                                0x48080F

#endif
