// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_FLYINGMAGIKOOPA_H_
#define _NPC_SPRITE_FLYINGMAGIKOOPA_H_

#include "types.h"

#define SPR_FlyingMagikoopa 0x57

#define SPR_PAL_FlyingMagikoopa 0x0
#define SPR_PAL_FlyingMagikoopa_Red 0x1
#define SPR_PAL_FlyingMagikoopa_Yellow 0x2
#define SPR_PAL_FlyingMagikoopa_White 0x3
#define SPR_PAL_FlyingMagikoopa_Green 0x4
#define SPR_PAL_FlyingMagikoopa_Gray 0x5
#define SPR_PAL_FlyingMagikoopa_Poisoned 0x6
#define SPR_PAL_FlyingMagikoopa_Red_Poisoned 0x7
#define SPR_PAL_FlyingMagikoopa_Yellow_Poisoned 0x8
#define SPR_PAL_FlyingMagikoopa_White_Poisoned 0x9
#define SPR_PAL_FlyingMagikoopa_Green_Poisoned 0xA
#define SPR_PAL_FlyingMagikoopa_Gray_Poisoned 0xB
#define SPR_PAL_FlyingMagikoopa_Dizzy 0xC
#define SPR_PAL_FlyingMagikoopa_Red_Dizzy 0xD
#define SPR_PAL_FlyingMagikoopa_Yellow_Dizzy 0xE
#define SPR_PAL_FlyingMagikoopa_White_Dizzy 0xF
#define SPR_PAL_FlyingMagikoopa_Green_Dizzy 0x10
#define SPR_PAL_FlyingMagikoopa_Gray_Dizzy 0x11
#define SPR_PAL_FlyingMagikoopa_Shocked 0x12
#define SPR_PAL_FlyingMagikoopa_Red_Shocked 0x13
#define SPR_PAL_FlyingMagikoopa_Yellow_Shocked 0x14
#define SPR_PAL_FlyingMagikoopa_White_Shocked 0x15
#define SPR_PAL_FlyingMagikoopa_Green_Shocked 0x16
#define SPR_PAL_FlyingMagikoopa_Gray_Shocked 0x17
#define SPR_PAL_FlyingMagikoopa_Burnt 0x18

#define ANIM_FlyingMagikoopa_Anim00                             0x570000
#define ANIM_FlyingMagikoopa_Anim01                             0x570001
#define ANIM_FlyingMagikoopa_Anim02                             0x570002
#define ANIM_FlyingMagikoopa_Anim03                             0x570003
#define ANIM_FlyingMagikoopa_Anim04                             0x570004
#define ANIM_FlyingMagikoopa_Anim05                             0x570005
#define ANIM_FlyingMagikoopa_Anim06                             0x570006
#define ANIM_FlyingMagikoopa_Anim07                             0x570007
#define ANIM_FlyingMagikoopa_Anim08                             0x570008
#define ANIM_FlyingMagikoopa_Anim09                             0x570009
#define ANIM_FlyingMagikoopa_Anim0A                             0x57000A

#define ANIM_FlyingMagikoopa_Red_Anim00                         0x570100
#define ANIM_FlyingMagikoopa_Red_Anim01                         0x570101
#define ANIM_FlyingMagikoopa_Red_Anim02                         0x570102
#define ANIM_FlyingMagikoopa_Red_Anim03                         0x570103
#define ANIM_FlyingMagikoopa_Red_Anim04                         0x570104
#define ANIM_FlyingMagikoopa_Red_Anim05                         0x570105
#define ANIM_FlyingMagikoopa_Red_Anim06                         0x570106
#define ANIM_FlyingMagikoopa_Red_Anim07                         0x570107
#define ANIM_FlyingMagikoopa_Red_Anim08                         0x570108
#define ANIM_FlyingMagikoopa_Red_Anim09                         0x570109
#define ANIM_FlyingMagikoopa_Red_Anim0A                         0x57010A

#define ANIM_FlyingMagikoopa_Yellow_Anim00                      0x570200
#define ANIM_FlyingMagikoopa_Yellow_Anim01                      0x570201
#define ANIM_FlyingMagikoopa_Yellow_Anim02                      0x570202
#define ANIM_FlyingMagikoopa_Yellow_Anim03                      0x570203
#define ANIM_FlyingMagikoopa_Yellow_Anim04                      0x570204
#define ANIM_FlyingMagikoopa_Yellow_Anim05                      0x570205
#define ANIM_FlyingMagikoopa_Yellow_Anim06                      0x570206
#define ANIM_FlyingMagikoopa_Yellow_Anim07                      0x570207
#define ANIM_FlyingMagikoopa_Yellow_Anim08                      0x570208
#define ANIM_FlyingMagikoopa_Yellow_Anim09                      0x570209
#define ANIM_FlyingMagikoopa_Yellow_Anim0A                      0x57020A

#define ANIM_FlyingMagikoopa_White_Anim00                       0x570300
#define ANIM_FlyingMagikoopa_White_Anim01                       0x570301
#define ANIM_FlyingMagikoopa_White_Anim02                       0x570302
#define ANIM_FlyingMagikoopa_White_Anim03                       0x570303
#define ANIM_FlyingMagikoopa_White_Anim04                       0x570304
#define ANIM_FlyingMagikoopa_White_Anim05                       0x570305
#define ANIM_FlyingMagikoopa_White_Anim06                       0x570306
#define ANIM_FlyingMagikoopa_White_Anim07                       0x570307
#define ANIM_FlyingMagikoopa_White_Anim08                       0x570308
#define ANIM_FlyingMagikoopa_White_Anim09                       0x570309
#define ANIM_FlyingMagikoopa_White_Anim0A                       0x57030A

#define ANIM_FlyingMagikoopa_Green_Anim00                       0x570400
#define ANIM_FlyingMagikoopa_Green_Anim01                       0x570401
#define ANIM_FlyingMagikoopa_Green_Anim02                       0x570402
#define ANIM_FlyingMagikoopa_Green_Anim03                       0x570403
#define ANIM_FlyingMagikoopa_Green_Anim04                       0x570404
#define ANIM_FlyingMagikoopa_Green_Anim05                       0x570405
#define ANIM_FlyingMagikoopa_Green_Anim06                       0x570406
#define ANIM_FlyingMagikoopa_Green_Anim07                       0x570407
#define ANIM_FlyingMagikoopa_Green_Anim08                       0x570408
#define ANIM_FlyingMagikoopa_Green_Anim09                       0x570409
#define ANIM_FlyingMagikoopa_Green_Anim0A                       0x57040A

#define ANIM_FlyingMagikoopa_Gray_Anim00                        0x570500
#define ANIM_FlyingMagikoopa_Gray_Anim01                        0x570501
#define ANIM_FlyingMagikoopa_Gray_Anim02                        0x570502
#define ANIM_FlyingMagikoopa_Gray_Anim03                        0x570503
#define ANIM_FlyingMagikoopa_Gray_Anim04                        0x570504
#define ANIM_FlyingMagikoopa_Gray_Anim05                        0x570505
#define ANIM_FlyingMagikoopa_Gray_Anim06                        0x570506
#define ANIM_FlyingMagikoopa_Gray_Anim07                        0x570507
#define ANIM_FlyingMagikoopa_Gray_Anim08                        0x570508
#define ANIM_FlyingMagikoopa_Gray_Anim09                        0x570509
#define ANIM_FlyingMagikoopa_Gray_Anim0A                        0x57050A

#define ANIM_FlyingMagikoopa_Poisoned_Anim00                    0x570600
#define ANIM_FlyingMagikoopa_Poisoned_Anim01                    0x570601
#define ANIM_FlyingMagikoopa_Poisoned_Anim02                    0x570602
#define ANIM_FlyingMagikoopa_Poisoned_Anim03                    0x570603
#define ANIM_FlyingMagikoopa_Poisoned_Anim04                    0x570604
#define ANIM_FlyingMagikoopa_Poisoned_Anim05                    0x570605
#define ANIM_FlyingMagikoopa_Poisoned_Anim06                    0x570606
#define ANIM_FlyingMagikoopa_Poisoned_Anim07                    0x570607
#define ANIM_FlyingMagikoopa_Poisoned_Anim08                    0x570608
#define ANIM_FlyingMagikoopa_Poisoned_Anim09                    0x570609
#define ANIM_FlyingMagikoopa_Poisoned_Anim0A                    0x57060A

#define ANIM_FlyingMagikoopa_Red_Poisoned_Anim00                0x570700
#define ANIM_FlyingMagikoopa_Red_Poisoned_Anim01                0x570701
#define ANIM_FlyingMagikoopa_Red_Poisoned_Anim02                0x570702
#define ANIM_FlyingMagikoopa_Red_Poisoned_Anim03                0x570703
#define ANIM_FlyingMagikoopa_Red_Poisoned_Anim04                0x570704
#define ANIM_FlyingMagikoopa_Red_Poisoned_Anim05                0x570705
#define ANIM_FlyingMagikoopa_Red_Poisoned_Anim06                0x570706
#define ANIM_FlyingMagikoopa_Red_Poisoned_Anim07                0x570707
#define ANIM_FlyingMagikoopa_Red_Poisoned_Anim08                0x570708
#define ANIM_FlyingMagikoopa_Red_Poisoned_Anim09                0x570709
#define ANIM_FlyingMagikoopa_Red_Poisoned_Anim0A                0x57070A

#define ANIM_FlyingMagikoopa_Yellow_Poisoned_Anim00             0x570800
#define ANIM_FlyingMagikoopa_Yellow_Poisoned_Anim01             0x570801
#define ANIM_FlyingMagikoopa_Yellow_Poisoned_Anim02             0x570802
#define ANIM_FlyingMagikoopa_Yellow_Poisoned_Anim03             0x570803
#define ANIM_FlyingMagikoopa_Yellow_Poisoned_Anim04             0x570804
#define ANIM_FlyingMagikoopa_Yellow_Poisoned_Anim05             0x570805
#define ANIM_FlyingMagikoopa_Yellow_Poisoned_Anim06             0x570806
#define ANIM_FlyingMagikoopa_Yellow_Poisoned_Anim07             0x570807
#define ANIM_FlyingMagikoopa_Yellow_Poisoned_Anim08             0x570808
#define ANIM_FlyingMagikoopa_Yellow_Poisoned_Anim09             0x570809
#define ANIM_FlyingMagikoopa_Yellow_Poisoned_Anim0A             0x57080A

#define ANIM_FlyingMagikoopa_White_Poisoned_Anim00              0x570900
#define ANIM_FlyingMagikoopa_White_Poisoned_Anim01              0x570901
#define ANIM_FlyingMagikoopa_White_Poisoned_Anim02              0x570902
#define ANIM_FlyingMagikoopa_White_Poisoned_Anim03              0x570903
#define ANIM_FlyingMagikoopa_White_Poisoned_Anim04              0x570904
#define ANIM_FlyingMagikoopa_White_Poisoned_Anim05              0x570905
#define ANIM_FlyingMagikoopa_White_Poisoned_Anim06              0x570906
#define ANIM_FlyingMagikoopa_White_Poisoned_Anim07              0x570907
#define ANIM_FlyingMagikoopa_White_Poisoned_Anim08              0x570908
#define ANIM_FlyingMagikoopa_White_Poisoned_Anim09              0x570909
#define ANIM_FlyingMagikoopa_White_Poisoned_Anim0A              0x57090A

#define ANIM_FlyingMagikoopa_Green_Poisoned_Anim00              0x570A00
#define ANIM_FlyingMagikoopa_Green_Poisoned_Anim01              0x570A01
#define ANIM_FlyingMagikoopa_Green_Poisoned_Anim02              0x570A02
#define ANIM_FlyingMagikoopa_Green_Poisoned_Anim03              0x570A03
#define ANIM_FlyingMagikoopa_Green_Poisoned_Anim04              0x570A04
#define ANIM_FlyingMagikoopa_Green_Poisoned_Anim05              0x570A05
#define ANIM_FlyingMagikoopa_Green_Poisoned_Anim06              0x570A06
#define ANIM_FlyingMagikoopa_Green_Poisoned_Anim07              0x570A07
#define ANIM_FlyingMagikoopa_Green_Poisoned_Anim08              0x570A08
#define ANIM_FlyingMagikoopa_Green_Poisoned_Anim09              0x570A09
#define ANIM_FlyingMagikoopa_Green_Poisoned_Anim0A              0x570A0A

#define ANIM_FlyingMagikoopa_Gray_Poisoned_Anim00               0x570B00
#define ANIM_FlyingMagikoopa_Gray_Poisoned_Anim01               0x570B01
#define ANIM_FlyingMagikoopa_Gray_Poisoned_Anim02               0x570B02
#define ANIM_FlyingMagikoopa_Gray_Poisoned_Anim03               0x570B03
#define ANIM_FlyingMagikoopa_Gray_Poisoned_Anim04               0x570B04
#define ANIM_FlyingMagikoopa_Gray_Poisoned_Anim05               0x570B05
#define ANIM_FlyingMagikoopa_Gray_Poisoned_Anim06               0x570B06
#define ANIM_FlyingMagikoopa_Gray_Poisoned_Anim07               0x570B07
#define ANIM_FlyingMagikoopa_Gray_Poisoned_Anim08               0x570B08
#define ANIM_FlyingMagikoopa_Gray_Poisoned_Anim09               0x570B09
#define ANIM_FlyingMagikoopa_Gray_Poisoned_Anim0A               0x570B0A

#define ANIM_FlyingMagikoopa_Dizzy_Anim00                       0x570C00
#define ANIM_FlyingMagikoopa_Dizzy_Anim01                       0x570C01
#define ANIM_FlyingMagikoopa_Dizzy_Anim02                       0x570C02
#define ANIM_FlyingMagikoopa_Dizzy_Anim03                       0x570C03
#define ANIM_FlyingMagikoopa_Dizzy_Anim04                       0x570C04
#define ANIM_FlyingMagikoopa_Dizzy_Anim05                       0x570C05
#define ANIM_FlyingMagikoopa_Dizzy_Anim06                       0x570C06
#define ANIM_FlyingMagikoopa_Dizzy_Anim07                       0x570C07
#define ANIM_FlyingMagikoopa_Dizzy_Anim08                       0x570C08
#define ANIM_FlyingMagikoopa_Dizzy_Anim09                       0x570C09
#define ANIM_FlyingMagikoopa_Dizzy_Anim0A                       0x570C0A

#define ANIM_FlyingMagikoopa_Red_Dizzy_Anim00                   0x570D00
#define ANIM_FlyingMagikoopa_Red_Dizzy_Anim01                   0x570D01
#define ANIM_FlyingMagikoopa_Red_Dizzy_Anim02                   0x570D02
#define ANIM_FlyingMagikoopa_Red_Dizzy_Anim03                   0x570D03
#define ANIM_FlyingMagikoopa_Red_Dizzy_Anim04                   0x570D04
#define ANIM_FlyingMagikoopa_Red_Dizzy_Anim05                   0x570D05
#define ANIM_FlyingMagikoopa_Red_Dizzy_Anim06                   0x570D06
#define ANIM_FlyingMagikoopa_Red_Dizzy_Anim07                   0x570D07
#define ANIM_FlyingMagikoopa_Red_Dizzy_Anim08                   0x570D08
#define ANIM_FlyingMagikoopa_Red_Dizzy_Anim09                   0x570D09
#define ANIM_FlyingMagikoopa_Red_Dizzy_Anim0A                   0x570D0A

#define ANIM_FlyingMagikoopa_Yellow_Dizzy_Anim00                0x570E00
#define ANIM_FlyingMagikoopa_Yellow_Dizzy_Anim01                0x570E01
#define ANIM_FlyingMagikoopa_Yellow_Dizzy_Anim02                0x570E02
#define ANIM_FlyingMagikoopa_Yellow_Dizzy_Anim03                0x570E03
#define ANIM_FlyingMagikoopa_Yellow_Dizzy_Anim04                0x570E04
#define ANIM_FlyingMagikoopa_Yellow_Dizzy_Anim05                0x570E05
#define ANIM_FlyingMagikoopa_Yellow_Dizzy_Anim06                0x570E06
#define ANIM_FlyingMagikoopa_Yellow_Dizzy_Anim07                0x570E07
#define ANIM_FlyingMagikoopa_Yellow_Dizzy_Anim08                0x570E08
#define ANIM_FlyingMagikoopa_Yellow_Dizzy_Anim09                0x570E09
#define ANIM_FlyingMagikoopa_Yellow_Dizzy_Anim0A                0x570E0A

#define ANIM_FlyingMagikoopa_White_Dizzy_Anim00                 0x570F00
#define ANIM_FlyingMagikoopa_White_Dizzy_Anim01                 0x570F01
#define ANIM_FlyingMagikoopa_White_Dizzy_Anim02                 0x570F02
#define ANIM_FlyingMagikoopa_White_Dizzy_Anim03                 0x570F03
#define ANIM_FlyingMagikoopa_White_Dizzy_Anim04                 0x570F04
#define ANIM_FlyingMagikoopa_White_Dizzy_Anim05                 0x570F05
#define ANIM_FlyingMagikoopa_White_Dizzy_Anim06                 0x570F06
#define ANIM_FlyingMagikoopa_White_Dizzy_Anim07                 0x570F07
#define ANIM_FlyingMagikoopa_White_Dizzy_Anim08                 0x570F08
#define ANIM_FlyingMagikoopa_White_Dizzy_Anim09                 0x570F09
#define ANIM_FlyingMagikoopa_White_Dizzy_Anim0A                 0x570F0A

#define ANIM_FlyingMagikoopa_Green_Dizzy_Anim00                 0x571000
#define ANIM_FlyingMagikoopa_Green_Dizzy_Anim01                 0x571001
#define ANIM_FlyingMagikoopa_Green_Dizzy_Anim02                 0x571002
#define ANIM_FlyingMagikoopa_Green_Dizzy_Anim03                 0x571003
#define ANIM_FlyingMagikoopa_Green_Dizzy_Anim04                 0x571004
#define ANIM_FlyingMagikoopa_Green_Dizzy_Anim05                 0x571005
#define ANIM_FlyingMagikoopa_Green_Dizzy_Anim06                 0x571006
#define ANIM_FlyingMagikoopa_Green_Dizzy_Anim07                 0x571007
#define ANIM_FlyingMagikoopa_Green_Dizzy_Anim08                 0x571008
#define ANIM_FlyingMagikoopa_Green_Dizzy_Anim09                 0x571009
#define ANIM_FlyingMagikoopa_Green_Dizzy_Anim0A                 0x57100A

#define ANIM_FlyingMagikoopa_Gray_Dizzy_Anim00                  0x571100
#define ANIM_FlyingMagikoopa_Gray_Dizzy_Anim01                  0x571101
#define ANIM_FlyingMagikoopa_Gray_Dizzy_Anim02                  0x571102
#define ANIM_FlyingMagikoopa_Gray_Dizzy_Anim03                  0x571103
#define ANIM_FlyingMagikoopa_Gray_Dizzy_Anim04                  0x571104
#define ANIM_FlyingMagikoopa_Gray_Dizzy_Anim05                  0x571105
#define ANIM_FlyingMagikoopa_Gray_Dizzy_Anim06                  0x571106
#define ANIM_FlyingMagikoopa_Gray_Dizzy_Anim07                  0x571107
#define ANIM_FlyingMagikoopa_Gray_Dizzy_Anim08                  0x571108
#define ANIM_FlyingMagikoopa_Gray_Dizzy_Anim09                  0x571109
#define ANIM_FlyingMagikoopa_Gray_Dizzy_Anim0A                  0x57110A

#define ANIM_FlyingMagikoopa_Shocked_Anim00                     0x571200
#define ANIM_FlyingMagikoopa_Shocked_Anim01                     0x571201
#define ANIM_FlyingMagikoopa_Shocked_Anim02                     0x571202
#define ANIM_FlyingMagikoopa_Shocked_Anim03                     0x571203
#define ANIM_FlyingMagikoopa_Shocked_Anim04                     0x571204
#define ANIM_FlyingMagikoopa_Shocked_Anim05                     0x571205
#define ANIM_FlyingMagikoopa_Shocked_Anim06                     0x571206
#define ANIM_FlyingMagikoopa_Shocked_Anim07                     0x571207
#define ANIM_FlyingMagikoopa_Shocked_Anim08                     0x571208
#define ANIM_FlyingMagikoopa_Shocked_Anim09                     0x571209
#define ANIM_FlyingMagikoopa_Shocked_Anim0A                     0x57120A

#define ANIM_FlyingMagikoopa_Red_Shocked_Anim00                 0x571300
#define ANIM_FlyingMagikoopa_Red_Shocked_Anim01                 0x571301
#define ANIM_FlyingMagikoopa_Red_Shocked_Anim02                 0x571302
#define ANIM_FlyingMagikoopa_Red_Shocked_Anim03                 0x571303
#define ANIM_FlyingMagikoopa_Red_Shocked_Anim04                 0x571304
#define ANIM_FlyingMagikoopa_Red_Shocked_Anim05                 0x571305
#define ANIM_FlyingMagikoopa_Red_Shocked_Anim06                 0x571306
#define ANIM_FlyingMagikoopa_Red_Shocked_Anim07                 0x571307
#define ANIM_FlyingMagikoopa_Red_Shocked_Anim08                 0x571308
#define ANIM_FlyingMagikoopa_Red_Shocked_Anim09                 0x571309
#define ANIM_FlyingMagikoopa_Red_Shocked_Anim0A                 0x57130A

#define ANIM_FlyingMagikoopa_Yellow_Shocked_Anim00              0x571400
#define ANIM_FlyingMagikoopa_Yellow_Shocked_Anim01              0x571401
#define ANIM_FlyingMagikoopa_Yellow_Shocked_Anim02              0x571402
#define ANIM_FlyingMagikoopa_Yellow_Shocked_Anim03              0x571403
#define ANIM_FlyingMagikoopa_Yellow_Shocked_Anim04              0x571404
#define ANIM_FlyingMagikoopa_Yellow_Shocked_Anim05              0x571405
#define ANIM_FlyingMagikoopa_Yellow_Shocked_Anim06              0x571406
#define ANIM_FlyingMagikoopa_Yellow_Shocked_Anim07              0x571407
#define ANIM_FlyingMagikoopa_Yellow_Shocked_Anim08              0x571408
#define ANIM_FlyingMagikoopa_Yellow_Shocked_Anim09              0x571409
#define ANIM_FlyingMagikoopa_Yellow_Shocked_Anim0A              0x57140A

#define ANIM_FlyingMagikoopa_White_Shocked_Anim00               0x571500
#define ANIM_FlyingMagikoopa_White_Shocked_Anim01               0x571501
#define ANIM_FlyingMagikoopa_White_Shocked_Anim02               0x571502
#define ANIM_FlyingMagikoopa_White_Shocked_Anim03               0x571503
#define ANIM_FlyingMagikoopa_White_Shocked_Anim04               0x571504
#define ANIM_FlyingMagikoopa_White_Shocked_Anim05               0x571505
#define ANIM_FlyingMagikoopa_White_Shocked_Anim06               0x571506
#define ANIM_FlyingMagikoopa_White_Shocked_Anim07               0x571507
#define ANIM_FlyingMagikoopa_White_Shocked_Anim08               0x571508
#define ANIM_FlyingMagikoopa_White_Shocked_Anim09               0x571509
#define ANIM_FlyingMagikoopa_White_Shocked_Anim0A               0x57150A

#define ANIM_FlyingMagikoopa_Green_Shocked_Anim00               0x571600
#define ANIM_FlyingMagikoopa_Green_Shocked_Anim01               0x571601
#define ANIM_FlyingMagikoopa_Green_Shocked_Anim02               0x571602
#define ANIM_FlyingMagikoopa_Green_Shocked_Anim03               0x571603
#define ANIM_FlyingMagikoopa_Green_Shocked_Anim04               0x571604
#define ANIM_FlyingMagikoopa_Green_Shocked_Anim05               0x571605
#define ANIM_FlyingMagikoopa_Green_Shocked_Anim06               0x571606
#define ANIM_FlyingMagikoopa_Green_Shocked_Anim07               0x571607
#define ANIM_FlyingMagikoopa_Green_Shocked_Anim08               0x571608
#define ANIM_FlyingMagikoopa_Green_Shocked_Anim09               0x571609
#define ANIM_FlyingMagikoopa_Green_Shocked_Anim0A               0x57160A

#define ANIM_FlyingMagikoopa_Gray_Shocked_Anim00                0x571700
#define ANIM_FlyingMagikoopa_Gray_Shocked_Anim01                0x571701
#define ANIM_FlyingMagikoopa_Gray_Shocked_Anim02                0x571702
#define ANIM_FlyingMagikoopa_Gray_Shocked_Anim03                0x571703
#define ANIM_FlyingMagikoopa_Gray_Shocked_Anim04                0x571704
#define ANIM_FlyingMagikoopa_Gray_Shocked_Anim05                0x571705
#define ANIM_FlyingMagikoopa_Gray_Shocked_Anim06                0x571706
#define ANIM_FlyingMagikoopa_Gray_Shocked_Anim07                0x571707
#define ANIM_FlyingMagikoopa_Gray_Shocked_Anim08                0x571708
#define ANIM_FlyingMagikoopa_Gray_Shocked_Anim09                0x571709
#define ANIM_FlyingMagikoopa_Gray_Shocked_Anim0A                0x57170A

#define ANIM_FlyingMagikoopa_Burnt_Anim00                       0x571800
#define ANIM_FlyingMagikoopa_Burnt_Anim01                       0x571801
#define ANIM_FlyingMagikoopa_Burnt_Anim02                       0x571802
#define ANIM_FlyingMagikoopa_Burnt_Anim03                       0x571803
#define ANIM_FlyingMagikoopa_Burnt_Anim04                       0x571804
#define ANIM_FlyingMagikoopa_Burnt_Anim05                       0x571805
#define ANIM_FlyingMagikoopa_Burnt_Anim06                       0x571806
#define ANIM_FlyingMagikoopa_Burnt_Anim07                       0x571807
#define ANIM_FlyingMagikoopa_Burnt_Anim08                       0x571808
#define ANIM_FlyingMagikoopa_Burnt_Anim09                       0x571809
#define ANIM_FlyingMagikoopa_Burnt_Anim0A                       0x57180A

#endif
