// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_GENERALGUYBOMB_H_
#define _NPC_SPRITE_GENERALGUYBOMB_H_

#include "types.h"

#define SPR_GeneralGuyBomb 0x77

#define SPR_PAL_GeneralGuyBomb 0x0
#define SPR_PAL_GeneralGuyBomb_Gray 0x1
#define SPR_PAL_GeneralGuyBomb_Fuse 0x2

#define ANIM_GeneralGuyBomb_Anim00                              0x770000
#define ANIM_GeneralGuyBomb_Anim01                              0x770001
#define ANIM_GeneralGuyBomb_Anim02                              0x770002

#define ANIM_GeneralGuyBomb_Gray_Anim00                         0x770100
#define ANIM_GeneralGuyBomb_Gray_Anim01                         0x770101
#define ANIM_GeneralGuyBomb_Gray_Anim02                         0x770102

#define ANIM_GeneralGuyBomb_Fuse_Anim00                         0x770200
#define ANIM_GeneralGuyBomb_Fuse_Anim01                         0x770201
#define ANIM_GeneralGuyBomb_Fuse_Anim02                         0x770202

#endif
