// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_GOOMBABROS_H_
#define _NPC_SPRITE_GOOMBABROS_H_

#include "types.h"

#define SPR_GoombaBros 0x62

#define SPR_PAL_GoombaBros_Red 0x0
#define SPR_PAL_GoombaBros_Blue 0x1
#define SPR_PAL_GoombaBros_Red_Poisoned 0x2
#define SPR_PAL_GoombaBros_Blue_Poisoned 0x3
#define SPR_PAL_GoombaBros_Red_Dizzy 0x4
#define SPR_PAL_GoombaBros_Blue_Dizzy 0x5
#define SPR_PAL_GoombaBros_Red_Shocked 0x6
#define SPR_PAL_GoombaBros_Blue_Shocked 0x7
#define SPR_PAL_GoombaBros_Burnt 0x8

#define ANIM_GoombaBros_Red_Still                               0x620000
#define ANIM_GoombaBros_Red_CryStill                            0x620001
#define ANIM_GoombaBros_Red_Idle                                0x620002
#define ANIM_GoombaBros_Red_CryIdle                             0x620003
#define ANIM_GoombaBros_Red_Walk                                0x620004
#define ANIM_GoombaBros_Red_CryWalk                             0x620005
#define ANIM_GoombaBros_Red_Run                                 0x620006
#define ANIM_GoombaBros_Red_CryRun                              0x620007
#define ANIM_GoombaBros_Red_Midair                              0x620008
#define ANIM_GoombaBros_Red_Hurt                                0x620009
#define ANIM_GoombaBros_Red_Talk                                0x62000A
#define ANIM_GoombaBros_Red_CryTalk                             0x62000B
#define ANIM_GoombaBros_Red_Dizzy                               0x62000C
#define ANIM_GoombaBros_Red_Sleep                               0x62000D
#define ANIM_GoombaBros_Red_BurnHurt                            0x62000E
#define ANIM_GoombaBros_Red_BurnStill                           0x62000F

#define ANIM_GoombaBros_Blue_Still                              0x620100
#define ANIM_GoombaBros_Blue_CryStill                           0x620101
#define ANIM_GoombaBros_Blue_Idle                               0x620102
#define ANIM_GoombaBros_Blue_CryIdle                            0x620103
#define ANIM_GoombaBros_Blue_Walk                               0x620104
#define ANIM_GoombaBros_Blue_CryWalk                            0x620105
#define ANIM_GoombaBros_Blue_Run                                0x620106
#define ANIM_GoombaBros_Blue_CryRun                             0x620107
#define ANIM_GoombaBros_Blue_Midair                             0x620108
#define ANIM_GoombaBros_Blue_Hurt                               0x620109
#define ANIM_GoombaBros_Blue_Talk                               0x62010A
#define ANIM_GoombaBros_Blue_CryTalk                            0x62010B
#define ANIM_GoombaBros_Blue_Dizzy                              0x62010C
#define ANIM_GoombaBros_Blue_Sleep                              0x62010D
#define ANIM_GoombaBros_Blue_BurnHurt                           0x62010E
#define ANIM_GoombaBros_Blue_BurnStill                          0x62010F

#define ANIM_GoombaBros_Red_Poisoned_Still                      0x620200
#define ANIM_GoombaBros_Red_Poisoned_CryStill                   0x620201
#define ANIM_GoombaBros_Red_Poisoned_Idle                       0x620202
#define ANIM_GoombaBros_Red_Poisoned_CryIdle                    0x620203
#define ANIM_GoombaBros_Red_Poisoned_Walk                       0x620204
#define ANIM_GoombaBros_Red_Poisoned_CryWalk                    0x620205
#define ANIM_GoombaBros_Red_Poisoned_Run                        0x620206
#define ANIM_GoombaBros_Red_Poisoned_CryRun                     0x620207
#define ANIM_GoombaBros_Red_Poisoned_Midair                     0x620208
#define ANIM_GoombaBros_Red_Poisoned_Hurt                       0x620209
#define ANIM_GoombaBros_Red_Poisoned_Talk                       0x62020A
#define ANIM_GoombaBros_Red_Poisoned_CryTalk                    0x62020B
#define ANIM_GoombaBros_Red_Poisoned_Dizzy                      0x62020C
#define ANIM_GoombaBros_Red_Poisoned_Sleep                      0x62020D
#define ANIM_GoombaBros_Red_Poisoned_BurnHurt                   0x62020E
#define ANIM_GoombaBros_Red_Poisoned_BurnStill                  0x62020F

#define ANIM_GoombaBros_Blue_Poisoned_Still                     0x620300
#define ANIM_GoombaBros_Blue_Poisoned_CryStill                  0x620301
#define ANIM_GoombaBros_Blue_Poisoned_Idle                      0x620302
#define ANIM_GoombaBros_Blue_Poisoned_CryIdle                   0x620303
#define ANIM_GoombaBros_Blue_Poisoned_Walk                      0x620304
#define ANIM_GoombaBros_Blue_Poisoned_CryWalk                   0x620305
#define ANIM_GoombaBros_Blue_Poisoned_Run                       0x620306
#define ANIM_GoombaBros_Blue_Poisoned_CryRun                    0x620307
#define ANIM_GoombaBros_Blue_Poisoned_Midair                    0x620308
#define ANIM_GoombaBros_Blue_Poisoned_Hurt                      0x620309
#define ANIM_GoombaBros_Blue_Poisoned_Talk                      0x62030A
#define ANIM_GoombaBros_Blue_Poisoned_CryTalk                   0x62030B
#define ANIM_GoombaBros_Blue_Poisoned_Dizzy                     0x62030C
#define ANIM_GoombaBros_Blue_Poisoned_Sleep                     0x62030D
#define ANIM_GoombaBros_Blue_Poisoned_BurnHurt                  0x62030E
#define ANIM_GoombaBros_Blue_Poisoned_BurnStill                 0x62030F

#define ANIM_GoombaBros_Red_Dizzy_Still                         0x620400
#define ANIM_GoombaBros_Red_Dizzy_CryStill                      0x620401
#define ANIM_GoombaBros_Red_Dizzy_Idle                          0x620402
#define ANIM_GoombaBros_Red_Dizzy_CryIdle                       0x620403
#define ANIM_GoombaBros_Red_Dizzy_Walk                          0x620404
#define ANIM_GoombaBros_Red_Dizzy_CryWalk                       0x620405
#define ANIM_GoombaBros_Red_Dizzy_Run                           0x620406
#define ANIM_GoombaBros_Red_Dizzy_CryRun                        0x620407
#define ANIM_GoombaBros_Red_Dizzy_Midair                        0x620408
#define ANIM_GoombaBros_Red_Dizzy_Hurt                          0x620409
#define ANIM_GoombaBros_Red_Dizzy_Talk                          0x62040A
#define ANIM_GoombaBros_Red_Dizzy_CryTalk                       0x62040B
#define ANIM_GoombaBros_Red_Dizzy_Dizzy                         0x62040C
#define ANIM_GoombaBros_Red_Dizzy_Sleep                         0x62040D
#define ANIM_GoombaBros_Red_Dizzy_BurnHurt                      0x62040E
#define ANIM_GoombaBros_Red_Dizzy_BurnStill                     0x62040F

#define ANIM_GoombaBros_Blue_Dizzy_Still                        0x620500
#define ANIM_GoombaBros_Blue_Dizzy_CryStill                     0x620501
#define ANIM_GoombaBros_Blue_Dizzy_Idle                         0x620502
#define ANIM_GoombaBros_Blue_Dizzy_CryIdle                      0x620503
#define ANIM_GoombaBros_Blue_Dizzy_Walk                         0x620504
#define ANIM_GoombaBros_Blue_Dizzy_CryWalk                      0x620505
#define ANIM_GoombaBros_Blue_Dizzy_Run                          0x620506
#define ANIM_GoombaBros_Blue_Dizzy_CryRun                       0x620507
#define ANIM_GoombaBros_Blue_Dizzy_Midair                       0x620508
#define ANIM_GoombaBros_Blue_Dizzy_Hurt                         0x620509
#define ANIM_GoombaBros_Blue_Dizzy_Talk                         0x62050A
#define ANIM_GoombaBros_Blue_Dizzy_CryTalk                      0x62050B
#define ANIM_GoombaBros_Blue_Dizzy_Dizzy                        0x62050C
#define ANIM_GoombaBros_Blue_Dizzy_Sleep                        0x62050D
#define ANIM_GoombaBros_Blue_Dizzy_BurnHurt                     0x62050E
#define ANIM_GoombaBros_Blue_Dizzy_BurnStill                    0x62050F

#define ANIM_GoombaBros_Red_Shocked_Still                       0x620600
#define ANIM_GoombaBros_Red_Shocked_CryStill                    0x620601
#define ANIM_GoombaBros_Red_Shocked_Idle                        0x620602
#define ANIM_GoombaBros_Red_Shocked_CryIdle                     0x620603
#define ANIM_GoombaBros_Red_Shocked_Walk                        0x620604
#define ANIM_GoombaBros_Red_Shocked_CryWalk                     0x620605
#define ANIM_GoombaBros_Red_Shocked_Run                         0x620606
#define ANIM_GoombaBros_Red_Shocked_CryRun                      0x620607
#define ANIM_GoombaBros_Red_Shocked_Midair                      0x620608
#define ANIM_GoombaBros_Red_Shocked_Hurt                        0x620609
#define ANIM_GoombaBros_Red_Shocked_Talk                        0x62060A
#define ANIM_GoombaBros_Red_Shocked_CryTalk                     0x62060B
#define ANIM_GoombaBros_Red_Shocked_Dizzy                       0x62060C
#define ANIM_GoombaBros_Red_Shocked_Sleep                       0x62060D
#define ANIM_GoombaBros_Red_Shocked_BurnHurt                    0x62060E
#define ANIM_GoombaBros_Red_Shocked_BurnStill                   0x62060F

#define ANIM_GoombaBros_Blue_Shocked_Still                      0x620700
#define ANIM_GoombaBros_Blue_Shocked_CryStill                   0x620701
#define ANIM_GoombaBros_Blue_Shocked_Idle                       0x620702
#define ANIM_GoombaBros_Blue_Shocked_CryIdle                    0x620703
#define ANIM_GoombaBros_Blue_Shocked_Walk                       0x620704
#define ANIM_GoombaBros_Blue_Shocked_CryWalk                    0x620705
#define ANIM_GoombaBros_Blue_Shocked_Run                        0x620706
#define ANIM_GoombaBros_Blue_Shocked_CryRun                     0x620707
#define ANIM_GoombaBros_Blue_Shocked_Midair                     0x620708
#define ANIM_GoombaBros_Blue_Shocked_Hurt                       0x620709
#define ANIM_GoombaBros_Blue_Shocked_Talk                       0x62070A
#define ANIM_GoombaBros_Blue_Shocked_CryTalk                    0x62070B
#define ANIM_GoombaBros_Blue_Shocked_Dizzy                      0x62070C
#define ANIM_GoombaBros_Blue_Shocked_Sleep                      0x62070D
#define ANIM_GoombaBros_Blue_Shocked_BurnHurt                   0x62070E
#define ANIM_GoombaBros_Blue_Shocked_BurnStill                  0x62070F

#define ANIM_GoombaBros_Burnt_Still                             0x620800
#define ANIM_GoombaBros_Burnt_CryStill                          0x620801
#define ANIM_GoombaBros_Burnt_Idle                              0x620802
#define ANIM_GoombaBros_Burnt_CryIdle                           0x620803
#define ANIM_GoombaBros_Burnt_Walk                              0x620804
#define ANIM_GoombaBros_Burnt_CryWalk                           0x620805
#define ANIM_GoombaBros_Burnt_Run                               0x620806
#define ANIM_GoombaBros_Burnt_CryRun                            0x620807
#define ANIM_GoombaBros_Burnt_Midair                            0x620808
#define ANIM_GoombaBros_Burnt_Hurt                              0x620809
#define ANIM_GoombaBros_Burnt_Talk                              0x62080A
#define ANIM_GoombaBros_Burnt_CryTalk                           0x62080B
#define ANIM_GoombaBros_Burnt_Dizzy                             0x62080C
#define ANIM_GoombaBros_Burnt_Sleep                             0x62080D
#define ANIM_GoombaBros_Burnt_BurnHurt                          0x62080E
#define ANIM_GoombaBros_Burnt_BurnStill                         0x62080F

#endif
