// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_GOOMBARIA_H_
#define _NPC_SPRITE_GOOMBARIA_H_

#include "types.h"

#define SPR_Goombaria 0x9E

#define SPR_PAL_Goombaria 0x0
#define SPR_PAL_Goombaria_Tear 0x1

#define ANIM_Goombaria_Still                                    0x9E0000
#define ANIM_Goombaria_Idle                                     0x9E0001
#define ANIM_Goombaria_SadIdle                                  0x9E0002
#define ANIM_Goombaria_LookUp                                   0x9E0003
#define ANIM_Goombaria_Stand                                    0x9E0004
#define ANIM_Goombaria_Walk                                     0x9E0005
#define ANIM_Goombaria_SadWalk                                  0x9E0006
#define ANIM_Goombaria_Run                                      0x9E0007
#define ANIM_Goombaria_SadRun                                   0x9E0008
#define ANIM_Goombaria_JumpEyesClosed                           0x9E0009
#define ANIM_Goombaria_Hurt                                     0x9E000A
#define ANIM_Goombaria_Talk                                     0x9E000B
#define ANIM_Goombaria_SadTalk                                  0x9E000C
#define ANIM_Goombaria_LookUpTalk                               0x9E000D
#define ANIM_Goombaria_Celebrate                                0x9E000E
#define ANIM_Goombaria_LeanOver                                 0x9E000F
#define ANIM_Goombaria_Inspect                                  0x9E0010
#define ANIM_Goombaria_Shock                                    0x9E0011
#define ANIM_Goombaria_Jump                                     0x9E0012
#define ANIM_Goombaria_Fall                                     0x9E0013

#define ANIM_Goombaria_Tear_Still                               0x9E0100
#define ANIM_Goombaria_Tear_Idle                                0x9E0101
#define ANIM_Goombaria_Tear_SadIdle                             0x9E0102
#define ANIM_Goombaria_Tear_LookUp                              0x9E0103
#define ANIM_Goombaria_Tear_Stand                               0x9E0104
#define ANIM_Goombaria_Tear_Walk                                0x9E0105
#define ANIM_Goombaria_Tear_SadWalk                             0x9E0106
#define ANIM_Goombaria_Tear_Run                                 0x9E0107
#define ANIM_Goombaria_Tear_SadRun                              0x9E0108
#define ANIM_Goombaria_Tear_JumpEyesClosed                      0x9E0109
#define ANIM_Goombaria_Tear_Hurt                                0x9E010A
#define ANIM_Goombaria_Tear_Talk                                0x9E010B
#define ANIM_Goombaria_Tear_SadTalk                             0x9E010C
#define ANIM_Goombaria_Tear_LookUpTalk                          0x9E010D
#define ANIM_Goombaria_Tear_Celebrate                           0x9E010E
#define ANIM_Goombaria_Tear_LeanOver                            0x9E010F
#define ANIM_Goombaria_Tear_Inspect                             0x9E0110
#define ANIM_Goombaria_Tear_Shock                               0x9E0111
#define ANIM_Goombaria_Tear_Jump                                0x9E0112
#define ANIM_Goombaria_Tear_Fall                                0x9E0113

#endif
