// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_GOOMA_H_
#define _NPC_SPRITE_GOOMA_H_

#include "types.h"

#define SPR_Gooma 0x9F

#define SPR_PAL_Gooma 0x0

#define ANIM_Gooma_Still                                        0x9F0000
#define ANIM_Gooma_Idle                                         0x9F0001
#define ANIM_Gooma_Walk                                         0x9F0002
#define ANIM_Gooma_Run                                          0x9F0003
#define ANIM_Gooma_Talk                                         0x9F0004

#endif
