// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_GOOMPA_H_
#define _NPC_SPRITE_GOOMPA_H_

#include "types.h"

#define SPR_Goompa 0x9D

#define SPR_PAL_Goompa 0x0

#define ANIM_Goompa_Still                                       0x9D0000
#define ANIM_Goompa_Idle                                        0x9D0001
#define ANIM_Goompa_Walk                                        0x9D0002
#define ANIM_Goompa_Run                                         0x9D0003
#define ANIM_Goompa_Jump                                        0x9D0004
#define ANIM_Goompa_Fall                                        0x9D0005
#define ANIM_Goompa_Hurt                                        0x9D0006
#define ANIM_Goompa_Injured                                     0x9D0007
#define ANIM_Goompa_Talk                                        0x9D0008
#define ANIM_Goompa_Celebrate                                   0x9D0009
#define ANIM_Goompa_WearyIdle                                   0x9D000A
#define ANIM_Goompa_WearyTalk                                   0x9D000B
#define ANIM_Goompa_WearyWalk                                   0x9D000C
#define ANIM_Goompa_Rummage                                     0x9D000D

#endif
