// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_GOURMETGUY_H_
#define _NPC_SPRITE_GOURMETGUY_H_

#include "types.h"

#define SPR_GourmetGuy 0xC1

#define SPR_PAL_GourmetGuy 0x0

#define ANIM_GourmetGuy_Still                                   0xC10000
#define ANIM_GourmetGuy_Idle                                    0xC10001
#define ANIM_GourmetGuy_Walk                                    0xC10002
#define ANIM_GourmetGuy_Panic                                   0xC10003
#define ANIM_GourmetGuy_Talk                                    0xC10004
#define ANIM_GourmetGuy_Eat                                     0xC10005
#define ANIM_GourmetGuy_SpitOut                                 0xC10006
#define ANIM_GourmetGuy_Surprise                                0xC10007
#define ANIM_GourmetGuy_TalkSurprise                            0xC10008
#define ANIM_GourmetGuy_Knife                                   0xC10009
#define ANIM_GourmetGuy_Fork                                    0xC1000A
#define ANIM_GourmetGuy_Leap                                    0xC1000B
#define ANIM_GourmetGuy_Inspect                                 0xC1000C
#define ANIM_GourmetGuy_SitIdle                                 0xC1000D

#endif
