// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_HARRYT_H_
#define _NPC_SPRITE_HARRYT_H_

#include "types.h"

#define SPR_HarryT 0x88

#define SPR_PAL_HarryT 0x0

#define ANIM_HarryT_Still                                       0x880000
#define ANIM_HarryT_Idle                                        0x880001
#define ANIM_HarryT_Walk                                        0x880002
#define ANIM_HarryT_Run                                         0x880003
#define ANIM_HarryT_Talk                                        0x880004
#define ANIM_HarryT_Unused1                                     0x880005
#define ANIM_HarryT_Unused2                                     0x880006

#endif
