// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_HEARTPLANT_H_
#define _NPC_SPRITE_HEARTPLANT_H_

#include "types.h"

#define SPR_HeartPlant 0x43

#define SPR_PAL_HeartPlant 0x0
#define SPR_PAL_HeartPlant_Gray 0x1

#define ANIM_HeartPlant_Anim00                                  0x430000
#define ANIM_HeartPlant_Anim01                                  0x430001

#define ANIM_HeartPlant_Gray_Anim00                             0x430100
#define ANIM_HeartPlant_Gray_Anim01                             0x430101

#endif
