// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_HERRINGWAY_H_
#define _NPC_SPRITE_HERRINGWAY_H_

#include "types.h"

#define SPR_Herringway 0xD1

#define SPR_PAL_Herringway 0x0

#define ANIM_Herringway_Still                                   0xD10000
#define ANIM_Herringway_Idle                                    0xD10001
#define ANIM_Herringway_Walk                                    0xD10002
#define ANIM_Herringway_Run                                     0xD10003
#define ANIM_Herringway_Talk                                    0xD10004
#define ANIM_Herringway_Recieve                                 0xD10005
#define ANIM_Herringway_IdleCarry                               0xD10006
#define ANIM_Herringway_TalkCarry                               0xD10007
#define ANIM_Herringway_WalkCarry                               0xD10008
#define ANIM_Herringway_RunCarry                                0xD10009

#endif
