// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_HURTPLANT_H_
#define _NPC_SPRITE_HURTPLANT_H_

#include "types.h"

#define SPR_HurtPlant 0x44

#define SPR_PAL_HurtPlant 0x0
#define SPR_PAL_HurtPlant_Poisoned 0x1
#define SPR_PAL_HurtPlant_Dizzy 0x2
#define SPR_PAL_HurtPlant_Shocked 0x3
#define SPR_PAL_HurtPlant_Burnt 0x4

#define ANIM_HurtPlant_Anim00                                   0x440000
#define ANIM_HurtPlant_Anim01                                   0x440001
#define ANIM_HurtPlant_Anim02                                   0x440002
#define ANIM_HurtPlant_Anim03                                   0x440003
#define ANIM_HurtPlant_Anim04                                   0x440004
#define ANIM_HurtPlant_Anim05                                   0x440005
#define ANIM_HurtPlant_Anim06                                   0x440006
#define ANIM_HurtPlant_Anim07                                   0x440007
#define ANIM_HurtPlant_Anim08                                   0x440008
#define ANIM_HurtPlant_Anim09                                   0x440009
#define ANIM_HurtPlant_Anim0A                                   0x44000A
#define ANIM_HurtPlant_Anim0B                                   0x44000B
#define ANIM_HurtPlant_Anim0C                                   0x44000C
#define ANIM_HurtPlant_Anim0D                                   0x44000D
#define ANIM_HurtPlant_Anim0E                                   0x44000E

#define ANIM_HurtPlant_Poisoned_Anim00                          0x440100
#define ANIM_HurtPlant_Poisoned_Anim01                          0x440101
#define ANIM_HurtPlant_Poisoned_Anim02                          0x440102
#define ANIM_HurtPlant_Poisoned_Anim03                          0x440103
#define ANIM_HurtPlant_Poisoned_Anim04                          0x440104
#define ANIM_HurtPlant_Poisoned_Anim05                          0x440105
#define ANIM_HurtPlant_Poisoned_Anim06                          0x440106
#define ANIM_HurtPlant_Poisoned_Anim07                          0x440107
#define ANIM_HurtPlant_Poisoned_Anim08                          0x440108
#define ANIM_HurtPlant_Poisoned_Anim09                          0x440109
#define ANIM_HurtPlant_Poisoned_Anim0A                          0x44010A
#define ANIM_HurtPlant_Poisoned_Anim0B                          0x44010B
#define ANIM_HurtPlant_Poisoned_Anim0C                          0x44010C
#define ANIM_HurtPlant_Poisoned_Anim0D                          0x44010D
#define ANIM_HurtPlant_Poisoned_Anim0E                          0x44010E

#define ANIM_HurtPlant_Dizzy_Anim00                             0x440200
#define ANIM_HurtPlant_Dizzy_Anim01                             0x440201
#define ANIM_HurtPlant_Dizzy_Anim02                             0x440202
#define ANIM_HurtPlant_Dizzy_Anim03                             0x440203
#define ANIM_HurtPlant_Dizzy_Anim04                             0x440204
#define ANIM_HurtPlant_Dizzy_Anim05                             0x440205
#define ANIM_HurtPlant_Dizzy_Anim06                             0x440206
#define ANIM_HurtPlant_Dizzy_Anim07                             0x440207
#define ANIM_HurtPlant_Dizzy_Anim08                             0x440208
#define ANIM_HurtPlant_Dizzy_Anim09                             0x440209
#define ANIM_HurtPlant_Dizzy_Anim0A                             0x44020A
#define ANIM_HurtPlant_Dizzy_Anim0B                             0x44020B
#define ANIM_HurtPlant_Dizzy_Anim0C                             0x44020C
#define ANIM_HurtPlant_Dizzy_Anim0D                             0x44020D
#define ANIM_HurtPlant_Dizzy_Anim0E                             0x44020E

#define ANIM_HurtPlant_Shocked_Anim00                           0x440300
#define ANIM_HurtPlant_Shocked_Anim01                           0x440301
#define ANIM_HurtPlant_Shocked_Anim02                           0x440302
#define ANIM_HurtPlant_Shocked_Anim03                           0x440303
#define ANIM_HurtPlant_Shocked_Anim04                           0x440304
#define ANIM_HurtPlant_Shocked_Anim05                           0x440305
#define ANIM_HurtPlant_Shocked_Anim06                           0x440306
#define ANIM_HurtPlant_Shocked_Anim07                           0x440307
#define ANIM_HurtPlant_Shocked_Anim08                           0x440308
#define ANIM_HurtPlant_Shocked_Anim09                           0x440309
#define ANIM_HurtPlant_Shocked_Anim0A                           0x44030A
#define ANIM_HurtPlant_Shocked_Anim0B                           0x44030B
#define ANIM_HurtPlant_Shocked_Anim0C                           0x44030C
#define ANIM_HurtPlant_Shocked_Anim0D                           0x44030D
#define ANIM_HurtPlant_Shocked_Anim0E                           0x44030E

#define ANIM_HurtPlant_Burnt_Anim00                             0x440400
#define ANIM_HurtPlant_Burnt_Anim01                             0x440401
#define ANIM_HurtPlant_Burnt_Anim02                             0x440402
#define ANIM_HurtPlant_Burnt_Anim03                             0x440403
#define ANIM_HurtPlant_Burnt_Anim04                             0x440404
#define ANIM_HurtPlant_Burnt_Anim05                             0x440405
#define ANIM_HurtPlant_Burnt_Anim06                             0x440406
#define ANIM_HurtPlant_Burnt_Anim07                             0x440407
#define ANIM_HurtPlant_Burnt_Anim08                             0x440408
#define ANIM_HurtPlant_Burnt_Anim09                             0x440409
#define ANIM_HurtPlant_Burnt_Anim0A                             0x44040A
#define ANIM_HurtPlant_Burnt_Anim0B                             0x44040B
#define ANIM_HurtPlant_Burnt_Anim0C                             0x44040C
#define ANIM_HurtPlant_Burnt_Anim0D                             0x44040D
#define ANIM_HurtPlant_Burnt_Anim0E                             0x44040E

#endif
