// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_KOLORADOWIFE_H_
#define _NPC_SPRITE_KOLORADOWIFE_H_

#include "types.h"

#define SPR_KoloradoWife 0xB4

#define SPR_PAL_KoloradoWife 0x0

#define ANIM_KoloradoWife_Still                                 0xB40000
#define ANIM_KoloradoWife_Idle                                  0xB40001
#define ANIM_KoloradoWife_Walk                                  0xB40002
#define ANIM_KoloradoWife_Run                                   0xB40003
#define ANIM_KoloradoWife_Talk                                  0xB40004

#endif
