// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_KOOPAKOOT_H_
#define _NPC_SPRITE_KOOPAKOOT_H_

#include "types.h"

#define SPR_KoopaKoot 0xB5

#define SPR_PAL_KoopaKoot 0x0

#define ANIM_KoopaKoot_Still                                    0xB50000
#define ANIM_KoopaKoot_Idle                                     0xB50001
#define ANIM_KoopaKoot_Walk                                     0xB50002
#define ANIM_KoopaKoot_Run                                      0xB50003
#define ANIM_KoopaKoot_Talk                                     0xB50004
#define ANIM_KoopaKoot_Celebrate                                0xB50005
#define ANIM_KoopaKoot_SwingCane                                0xB50006
#define ANIM_KoopaKoot_StillCane                                0xB50007
#define ANIM_KoopaKoot_TalkCane                                 0xB50008
#define ANIM_KoopaKoot_IdleCane                                 0xB50009

#endif
