// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_KOOPA_H_
#define _NPC_SPRITE_KOOPA_H_

#include "types.h"

#define SPR_Koopa 0x8F

#define SPR_PAL_Koopa 0x0
#define SPR_PAL_Koopa_Red 0x1

#define ANIM_Koopa_Still                                        0x8F0000
#define ANIM_Koopa_EmbedStill                                   0x8F0001
#define ANIM_Koopa_Idle                                         0x8F0002
#define ANIM_Koopa_LeanBack                                     0x8F0003
#define ANIM_Koopa_EmbedIdle                                    0x8F0004
#define ANIM_Koopa_Walk                                         0x8F0005
#define ANIM_Koopa_Run                                          0x8F0006
#define ANIM_Koopa_Talk                                         0x8F0007
#define ANIM_Koopa_LeanBackTalk                                 0x8F0008
#define ANIM_Koopa_Happy                                        0x8F0009
#define ANIM_Koopa_Shell                                        0x8F000A
#define ANIM_Koopa_Topple                                       0x8F000B

#define ANIM_Koopa_Red_Still                                    0x8F0100
#define ANIM_Koopa_Red_EmbedStill                               0x8F0101
#define ANIM_Koopa_Red_Idle                                     0x8F0102
#define ANIM_Koopa_Red_LeanBack                                 0x8F0103
#define ANIM_Koopa_Red_EmbedIdle                                0x8F0104
#define ANIM_Koopa_Red_Walk                                     0x8F0105
#define ANIM_Koopa_Red_Run                                      0x8F0106
#define ANIM_Koopa_Red_Talk                                     0x8F0107
#define ANIM_Koopa_Red_LeanBackTalk                             0x8F0108
#define ANIM_Koopa_Red_Happy                                    0x8F0109
#define ANIM_Koopa_Red_Shell                                    0x8F010A
#define ANIM_Koopa_Red_Topple                                   0x8F010B

#endif
