// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_KOOPATROL_H_
#define _NPC_SPRITE_KOOPATROL_H_

#include "types.h"

#define SPR_Koopatrol 0x59

#define SPR_PAL_Koopatrol 0x0
#define SPR_PAL_Koopatrol_Poisoned 0x1
#define SPR_PAL_Koopatrol_Dizzy 0x2
#define SPR_PAL_Koopatrol_Shocked 0x3
#define SPR_PAL_Koopatrol_Burnt 0x4

#define ANIM_Koopatrol_Anim00                                   0x590000
#define ANIM_Koopatrol_Anim01                                   0x590001
#define ANIM_Koopatrol_Anim02                                   0x590002
#define ANIM_Koopatrol_Anim03                                   0x590003
#define ANIM_Koopatrol_Anim04                                   0x590004
#define ANIM_Koopatrol_Anim05                                   0x590005
#define ANIM_Koopatrol_Anim06                                   0x590006
#define ANIM_Koopatrol_Anim07                                   0x590007
#define ANIM_Koopatrol_Anim08                                   0x590008
#define ANIM_Koopatrol_Anim09                                   0x590009
#define ANIM_Koopatrol_Anim0A                                   0x59000A
#define ANIM_Koopatrol_Anim0B                                   0x59000B
#define ANIM_Koopatrol_Anim0C                                   0x59000C
#define ANIM_Koopatrol_Anim0D                                   0x59000D
#define ANIM_Koopatrol_Anim0E                                   0x59000E
#define ANIM_Koopatrol_Anim0F                                   0x59000F
#define ANIM_Koopatrol_Anim10                                   0x590010
#define ANIM_Koopatrol_Anim11                                   0x590011
#define ANIM_Koopatrol_Anim12                                   0x590012
#define ANIM_Koopatrol_Anim13                                   0x590013
#define ANIM_Koopatrol_Anim14                                   0x590014
#define ANIM_Koopatrol_Anim15                                   0x590015
#define ANIM_Koopatrol_Anim16                                   0x590016

#define ANIM_Koopatrol_Poisoned_Anim00                          0x590100
#define ANIM_Koopatrol_Poisoned_Anim01                          0x590101
#define ANIM_Koopatrol_Poisoned_Anim02                          0x590102
#define ANIM_Koopatrol_Poisoned_Anim03                          0x590103
#define ANIM_Koopatrol_Poisoned_Anim04                          0x590104
#define ANIM_Koopatrol_Poisoned_Anim05                          0x590105
#define ANIM_Koopatrol_Poisoned_Anim06                          0x590106
#define ANIM_Koopatrol_Poisoned_Anim07                          0x590107
#define ANIM_Koopatrol_Poisoned_Anim08                          0x590108
#define ANIM_Koopatrol_Poisoned_Anim09                          0x590109
#define ANIM_Koopatrol_Poisoned_Anim0A                          0x59010A
#define ANIM_Koopatrol_Poisoned_Anim0B                          0x59010B
#define ANIM_Koopatrol_Poisoned_Anim0C                          0x59010C
#define ANIM_Koopatrol_Poisoned_Anim0D                          0x59010D
#define ANIM_Koopatrol_Poisoned_Anim0E                          0x59010E
#define ANIM_Koopatrol_Poisoned_Anim0F                          0x59010F
#define ANIM_Koopatrol_Poisoned_Anim10                          0x590110
#define ANIM_Koopatrol_Poisoned_Anim11                          0x590111
#define ANIM_Koopatrol_Poisoned_Anim12                          0x590112
#define ANIM_Koopatrol_Poisoned_Anim13                          0x590113
#define ANIM_Koopatrol_Poisoned_Anim14                          0x590114
#define ANIM_Koopatrol_Poisoned_Anim15                          0x590115
#define ANIM_Koopatrol_Poisoned_Anim16                          0x590116

#define ANIM_Koopatrol_Dizzy_Anim00                             0x590200
#define ANIM_Koopatrol_Dizzy_Anim01                             0x590201
#define ANIM_Koopatrol_Dizzy_Anim02                             0x590202
#define ANIM_Koopatrol_Dizzy_Anim03                             0x590203
#define ANIM_Koopatrol_Dizzy_Anim04                             0x590204
#define ANIM_Koopatrol_Dizzy_Anim05                             0x590205
#define ANIM_Koopatrol_Dizzy_Anim06                             0x590206
#define ANIM_Koopatrol_Dizzy_Anim07                             0x590207
#define ANIM_Koopatrol_Dizzy_Anim08                             0x590208
#define ANIM_Koopatrol_Dizzy_Anim09                             0x590209
#define ANIM_Koopatrol_Dizzy_Anim0A                             0x59020A
#define ANIM_Koopatrol_Dizzy_Anim0B                             0x59020B
#define ANIM_Koopatrol_Dizzy_Anim0C                             0x59020C
#define ANIM_Koopatrol_Dizzy_Anim0D                             0x59020D
#define ANIM_Koopatrol_Dizzy_Anim0E                             0x59020E
#define ANIM_Koopatrol_Dizzy_Anim0F                             0x59020F
#define ANIM_Koopatrol_Dizzy_Anim10                             0x590210
#define ANIM_Koopatrol_Dizzy_Anim11                             0x590211
#define ANIM_Koopatrol_Dizzy_Anim12                             0x590212
#define ANIM_Koopatrol_Dizzy_Anim13                             0x590213
#define ANIM_Koopatrol_Dizzy_Anim14                             0x590214
#define ANIM_Koopatrol_Dizzy_Anim15                             0x590215
#define ANIM_Koopatrol_Dizzy_Anim16                             0x590216

#define ANIM_Koopatrol_Shocked_Anim00                           0x590300
#define ANIM_Koopatrol_Shocked_Anim01                           0x590301
#define ANIM_Koopatrol_Shocked_Anim02                           0x590302
#define ANIM_Koopatrol_Shocked_Anim03                           0x590303
#define ANIM_Koopatrol_Shocked_Anim04                           0x590304
#define ANIM_Koopatrol_Shocked_Anim05                           0x590305
#define ANIM_Koopatrol_Shocked_Anim06                           0x590306
#define ANIM_Koopatrol_Shocked_Anim07                           0x590307
#define ANIM_Koopatrol_Shocked_Anim08                           0x590308
#define ANIM_Koopatrol_Shocked_Anim09                           0x590309
#define ANIM_Koopatrol_Shocked_Anim0A                           0x59030A
#define ANIM_Koopatrol_Shocked_Anim0B                           0x59030B
#define ANIM_Koopatrol_Shocked_Anim0C                           0x59030C
#define ANIM_Koopatrol_Shocked_Anim0D                           0x59030D
#define ANIM_Koopatrol_Shocked_Anim0E                           0x59030E
#define ANIM_Koopatrol_Shocked_Anim0F                           0x59030F
#define ANIM_Koopatrol_Shocked_Anim10                           0x590310
#define ANIM_Koopatrol_Shocked_Anim11                           0x590311
#define ANIM_Koopatrol_Shocked_Anim12                           0x590312
#define ANIM_Koopatrol_Shocked_Anim13                           0x590313
#define ANIM_Koopatrol_Shocked_Anim14                           0x590314
#define ANIM_Koopatrol_Shocked_Anim15                           0x590315
#define ANIM_Koopatrol_Shocked_Anim16                           0x590316

#define ANIM_Koopatrol_Burnt_Anim00                             0x590400
#define ANIM_Koopatrol_Burnt_Anim01                             0x590401
#define ANIM_Koopatrol_Burnt_Anim02                             0x590402
#define ANIM_Koopatrol_Burnt_Anim03                             0x590403
#define ANIM_Koopatrol_Burnt_Anim04                             0x590404
#define ANIM_Koopatrol_Burnt_Anim05                             0x590405
#define ANIM_Koopatrol_Burnt_Anim06                             0x590406
#define ANIM_Koopatrol_Burnt_Anim07                             0x590407
#define ANIM_Koopatrol_Burnt_Anim08                             0x590408
#define ANIM_Koopatrol_Burnt_Anim09                             0x590409
#define ANIM_Koopatrol_Burnt_Anim0A                             0x59040A
#define ANIM_Koopatrol_Burnt_Anim0B                             0x59040B
#define ANIM_Koopatrol_Burnt_Anim0C                             0x59040C
#define ANIM_Koopatrol_Burnt_Anim0D                             0x59040D
#define ANIM_Koopatrol_Burnt_Anim0E                             0x59040E
#define ANIM_Koopatrol_Burnt_Anim0F                             0x59040F
#define ANIM_Koopatrol_Burnt_Anim10                             0x590410
#define ANIM_Koopatrol_Burnt_Anim11                             0x590411
#define ANIM_Koopatrol_Burnt_Anim12                             0x590412
#define ANIM_Koopatrol_Burnt_Anim13                             0x590413
#define ANIM_Koopatrol_Burnt_Anim14                             0x590414
#define ANIM_Koopatrol_Burnt_Anim15                             0x590415
#define ANIM_Koopatrol_Burnt_Anim16                             0x590416

#endif
