// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_KOOPERWITHOUTSHELL_H_
#define _NPC_SPRITE_KOOPERWITHOUTSHELL_H_

#include "types.h"

#define SPR_KooperWithoutShell 0x11

#define SPR_PAL_KooperWithoutShell 0x0

#define ANIM_KooperWithoutShell_Still                           0x110000
#define ANIM_KooperWithoutShell_StillHappy                      0x110001
#define ANIM_KooperWithoutShell_StillAngry                      0x110002
#define ANIM_KooperWithoutShell_Idle                            0x110003
#define ANIM_KooperWithoutShell_IdleAngry                       0x110004
#define ANIM_KooperWithoutShell_Walk                            0x110005
#define ANIM_KooperWithoutShell_WalkAngry                       0x110006
#define ANIM_KooperWithoutShell_Run                             0x110007
#define ANIM_KooperWithoutShell_RunAngry                        0x110008
#define ANIM_KooperWithoutShell_Talk                            0x110009
#define ANIM_KooperWithoutShell_TalkAngry                       0x11000A
#define ANIM_KooperWithoutShell_Shout                           0x11000B
#define ANIM_KooperWithoutShell_ShoutAngry                      0x11000C
#define ANIM_KooperWithoutShell_Celebrate                       0x11000D
#define ANIM_KooperWithoutShell_CelebrateLoop                   0x11000E
#define ANIM_KooperWithoutShell_Bow                             0x11000F

#endif
