// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_LAKILULU_H_
#define _NPC_SPRITE_LAKILULU_H_

#include "types.h"

#define SPR_Lakilulu 0xCC

#define SPR_PAL_Lakilulu 0x0
#define SPR_PAL_Lakilulu_Spiny 0x1

#define ANIM_Lakilulu_Still                                     0xCC0000
#define ANIM_Lakilulu_Idle                                      0xCC0001
#define ANIM_Lakilulu_Walk                                      0xCC0002
#define ANIM_Lakilulu_Run                                       0xCC0003
#define ANIM_Lakilulu_Talk                                      0xCC0004
#define ANIM_Lakilulu_HappyNod                                  0xCC0005
#define ANIM_Lakilulu_HappyTalk                                 0xCC0006
#define ANIM_Lakilulu_Panic                                     0xCC0007
#define ANIM_Lakilulu_Shout                                     0xCC0008
#define ANIM_Lakilulu_ConcernedNod                              0xCC0009
#define ANIM_Lakilulu_ConcernedTalk                             0xCC000A
#define ANIM_Lakilulu_Spiny                                     0xCC000B
#define ANIM_Lakilulu_Lift                                      0xCC000C
#define ANIM_Lakilulu_Throw                                     0xCC000D

#define ANIM_Lakilulu_Spiny_Still                               0xCC0100
#define ANIM_Lakilulu_Spiny_Idle                                0xCC0101
#define ANIM_Lakilulu_Spiny_Walk                                0xCC0102
#define ANIM_Lakilulu_Spiny_Run                                 0xCC0103
#define ANIM_Lakilulu_Spiny_Talk                                0xCC0104
#define ANIM_Lakilulu_Spiny_HappyNod                            0xCC0105
#define ANIM_Lakilulu_Spiny_HappyTalk                           0xCC0106
#define ANIM_Lakilulu_Spiny_Panic                               0xCC0107
#define ANIM_Lakilulu_Spiny_Shout                               0xCC0108
#define ANIM_Lakilulu_Spiny_ConcernedNod                        0xCC0109
#define ANIM_Lakilulu_Spiny_ConcernedTalk                       0xCC010A
#define ANIM_Lakilulu_Spiny_Spiny                               0xCC010B
#define ANIM_Lakilulu_Spiny_Lift                                0xCC010C
#define ANIM_Lakilulu_Spiny_Throw                               0xCC010D

#endif
