// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_LEADERSFRIEND_H_
#define _NPC_SPRITE_LEADERSFRIEND_H_

#include "types.h"

#define SPR_LeadersFriend 0xC3

#define SPR_PAL_LeadersFriend 0x0

#define ANIM_LeadersFriend_Still                                0xC30000
#define ANIM_LeadersFriend_Idle                                 0xC30001
#define ANIM_LeadersFriend_Walk                                 0xC30002
#define ANIM_LeadersFriend_Run                                  0xC30003
#define ANIM_LeadersFriend_Talk                                 0xC30004
#define ANIM_LeadersFriend_Bow                                  0xC30005
#define ANIM_LeadersFriend_Plead                                0xC30006
#define ANIM_LeadersFriend_TalkPlead                            0xC30007
#define ANIM_LeadersFriend_StillSit                             0xC30008
#define ANIM_LeadersFriend_IdleSit                              0xC30009
#define ANIM_LeadersFriend_TalkSit                              0xC3000A
#define ANIM_LeadersFriend_BowSit                               0xC3000B
#define ANIM_LeadersFriend_TalkSitSad                           0xC3000C

#endif
