// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_LEAF_H_
#define _NPC_SPRITE_LEAF_H_

#include "types.h"

#define SPR_Leaf 0xE9

#define SPR_PAL_Leaf 0x0

#define ANIM_Leaf_Pivot                                         0xE90000

#endif
