// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_LILY_H_
#define _NPC_SPRITE_LILY_H_

#include "types.h"

#define SPR_Lily 0xC9

#define SPR_PAL_Lily 0x0

#define ANIM_Lily_Still                                         0xC90000
#define ANIM_Lily_Idle                                          0xC90001
#define ANIM_Lily_Talk                                          0xC90002
#define ANIM_Lily_TalkHappy                                     0xC90003
#define ANIM_Lily_TalkPlead                                     0xC90004
#define ANIM_Lily_Dread                                         0xC90005
#define ANIM_Lily_GiveItem                                      0xC90006
#define ANIM_Lily_IdleHappy                                     0xC90007
#define ANIM_Lily_IdlePlead                                     0xC90008
#define ANIM_Lily_DreadLoop                                     0xC90009

#endif
