// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_LUIGI_H_
#define _NPC_SPRITE_LUIGI_H_

#include "types.h"

#define SPR_Luigi 0x82

#define SPR_PAL_Luigi 0x0

#define ANIM_Luigi_Still                                        0x820000
#define ANIM_Luigi_StillLetter                                  0x820001
#define ANIM_Luigi_StillRead                                    0x820002
#define ANIM_Luigi_StillSit                                     0x820003
#define ANIM_Luigi_Idle                                         0x820004
#define ANIM_Luigi_IdleLetter                                   0x820005
#define ANIM_Luigi_IdleRead                                     0x820006
#define ANIM_Luigi_IdleSit                                      0x820007
#define ANIM_Luigi_Walk                                         0x820008
#define ANIM_Luigi_WalkLetter                                   0x820009
#define ANIM_Luigi_Run                                          0x82000A
#define ANIM_Luigi_RunLetter                                    0x82000B
#define ANIM_Luigi_JumpStance                                   0x82000C
#define ANIM_Luigi_Jump                                         0x82000D
#define ANIM_Luigi_Fall                                         0x82000E
#define ANIM_Luigi_Land                                         0x82000F
#define ANIM_Luigi_JumpStanceLetter                             0x820010
#define ANIM_Luigi_JumpLetter                                   0x820011
#define ANIM_Luigi_FallLetter                                   0x820012
#define ANIM_Luigi_LandLetter                                   0x820013
#define ANIM_Luigi_Talk                                         0x820014
#define ANIM_Luigi_TalkLetter                                   0x820015
#define ANIM_Luigi_TalkRead                                     0x820016
#define ANIM_Luigi_TalkSit                                      0x820017
#define ANIM_Luigi_OpenLetter                                   0x820018
#define ANIM_Luigi_ReadLetter                                   0x820019
#define ANIM_Luigi_CloseLetter                                  0x82001A
#define ANIM_Luigi_StillBack                                    0x82001B
#define ANIM_Luigi_IdleBack                                     0x82001C
#define ANIM_Luigi_WalkBack                                     0x82001D
#define ANIM_Luigi_RunBack                                      0x82001E

#endif
