// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_MAYORPENGUINWIFE_H_
#define _NPC_SPRITE_MAYORPENGUINWIFE_H_

#include "types.h"

#define SPR_MayorPenguinWife 0xCF

#define SPR_PAL_MayorPenguinWife 0x0

#define ANIM_MayorPenguinWife_Still                             0xCF0000
#define ANIM_MayorPenguinWife_Idle                              0xCF0001
#define ANIM_MayorPenguinWife_Walk                              0xCF0002
#define ANIM_MayorPenguinWife_Panic                             0xCF0003
#define ANIM_MayorPenguinWife_Talk                              0xCF0004
#define ANIM_MayorPenguinWife_Laugh                             0xCF0005
#define ANIM_MayorPenguinWife_Inspect                           0xCF0006
#define ANIM_MayorPenguinWife_Point                             0xCF0007
#define ANIM_MayorPenguinWife_PointTalk                         0xCF0008
#define ANIM_MayorPenguinWife_Horror                            0xCF0009
#define ANIM_MayorPenguinWife_Surprise                          0xCF000A

#endif
