// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_MERLOW_H_
#define _NPC_SPRITE_MERLOW_H_

#include "types.h"

#define SPR_Merlow 0xB2

#define SPR_PAL_Merlow 0x0

#define ANIM_Merlow_Still                                       0xB20000
#define ANIM_Merlow_Idle                                        0xB20001
#define ANIM_Merlow_Walk                                        0xB20002
#define ANIM_Merlow_Run                                         0xB20003
#define ANIM_Merlow_Talk                                        0xB20004
#define ANIM_Merlow_GiveItem                                    0xB20005

#endif
