// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_MERLAR_H_
#define _NPC_SPRITE_MERLAR_H_

#include "types.h"

#define SPR_Merlar 0xB1

#define SPR_PAL_Merlar 0x0

#define ANIM_Merlar_Still                                       0xB10000
#define ANIM_Merlar_Hover                                       0xB10001
#define ANIM_Merlar_Talk                                        0xB10002
#define ANIM_Merlar_Gather                                      0xB10003
#define ANIM_Merlar_Release                                     0xB10004

#endif
