// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_MOUSTAFA_H_
#define _NPC_SPRITE_MOUSTAFA_H_

#include "types.h"

#define SPR_Moustafa 0xBD

#define SPR_PAL_Moustafa 0x0

#define ANIM_Moustafa_Still                                     0xBD0000
#define ANIM_Moustafa_Idle                                      0xBD0001
#define ANIM_Moustafa_BlinkOnce                                 0xBD0002
#define ANIM_Moustafa_BlinkLoop                                 0xBD0003
#define ANIM_Moustafa_Run                                       0xBD0004
#define ANIM_Moustafa_Shout                                     0xBD0005
#define ANIM_Moustafa_Talk                                      0xBD0006
#define ANIM_Moustafa_Toss                                      0xBD0007
#define ANIM_Moustafa_ShoutAlt                                  0xBD0008

#endif
