// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_MOUSER_H_
#define _NPC_SPRITE_MOUSER_H_

#include "types.h"

#define SPR_Mouser 0x94

#define SPR_PAL_Mouser_Blue 0x0
#define SPR_PAL_Mouser_Purple 0x1

#define ANIM_Mouser_Blue_Still                                  0x940000
#define ANIM_Mouser_Blue_Idle                                   0x940001
#define ANIM_Mouser_Blue_Blink                                  0x940002
#define ANIM_Mouser_Blue_IdleOnlyBlink                          0x940003
#define ANIM_Mouser_Blue_Run                                    0x940004
#define ANIM_Mouser_Blue_Talk                                   0x940005
#define ANIM_Mouser_Blue_Whisper                                0x940006
#define ANIM_Mouser_Blue_Gossip                                 0x940007
#define ANIM_Mouser_Blue_GossipWhisper                          0x940008

#define ANIM_Mouser_Purple_Still                                0x940100
#define ANIM_Mouser_Purple_Idle                                 0x940101
#define ANIM_Mouser_Purple_Blink                                0x940102
#define ANIM_Mouser_Purple_IdleOnlyBlink                        0x940103
#define ANIM_Mouser_Purple_Run                                  0x940104
#define ANIM_Mouser_Purple_Talk                                 0x940105
#define ANIM_Mouser_Purple_Whisper                              0x940106
#define ANIM_Mouser_Purple_Gossip                               0x940107
#define ANIM_Mouser_Purple_GossipWhisper                        0x940108

#endif
