// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_MUSICIAN_H_
#define _NPC_SPRITE_MUSICIAN_H_

#include "types.h"

#define SPR_Musician 0x8E

#define SPR_PAL_Musician_Poet 0x0
#define SPR_PAL_Musician_Composer 0x1
#define SPR_PAL_Musician_Poet_Dark 0x2

#define ANIM_Musician_Poet_Still                                0x8E0000
#define ANIM_Musician_Poet_Idle                                 0x8E0001
#define ANIM_Musician_Poet_Talk                                 0x8E0002
#define ANIM_Musician_Poet_Write                                0x8E0003
#define ANIM_Musician_Poet_GivePaper                            0x8E0004
#define ANIM_Musician_Poet_Pensive                              0x8E0005
#define ANIM_Musician_Poet_ConductFast                          0x8E0006
#define ANIM_Musician_Poet_ConductSlow                          0x8E0007

#define ANIM_Musician_Composer_Still                            0x8E0100
#define ANIM_Musician_Composer_Idle                             0x8E0101
#define ANIM_Musician_Composer_Talk                             0x8E0102
#define ANIM_Musician_Composer_Write                            0x8E0103
#define ANIM_Musician_Composer_GivePaper                        0x8E0104
#define ANIM_Musician_Composer_Pensive                          0x8E0105
#define ANIM_Musician_Composer_ConductFast                      0x8E0106
#define ANIM_Musician_Composer_ConductSlow                      0x8E0107

#define ANIM_Musician_Poet_Dark_Still                           0x8E0200
#define ANIM_Musician_Poet_Dark_Idle                            0x8E0201
#define ANIM_Musician_Poet_Dark_Talk                            0x8E0202
#define ANIM_Musician_Poet_Dark_Write                           0x8E0203
#define ANIM_Musician_Poet_Dark_GivePaper                       0x8E0204
#define ANIM_Musician_Poet_Dark_Pensive                         0x8E0205
#define ANIM_Musician_Poet_Dark_ConductFast                     0x8E0206
#define ANIM_Musician_Poet_Dark_ConductSlow                     0x8E0207

#endif
