// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_PARADETUBBA_H_
#define _NPC_SPRITE_PARADETUBBA_H_

#include "types.h"

#define SPR_ParadeTubba 0xE4

#define SPR_PAL_ParadeTubba 0x0

#define ANIM_ParadeTubba_Still                                  0xE40000

#endif
