// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_PARADEKOLORADO_H_
#define _NPC_SPRITE_PARADEKOLORADO_H_

#include "types.h"

#define SPR_ParadeKolorado 0xDC

#define SPR_PAL_ParadeKolorado 0x0
#define SPR_PAL_ParadeKolorado_Wife 0x1

#define ANIM_ParadeKolorado_Idle                                0xDC0000
#define ANIM_ParadeKolorado_IdleFwd                             0xDC0001
#define ANIM_ParadeKolorado_Wave                                0xDC0002
#define ANIM_ParadeKolorado_WifeIdle                            0xDC0003
#define ANIM_ParadeKolorado_WifeIdleFwd                         0xDC0004
#define ANIM_ParadeKolorado_WifeWave                            0xDC0005

#define ANIM_ParadeKolorado_Wife_Idle                           0xDC0100
#define ANIM_ParadeKolorado_Wife_IdleFwd                        0xDC0101
#define ANIM_ParadeKolorado_Wife_Wave                           0xDC0102
#define ANIM_ParadeKolorado_Wife_WifeIdle                       0xDC0103
#define ANIM_ParadeKolorado_Wife_WifeIdleFwd                    0xDC0104
#define ANIM_ParadeKolorado_Wife_WifeWave                       0xDC0105

#endif
