// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_PARADEKOOPAS_H_
#define _NPC_SPRITE_PARADEKOOPAS_H_

#include "types.h"

#define SPR_ParadeKoopas 0xD7

#define SPR_PAL_ParadeKoopas_Bowser 0x0
#define SPR_PAL_ParadeKoopas_HammerBros 0x1
#define SPR_PAL_ParadeKoopas_Koopatrol 0x2
#define SPR_PAL_ParadeKoopas_Banner 0x3

#define ANIM_ParadeKoopas_Bowser_Bowser                         0xD70000
#define ANIM_ParadeKoopas_Bowser_Propeller                      0xD70001
#define ANIM_ParadeKoopas_Bowser_HammerBrosJuggle               0xD70002
#define ANIM_ParadeKoopas_Bowser_KoopatrolMarch                 0xD70003
#define ANIM_ParadeKoopas_Bowser_HammerBrosPanic                0xD70004
#define ANIM_ParadeKoopas_Bowser_KoopatrolPanic                 0xD70005

#define ANIM_ParadeKoopas_HammerBros_Bowser                     0xD70100
#define ANIM_ParadeKoopas_HammerBros_Propeller                  0xD70101
#define ANIM_ParadeKoopas_HammerBros_HammerBrosJuggle           0xD70102
#define ANIM_ParadeKoopas_HammerBros_KoopatrolMarch             0xD70103
#define ANIM_ParadeKoopas_HammerBros_HammerBrosPanic            0xD70104
#define ANIM_ParadeKoopas_HammerBros_KoopatrolPanic             0xD70105

#define ANIM_ParadeKoopas_Koopatrol_Bowser                      0xD70200
#define ANIM_ParadeKoopas_Koopatrol_Propeller                   0xD70201
#define ANIM_ParadeKoopas_Koopatrol_HammerBrosJuggle            0xD70202
#define ANIM_ParadeKoopas_Koopatrol_KoopatrolMarch              0xD70203
#define ANIM_ParadeKoopas_Koopatrol_HammerBrosPanic             0xD70204
#define ANIM_ParadeKoopas_Koopatrol_KoopatrolPanic              0xD70205

#define ANIM_ParadeKoopas_Banner_Bowser                         0xD70300
#define ANIM_ParadeKoopas_Banner_Propeller                      0xD70301
#define ANIM_ParadeKoopas_Banner_HammerBrosJuggle               0xD70302
#define ANIM_ParadeKoopas_Banner_KoopatrolMarch                 0xD70303
#define ANIM_ParadeKoopas_Banner_HammerBrosPanic                0xD70304
#define ANIM_ParadeKoopas_Banner_KoopatrolPanic                 0xD70305

#endif
