// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_PARADEHORN_H_
#define _NPC_SPRITE_PARADEHORN_H_

#include "types.h"

#define SPR_ParadeHorn 0xE3

#define SPR_PAL_ParadeHorn 0x0
#define SPR_PAL_ParadeHorn_Dark 0x1
#define SPR_PAL_ParadeHorn_DarkGlow 0x2

#define ANIM_ParadeHorn_Still                                   0xE30000
#define ANIM_ParadeHorn_Idle                                    0xE30001
#define ANIM_ParadeHorn_Walk                                    0xE30002

#define ANIM_ParadeHorn_Dark_Still                              0xE30100
#define ANIM_ParadeHorn_Dark_Idle                               0xE30101
#define ANIM_ParadeHorn_Dark_Walk                               0xE30102

#define ANIM_ParadeHorn_DarkGlow_Still                          0xE30200
#define ANIM_ParadeHorn_DarkGlow_Idle                           0xE30201
#define ANIM_ParadeHorn_DarkGlow_Walk                           0xE30202

#endif
