// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_PARADETWINK_H_
#define _NPC_SPRITE_PARADETWINK_H_

#include "types.h"

#define SPR_ParadeTwink 0xE8

#define SPR_PAL_ParadeTwink 0x0
#define SPR_PAL_ParadeTwink_Unused1 0x1
#define SPR_PAL_ParadeTwink_Unused2 0x2
#define SPR_PAL_ParadeTwink_Unused3 0x3

#define ANIM_ParadeTwink_Still                                  0xE80000
#define ANIM_ParadeTwink_Idle                                   0xE80001

#define ANIM_ParadeTwink_Unused1_Still                          0xE80100
#define ANIM_ParadeTwink_Unused1_Idle                           0xE80101

#define ANIM_ParadeTwink_Unused2_Still                          0xE80200
#define ANIM_ParadeTwink_Unused2_Idle                           0xE80201

#define ANIM_ParadeTwink_Unused3_Still                          0xE80300
#define ANIM_ParadeTwink_Unused3_Idle                           0xE80301

#endif
