// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_PARADEWIZARD_H_
#define _NPC_SPRITE_PARADEWIZARD_H_

#include "types.h"

#define SPR_ParadeWizard 0xE5

#define SPR_PAL_ParadeWizard_Merle 0x0
#define SPR_PAL_ParadeWizard_MerleGlow 0x1
#define SPR_PAL_ParadeWizard_Merlee 0x2
#define SPR_PAL_ParadeWizard_MerleeBrighter 0x3
#define SPR_PAL_ParadeWizard_MerleeBrightest 0x4
#define SPR_PAL_ParadeWizard_Merlon 0x5
#define SPR_PAL_ParadeWizard_MerlonGlow 0x6
#define SPR_PAL_ParadeWizard_Merluvlee 0x7
#define SPR_PAL_ParadeWizard_MerluvleeGlow 0x8
#define SPR_PAL_ParadeWizard_Merlow 0x9
#define SPR_PAL_ParadeWizard_MerlowGlow 0xA
#define SPR_PAL_ParadeWizard_Merlar 0xB
#define SPR_PAL_ParadeWizard_MerlarGlow 0xC

#define ANIM_ParadeWizard_Merle_MerleGather                     0xE50000
#define ANIM_ParadeWizard_Merle_MerleRelease                    0xE50001
#define ANIM_ParadeWizard_Merle_MerleeGather                    0xE50002
#define ANIM_ParadeWizard_Merle_MerleeRelease                   0xE50003
#define ANIM_ParadeWizard_Merle_MerlonGather                    0xE50004
#define ANIM_ParadeWizard_Merle_MerlonRelease                   0xE50005
#define ANIM_ParadeWizard_Merle_MerluvleeGather                 0xE50006
#define ANIM_ParadeWizard_Merle_MerluvleeRelease                0xE50007
#define ANIM_ParadeWizard_Merle_MerlowGather                    0xE50008
#define ANIM_ParadeWizard_Merle_MerlowRelease                   0xE50009
#define ANIM_ParadeWizard_Merle_MerlarGather                    0xE5000A
#define ANIM_ParadeWizard_Merle_MerlarRelease                   0xE5000B

#define ANIM_ParadeWizard_MerleGlow_MerleGather                 0xE50100
#define ANIM_ParadeWizard_MerleGlow_MerleRelease                0xE50101
#define ANIM_ParadeWizard_MerleGlow_MerleeGather                0xE50102
#define ANIM_ParadeWizard_MerleGlow_MerleeRelease               0xE50103
#define ANIM_ParadeWizard_MerleGlow_MerlonGather                0xE50104
#define ANIM_ParadeWizard_MerleGlow_MerlonRelease               0xE50105
#define ANIM_ParadeWizard_MerleGlow_MerluvleeGather             0xE50106
#define ANIM_ParadeWizard_MerleGlow_MerluvleeRelease            0xE50107
#define ANIM_ParadeWizard_MerleGlow_MerlowGather                0xE50108
#define ANIM_ParadeWizard_MerleGlow_MerlowRelease               0xE50109
#define ANIM_ParadeWizard_MerleGlow_MerlarGather                0xE5010A
#define ANIM_ParadeWizard_MerleGlow_MerlarRelease               0xE5010B

#define ANIM_ParadeWizard_Merlee_MerleGather                    0xE50200
#define ANIM_ParadeWizard_Merlee_MerleRelease                   0xE50201
#define ANIM_ParadeWizard_Merlee_MerleeGather                   0xE50202
#define ANIM_ParadeWizard_Merlee_MerleeRelease                  0xE50203
#define ANIM_ParadeWizard_Merlee_MerlonGather                   0xE50204
#define ANIM_ParadeWizard_Merlee_MerlonRelease                  0xE50205
#define ANIM_ParadeWizard_Merlee_MerluvleeGather                0xE50206
#define ANIM_ParadeWizard_Merlee_MerluvleeRelease               0xE50207
#define ANIM_ParadeWizard_Merlee_MerlowGather                   0xE50208
#define ANIM_ParadeWizard_Merlee_MerlowRelease                  0xE50209
#define ANIM_ParadeWizard_Merlee_MerlarGather                   0xE5020A
#define ANIM_ParadeWizard_Merlee_MerlarRelease                  0xE5020B

#define ANIM_ParadeWizard_MerleeBrighter_MerleGather            0xE50300
#define ANIM_ParadeWizard_MerleeBrighter_MerleRelease           0xE50301
#define ANIM_ParadeWizard_MerleeBrighter_MerleeGather           0xE50302
#define ANIM_ParadeWizard_MerleeBrighter_MerleeRelease          0xE50303
#define ANIM_ParadeWizard_MerleeBrighter_MerlonGather           0xE50304
#define ANIM_ParadeWizard_MerleeBrighter_MerlonRelease          0xE50305
#define ANIM_ParadeWizard_MerleeBrighter_MerluvleeGather        0xE50306
#define ANIM_ParadeWizard_MerleeBrighter_MerluvleeRelease       0xE50307
#define ANIM_ParadeWizard_MerleeBrighter_MerlowGather           0xE50308
#define ANIM_ParadeWizard_MerleeBrighter_MerlowRelease          0xE50309
#define ANIM_ParadeWizard_MerleeBrighter_MerlarGather           0xE5030A
#define ANIM_ParadeWizard_MerleeBrighter_MerlarRelease          0xE5030B

#define ANIM_ParadeWizard_MerleeBrightest_MerleGather           0xE50400
#define ANIM_ParadeWizard_MerleeBrightest_MerleRelease          0xE50401
#define ANIM_ParadeWizard_MerleeBrightest_MerleeGather          0xE50402
#define ANIM_ParadeWizard_MerleeBrightest_MerleeRelease         0xE50403
#define ANIM_ParadeWizard_MerleeBrightest_MerlonGather          0xE50404
#define ANIM_ParadeWizard_MerleeBrightest_MerlonRelease         0xE50405
#define ANIM_ParadeWizard_MerleeBrightest_MerluvleeGather       0xE50406
#define ANIM_ParadeWizard_MerleeBrightest_MerluvleeRelease      0xE50407
#define ANIM_ParadeWizard_MerleeBrightest_MerlowGather          0xE50408
#define ANIM_ParadeWizard_MerleeBrightest_MerlowRelease         0xE50409
#define ANIM_ParadeWizard_MerleeBrightest_MerlarGather          0xE5040A
#define ANIM_ParadeWizard_MerleeBrightest_MerlarRelease         0xE5040B

#define ANIM_ParadeWizard_Merlon_MerleGather                    0xE50500
#define ANIM_ParadeWizard_Merlon_MerleRelease                   0xE50501
#define ANIM_ParadeWizard_Merlon_MerleeGather                   0xE50502
#define ANIM_ParadeWizard_Merlon_MerleeRelease                  0xE50503
#define ANIM_ParadeWizard_Merlon_MerlonGather                   0xE50504
#define ANIM_ParadeWizard_Merlon_MerlonRelease                  0xE50505
#define ANIM_ParadeWizard_Merlon_MerluvleeGather                0xE50506
#define ANIM_ParadeWizard_Merlon_MerluvleeRelease               0xE50507
#define ANIM_ParadeWizard_Merlon_MerlowGather                   0xE50508
#define ANIM_ParadeWizard_Merlon_MerlowRelease                  0xE50509
#define ANIM_ParadeWizard_Merlon_MerlarGather                   0xE5050A
#define ANIM_ParadeWizard_Merlon_MerlarRelease                  0xE5050B

#define ANIM_ParadeWizard_MerlonGlow_MerleGather                0xE50600
#define ANIM_ParadeWizard_MerlonGlow_MerleRelease               0xE50601
#define ANIM_ParadeWizard_MerlonGlow_MerleeGather               0xE50602
#define ANIM_ParadeWizard_MerlonGlow_MerleeRelease              0xE50603
#define ANIM_ParadeWizard_MerlonGlow_MerlonGather               0xE50604
#define ANIM_ParadeWizard_MerlonGlow_MerlonRelease              0xE50605
#define ANIM_ParadeWizard_MerlonGlow_MerluvleeGather            0xE50606
#define ANIM_ParadeWizard_MerlonGlow_MerluvleeRelease           0xE50607
#define ANIM_ParadeWizard_MerlonGlow_MerlowGather               0xE50608
#define ANIM_ParadeWizard_MerlonGlow_MerlowRelease              0xE50609
#define ANIM_ParadeWizard_MerlonGlow_MerlarGather               0xE5060A
#define ANIM_ParadeWizard_MerlonGlow_MerlarRelease              0xE5060B

#define ANIM_ParadeWizard_Merluvlee_MerleGather                 0xE50700
#define ANIM_ParadeWizard_Merluvlee_MerleRelease                0xE50701
#define ANIM_ParadeWizard_Merluvlee_MerleeGather                0xE50702
#define ANIM_ParadeWizard_Merluvlee_MerleeRelease               0xE50703
#define ANIM_ParadeWizard_Merluvlee_MerlonGather                0xE50704
#define ANIM_ParadeWizard_Merluvlee_MerlonRelease               0xE50705
#define ANIM_ParadeWizard_Merluvlee_MerluvleeGather             0xE50706
#define ANIM_ParadeWizard_Merluvlee_MerluvleeRelease            0xE50707
#define ANIM_ParadeWizard_Merluvlee_MerlowGather                0xE50708
#define ANIM_ParadeWizard_Merluvlee_MerlowRelease               0xE50709
#define ANIM_ParadeWizard_Merluvlee_MerlarGather                0xE5070A
#define ANIM_ParadeWizard_Merluvlee_MerlarRelease               0xE5070B

#define ANIM_ParadeWizard_MerluvleeGlow_MerleGather             0xE50800
#define ANIM_ParadeWizard_MerluvleeGlow_MerleRelease            0xE50801
#define ANIM_ParadeWizard_MerluvleeGlow_MerleeGather            0xE50802
#define ANIM_ParadeWizard_MerluvleeGlow_MerleeRelease           0xE50803
#define ANIM_ParadeWizard_MerluvleeGlow_MerlonGather            0xE50804
#define ANIM_ParadeWizard_MerluvleeGlow_MerlonRelease           0xE50805
#define ANIM_ParadeWizard_MerluvleeGlow_MerluvleeGather         0xE50806
#define ANIM_ParadeWizard_MerluvleeGlow_MerluvleeRelease        0xE50807
#define ANIM_ParadeWizard_MerluvleeGlow_MerlowGather            0xE50808
#define ANIM_ParadeWizard_MerluvleeGlow_MerlowRelease           0xE50809
#define ANIM_ParadeWizard_MerluvleeGlow_MerlarGather            0xE5080A
#define ANIM_ParadeWizard_MerluvleeGlow_MerlarRelease           0xE5080B

#define ANIM_ParadeWizard_Merlow_MerleGather                    0xE50900
#define ANIM_ParadeWizard_Merlow_MerleRelease                   0xE50901
#define ANIM_ParadeWizard_Merlow_MerleeGather                   0xE50902
#define ANIM_ParadeWizard_Merlow_MerleeRelease                  0xE50903
#define ANIM_ParadeWizard_Merlow_MerlonGather                   0xE50904
#define ANIM_ParadeWizard_Merlow_MerlonRelease                  0xE50905
#define ANIM_ParadeWizard_Merlow_MerluvleeGather                0xE50906
#define ANIM_ParadeWizard_Merlow_MerluvleeRelease               0xE50907
#define ANIM_ParadeWizard_Merlow_MerlowGather                   0xE50908
#define ANIM_ParadeWizard_Merlow_MerlowRelease                  0xE50909
#define ANIM_ParadeWizard_Merlow_MerlarGather                   0xE5090A
#define ANIM_ParadeWizard_Merlow_MerlarRelease                  0xE5090B

#define ANIM_ParadeWizard_MerlowGlow_MerleGather                0xE50A00
#define ANIM_ParadeWizard_MerlowGlow_MerleRelease               0xE50A01
#define ANIM_ParadeWizard_MerlowGlow_MerleeGather               0xE50A02
#define ANIM_ParadeWizard_MerlowGlow_MerleeRelease              0xE50A03
#define ANIM_ParadeWizard_MerlowGlow_MerlonGather               0xE50A04
#define ANIM_ParadeWizard_MerlowGlow_MerlonRelease              0xE50A05
#define ANIM_ParadeWizard_MerlowGlow_MerluvleeGather            0xE50A06
#define ANIM_ParadeWizard_MerlowGlow_MerluvleeRelease           0xE50A07
#define ANIM_ParadeWizard_MerlowGlow_MerlowGather               0xE50A08
#define ANIM_ParadeWizard_MerlowGlow_MerlowRelease              0xE50A09
#define ANIM_ParadeWizard_MerlowGlow_MerlarGather               0xE50A0A
#define ANIM_ParadeWizard_MerlowGlow_MerlarRelease              0xE50A0B

#define ANIM_ParadeWizard_Merlar_MerleGather                    0xE50B00
#define ANIM_ParadeWizard_Merlar_MerleRelease                   0xE50B01
#define ANIM_ParadeWizard_Merlar_MerleeGather                   0xE50B02
#define ANIM_ParadeWizard_Merlar_MerleeRelease                  0xE50B03
#define ANIM_ParadeWizard_Merlar_MerlonGather                   0xE50B04
#define ANIM_ParadeWizard_Merlar_MerlonRelease                  0xE50B05
#define ANIM_ParadeWizard_Merlar_MerluvleeGather                0xE50B06
#define ANIM_ParadeWizard_Merlar_MerluvleeRelease               0xE50B07
#define ANIM_ParadeWizard_Merlar_MerlowGather                   0xE50B08
#define ANIM_ParadeWizard_Merlar_MerlowRelease                  0xE50B09
#define ANIM_ParadeWizard_Merlar_MerlarGather                   0xE50B0A
#define ANIM_ParadeWizard_Merlar_MerlarRelease                  0xE50B0B

#define ANIM_ParadeWizard_MerlarGlow_MerleGather                0xE50C00
#define ANIM_ParadeWizard_MerlarGlow_MerleRelease               0xE50C01
#define ANIM_ParadeWizard_MerlarGlow_MerleeGather               0xE50C02
#define ANIM_ParadeWizard_MerlarGlow_MerleeRelease              0xE50C03
#define ANIM_ParadeWizard_MerlarGlow_MerlonGather               0xE50C04
#define ANIM_ParadeWizard_MerlarGlow_MerlonRelease              0xE50C05
#define ANIM_ParadeWizard_MerlarGlow_MerluvleeGather            0xE50C06
#define ANIM_ParadeWizard_MerlarGlow_MerluvleeRelease           0xE50C07
#define ANIM_ParadeWizard_MerlarGlow_MerlowGather               0xE50C08
#define ANIM_ParadeWizard_MerlarGlow_MerlowRelease              0xE50C09
#define ANIM_ParadeWizard_MerlarGlow_MerlarGather               0xE50C0A
#define ANIM_ParadeWizard_MerlarGlow_MerlarRelease              0xE50C0B

#endif
