// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_PARADEMARIO_H_
#define _NPC_SPRITE_PARADEMARIO_H_

#include "types.h"

#define SPR_ParadeMario 0xE6

#define SPR_PAL_ParadeMario 0x0

#define ANIM_ParadeMario_Still                                  0xE60000
#define ANIM_ParadeMario_StillBack                              0xE60001
#define ANIM_ParadeMario_Idle                                   0xE60002
#define ANIM_ParadeMario_Walk                                   0xE60003
#define ANIM_ParadeMario_WalkBack                               0xE60004
#define ANIM_ParadeMario_Wave                                   0xE60005
#define ANIM_ParadeMario_LookUp                                 0xE60006
#define ANIM_ParadeMario_StillUp                                0xE60007
#define ANIM_ParadeMario_WaveUp                                 0xE60008
#define ANIM_ParadeMario_NodYes                                 0xE60009
#define ANIM_ParadeMario_Surprise                               0xE6000A

#endif
