// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_PARADELUIGI_H_
#define _NPC_SPRITE_PARADELUIGI_H_

#include "types.h"

#define SPR_ParadeLuigi 0xD9

#define SPR_PAL_ParadeLuigi 0x0

#define ANIM_ParadeLuigi_Still                                  0xD90000
#define ANIM_ParadeLuigi_Idle                                   0xD90001
#define ANIM_ParadeLuigi_March                                  0xD90002
#define ANIM_ParadeLuigi_MarchInPlace                           0xD90003
#define ANIM_ParadeLuigi_BlowWhistle                            0xD90004

#endif
