// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_PENGUIN_H_
#define _NPC_SPRITE_PENGUIN_H_

#include "types.h"

#define SPR_Penguin 0x9A

#define SPR_PAL_Penguin 0x0

#define ANIM_Penguin_Still                                      0x9A0000
#define ANIM_Penguin_Idle                                       0x9A0001
#define ANIM_Penguin_Walk                                       0x9A0002
#define ANIM_Penguin_Run                                        0x9A0003
#define ANIM_Penguin_Talk                                       0x9A0004
#define ANIM_Penguin_Celebrate                                  0x9A0005
#define ANIM_Penguin_Happy                                      0x9A0006

#endif
