// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_PETUNIA_H_
#define _NPC_SPRITE_PETUNIA_H_

#include "types.h"

#define SPR_Petunia 0xC7

#define SPR_PAL_Petunia 0x0

#define ANIM_Petunia_Still                                      0xC70000
#define ANIM_Petunia_Idle                                       0xC70001
#define ANIM_Petunia_Talk                                       0xC70002
#define ANIM_Petunia_Dance                                      0xC70003
#define ANIM_Petunia_GiveItem                                   0xC70004
#define ANIM_Petunia_Bashful                                    0xC70005
#define ANIM_Petunia_Angry                                      0xC70006
#define ANIM_Petunia_AngryTalk                                  0xC70007
#define ANIM_Petunia_HappyTalk                                  0xC70008
#define ANIM_Petunia_Sad                                        0xC70009
#define ANIM_Petunia_Horror                                     0xC7000A

#endif
