// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_POSTMASTER_H_
#define _NPC_SPRITE_POSTMASTER_H_

#include "types.h"

#define SPR_Postmaster 0x8A

#define SPR_PAL_Postmaster 0x0

#define ANIM_Postmaster_Still                                   0x8A0000
#define ANIM_Postmaster_Idle                                    0x8A0001
#define ANIM_Postmaster_Talk                                    0x8A0002
#define ANIM_Postmaster_GiveItem                                0x8A0003
#define ANIM_Postmaster_IdleAlt                                 0x8A0004
#define ANIM_Postmaster_Unused1                                 0x8A0005
#define ANIM_Postmaster_Unused2                                 0x8A0006
#define ANIM_Postmaster_Unused3                                 0x8A0007
#define ANIM_Postmaster_Unused4                                 0x8A0008
#define ANIM_Postmaster_Unused5                                 0x8A0009

#endif
