// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_RAVEN_H_
#define _NPC_SPRITE_RAVEN_H_

#include "types.h"

#define SPR_Raven 0x98

#define SPR_PAL_Raven 0x0

#define ANIM_Raven_Still                                        0x980000
#define ANIM_Raven_Idle                                         0x980001
#define ANIM_Raven_IdleBack                                     0x980002
#define ANIM_Raven_Walk                                         0x980003
#define ANIM_Raven_Run                                          0x980004
#define ANIM_Raven_Talk                                         0x980005
#define ANIM_Raven_Flail                                        0x980006
#define ANIM_Raven_Crash                                        0x980007

#endif
