// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_RIPCHEATO_H_
#define _NPC_SPRITE_RIPCHEATO_H_

#include "types.h"

#define SPR_RipCheato 0xAE

#define SPR_PAL_RipCheato 0x0

#define ANIM_RipCheato_Still                                    0xAE0000
#define ANIM_RipCheato_Idle                                     0xAE0001
#define ANIM_RipCheato_Walk                                     0xAE0002
#define ANIM_RipCheato_Run                                      0xAE0003
#define ANIM_RipCheato_Talk                                     0xAE0004

#endif
