// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_ROSIE_H_
#define _NPC_SPRITE_ROSIE_H_

#include "types.h"

#define SPR_Rosie 0xCA

#define SPR_PAL_Rosie 0x0

#define ANIM_Rosie_Still                                        0xCA0000
#define ANIM_Rosie_Idle                                         0xCA0001
#define ANIM_Rosie_IdleHold                                     0xCA0002
#define ANIM_Rosie_Talk                                         0xCA0003
#define ANIM_Rosie_TalkHold                                     0xCA0004
#define ANIM_Rosie_TakeOut                                      0xCA0005
#define ANIM_Rosie_GiveItem                                     0xCA0006

#endif
