// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_RUSST_H_
#define _NPC_SPRITE_RUSST_H_

#include "types.h"

#define SPR_RussT 0xA9

#define SPR_PAL_RussT 0x0

#define ANIM_RussT_Still                                        0xA90000
#define ANIM_RussT_Idle                                         0xA90001
#define ANIM_RussT_Walk                                         0xA90002
#define ANIM_RussT_Run                                          0xA90003
#define ANIM_RussT_Talk                                         0xA90004
#define ANIM_RussT_Think                                        0xA90005
#define ANIM_RussT_Lecture                                      0xA90006
#define ANIM_RussT_AdjustGlasses                                0xA90007
#define ANIM_RussT_Panic                                        0xA90008
#define ANIM_RussT_Disappointed                                 0xA90009

#endif
