// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_SHIVERTOAD_H_
#define _NPC_SPRITE_SHIVERTOAD_H_

#include "types.h"

#define SPR_ShiverToad 0x9B

#define SPR_PAL_ShiverToad_Red 0x0
#define SPR_PAL_ShiverToad_Green 0x1
#define SPR_PAL_ShiverToad_Blue 0x2
#define SPR_PAL_ShiverToad_Yellow 0x3

#define ANIM_ShiverToad_Red_Still                               0x9B0000
#define ANIM_ShiverToad_Red_Idle                                0x9B0001
#define ANIM_ShiverToad_Red_Walk                                0x9B0002
#define ANIM_ShiverToad_Red_Run                                 0x9B0003
#define ANIM_ShiverToad_Red_Talk                                0x9B0004

#define ANIM_ShiverToad_Green_Still                             0x9B0100
#define ANIM_ShiverToad_Green_Idle                              0x9B0101
#define ANIM_ShiverToad_Green_Walk                              0x9B0102
#define ANIM_ShiverToad_Green_Run                               0x9B0103
#define ANIM_ShiverToad_Green_Talk                              0x9B0104

#define ANIM_ShiverToad_Blue_Still                              0x9B0200
#define ANIM_ShiverToad_Blue_Idle                               0x9B0201
#define ANIM_ShiverToad_Blue_Walk                               0x9B0202
#define ANIM_ShiverToad_Blue_Run                                0x9B0203
#define ANIM_ShiverToad_Blue_Talk                               0x9B0204

#define ANIM_ShiverToad_Yellow_Still                            0x9B0300
#define ANIM_ShiverToad_Yellow_Idle                             0x9B0301
#define ANIM_ShiverToad_Yellow_Walk                             0x9B0302
#define ANIM_ShiverToad_Yellow_Run                              0x9B0303
#define ANIM_ShiverToad_Yellow_Talk                             0x9B0304

#endif
