// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_SPIKYGOOMNUT_H_
#define _NPC_SPRITE_SPIKYGOOMNUT_H_

#include "types.h"

#define SPR_SpikyGoomnut 0x64

#define SPR_PAL_SpikyGoomnut 0x0

#define ANIM_SpikyGoomnut_Still                                 0x640000

#endif
