// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_STILTGUY_H_
#define _NPC_SPRITE_STILTGUY_H_

#include "types.h"

#define SPR_StiltGuy 0x70

#define SPR_PAL_StiltGuy 0x0
#define SPR_PAL_StiltGuy_Poisoned 0x1
#define SPR_PAL_StiltGuy_Dizzy 0x2
#define SPR_PAL_StiltGuy_Shocked 0x3
#define SPR_PAL_StiltGuy_Burnt 0x4

#define ANIM_StiltGuy_Anim00                                    0x700000
#define ANIM_StiltGuy_Anim01                                    0x700001
#define ANIM_StiltGuy_Anim02                                    0x700002
#define ANIM_StiltGuy_Anim03                                    0x700003
#define ANIM_StiltGuy_Anim04                                    0x700004
#define ANIM_StiltGuy_Anim05                                    0x700005
#define ANIM_StiltGuy_Anim06                                    0x700006
#define ANIM_StiltGuy_Anim07                                    0x700007
#define ANIM_StiltGuy_Anim08                                    0x700008
#define ANIM_StiltGuy_Anim09                                    0x700009
#define ANIM_StiltGuy_Anim0A                                    0x70000A

#define ANIM_StiltGuy_Poisoned_Anim00                           0x700100
#define ANIM_StiltGuy_Poisoned_Anim01                           0x700101
#define ANIM_StiltGuy_Poisoned_Anim02                           0x700102
#define ANIM_StiltGuy_Poisoned_Anim03                           0x700103
#define ANIM_StiltGuy_Poisoned_Anim04                           0x700104
#define ANIM_StiltGuy_Poisoned_Anim05                           0x700105
#define ANIM_StiltGuy_Poisoned_Anim06                           0x700106
#define ANIM_StiltGuy_Poisoned_Anim07                           0x700107
#define ANIM_StiltGuy_Poisoned_Anim08                           0x700108
#define ANIM_StiltGuy_Poisoned_Anim09                           0x700109
#define ANIM_StiltGuy_Poisoned_Anim0A                           0x70010A

#define ANIM_StiltGuy_Dizzy_Anim00                              0x700200
#define ANIM_StiltGuy_Dizzy_Anim01                              0x700201
#define ANIM_StiltGuy_Dizzy_Anim02                              0x700202
#define ANIM_StiltGuy_Dizzy_Anim03                              0x700203
#define ANIM_StiltGuy_Dizzy_Anim04                              0x700204
#define ANIM_StiltGuy_Dizzy_Anim05                              0x700205
#define ANIM_StiltGuy_Dizzy_Anim06                              0x700206
#define ANIM_StiltGuy_Dizzy_Anim07                              0x700207
#define ANIM_StiltGuy_Dizzy_Anim08                              0x700208
#define ANIM_StiltGuy_Dizzy_Anim09                              0x700209
#define ANIM_StiltGuy_Dizzy_Anim0A                              0x70020A

#define ANIM_StiltGuy_Shocked_Anim00                            0x700300
#define ANIM_StiltGuy_Shocked_Anim01                            0x700301
#define ANIM_StiltGuy_Shocked_Anim02                            0x700302
#define ANIM_StiltGuy_Shocked_Anim03                            0x700303
#define ANIM_StiltGuy_Shocked_Anim04                            0x700304
#define ANIM_StiltGuy_Shocked_Anim05                            0x700305
#define ANIM_StiltGuy_Shocked_Anim06                            0x700306
#define ANIM_StiltGuy_Shocked_Anim07                            0x700307
#define ANIM_StiltGuy_Shocked_Anim08                            0x700308
#define ANIM_StiltGuy_Shocked_Anim09                            0x700309
#define ANIM_StiltGuy_Shocked_Anim0A                            0x70030A

#define ANIM_StiltGuy_Burnt_Anim00                              0x700400
#define ANIM_StiltGuy_Burnt_Anim01                              0x700401
#define ANIM_StiltGuy_Burnt_Anim02                              0x700402
#define ANIM_StiltGuy_Burnt_Anim03                              0x700403
#define ANIM_StiltGuy_Burnt_Anim04                              0x700404
#define ANIM_StiltGuy_Burnt_Anim05                              0x700405
#define ANIM_StiltGuy_Burnt_Anim06                              0x700406
#define ANIM_StiltGuy_Burnt_Anim07                              0x700407
#define ANIM_StiltGuy_Burnt_Anim08                              0x700408
#define ANIM_StiltGuy_Burnt_Anim09                              0x700409
#define ANIM_StiltGuy_Burnt_Anim0A                              0x70040A

#endif
