// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_TAYCET_H_
#define _NPC_SPRITE_TAYCET_H_

#include "types.h"

#define SPR_TayceT 0xAA

#define SPR_PAL_TayceT 0x0
#define SPR_PAL_TayceT_Pan 0x1

#define ANIM_TayceT_Still                                       0xAA0000
#define ANIM_TayceT_Idle                                        0xAA0001
#define ANIM_TayceT_Walk                                        0xAA0002
#define ANIM_TayceT_Run                                         0xAA0003
#define ANIM_TayceT_Talk                                        0xAA0004
#define ANIM_TayceT_TalkHappy                                   0xAA0005
#define ANIM_TayceT_IdleSad                                     0xAA0006
#define ANIM_TayceT_Cooking                                     0xAA0007
#define ANIM_TayceT_TurnBack                                    0xAA0008
#define ANIM_TayceT_TurnAway                                    0xAA0009
#define ANIM_TayceT_TalkFwd                                     0xAA000A
#define ANIM_TayceT_Carry                                       0xAA000B
#define ANIM_TayceT_Pan                                         0xAA000C

#define ANIM_TayceT_Pan_Still                                   0xAA0100
#define ANIM_TayceT_Pan_Idle                                    0xAA0101
#define ANIM_TayceT_Pan_Walk                                    0xAA0102
#define ANIM_TayceT_Pan_Run                                     0xAA0103
#define ANIM_TayceT_Pan_Talk                                    0xAA0104
#define ANIM_TayceT_Pan_TalkHappy                               0xAA0105
#define ANIM_TayceT_Pan_IdleSad                                 0xAA0106
#define ANIM_TayceT_Pan_Cooking                                 0xAA0107
#define ANIM_TayceT_Pan_TurnBack                                0xAA0108
#define ANIM_TayceT_Pan_TurnAway                                0xAA0109
#define ANIM_TayceT_Pan_TalkFwd                                 0xAA010A
#define ANIM_TayceT_Pan_Carry                                   0xAA010B
#define ANIM_TayceT_Pan_Pan                                     0xAA010C

#endif
