// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_TOAD_H_
#define _NPC_SPRITE_TOAD_H_

#include "types.h"

#define SPR_Toad 0x83

#define SPR_PAL_Toad_Red 0x0
#define SPR_PAL_Toad_Green 0x1
#define SPR_PAL_Toad_Blue 0x2
#define SPR_PAL_Toad_Yellow 0x3
#define SPR_PAL_Toad_Pink 0x4

#define ANIM_Toad_Red_Still                                     0x830000
#define ANIM_Toad_Red_Idle                                      0x830001
#define ANIM_Toad_Red_Walk                                      0x830002
#define ANIM_Toad_Red_Run                                       0x830003
#define ANIM_Toad_Red_Talk                                      0x830004
#define ANIM_Toad_Red_Celebrate                                 0x830005
#define ANIM_Toad_Red_Disappointed                              0x830006
#define ANIM_Toad_Red_GiveItem                                  0x830007
#define ANIM_Toad_Red_Panic                                     0x830008

#define ANIM_Toad_Green_Still                                   0x830100
#define ANIM_Toad_Green_Idle                                    0x830101
#define ANIM_Toad_Green_Walk                                    0x830102
#define ANIM_Toad_Green_Run                                     0x830103
#define ANIM_Toad_Green_Talk                                    0x830104
#define ANIM_Toad_Green_Celebrate                               0x830105
#define ANIM_Toad_Green_Disappointed                            0x830106
#define ANIM_Toad_Green_GiveItem                                0x830107
#define ANIM_Toad_Green_Panic                                   0x830108

#define ANIM_Toad_Blue_Still                                    0x830200
#define ANIM_Toad_Blue_Idle                                     0x830201
#define ANIM_Toad_Blue_Walk                                     0x830202
#define ANIM_Toad_Blue_Run                                      0x830203
#define ANIM_Toad_Blue_Talk                                     0x830204
#define ANIM_Toad_Blue_Celebrate                                0x830205
#define ANIM_Toad_Blue_Disappointed                             0x830206
#define ANIM_Toad_Blue_GiveItem                                 0x830207
#define ANIM_Toad_Blue_Panic                                    0x830208

#define ANIM_Toad_Yellow_Still                                  0x830300
#define ANIM_Toad_Yellow_Idle                                   0x830301
#define ANIM_Toad_Yellow_Walk                                   0x830302
#define ANIM_Toad_Yellow_Run                                    0x830303
#define ANIM_Toad_Yellow_Talk                                   0x830304
#define ANIM_Toad_Yellow_Celebrate                              0x830305
#define ANIM_Toad_Yellow_Disappointed                           0x830306
#define ANIM_Toad_Yellow_GiveItem                               0x830307
#define ANIM_Toad_Yellow_Panic                                  0x830308

#define ANIM_Toad_Pink_Still                                    0x830400
#define ANIM_Toad_Pink_Idle                                     0x830401
#define ANIM_Toad_Pink_Walk                                     0x830402
#define ANIM_Toad_Pink_Run                                      0x830403
#define ANIM_Toad_Pink_Talk                                     0x830404
#define ANIM_Toad_Pink_Celebrate                                0x830405
#define ANIM_Toad_Pink_Disappointed                             0x830406
#define ANIM_Toad_Pink_GiveItem                                 0x830407
#define ANIM_Toad_Pink_Panic                                    0x830408

#endif
