// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_TOADKID_H_
#define _NPC_SPRITE_TOADKID_H_

#include "types.h"

#define SPR_ToadKid 0x86

#define SPR_PAL_ToadKid_Red 0x0
#define SPR_PAL_ToadKid_Green 0x1
#define SPR_PAL_ToadKid_Blue 0x2
#define SPR_PAL_ToadKid_Yellow 0x3

#define ANIM_ToadKid_Red_Still                                  0x860000
#define ANIM_ToadKid_Red_Idle                                   0x860001
#define ANIM_ToadKid_Red_Walk                                   0x860002
#define ANIM_ToadKid_Red_Run                                    0x860003
#define ANIM_ToadKid_Red_Talk                                   0x860004
#define ANIM_ToadKid_Red_Celebrate                              0x860005
#define ANIM_ToadKid_Red_Disappointed                           0x860006

#define ANIM_ToadKid_Green_Still                                0x860100
#define ANIM_ToadKid_Green_Idle                                 0x860101
#define ANIM_ToadKid_Green_Walk                                 0x860102
#define ANIM_ToadKid_Green_Run                                  0x860103
#define ANIM_ToadKid_Green_Talk                                 0x860104
#define ANIM_ToadKid_Green_Celebrate                            0x860105
#define ANIM_ToadKid_Green_Disappointed                         0x860106

#define ANIM_ToadKid_Blue_Still                                 0x860200
#define ANIM_ToadKid_Blue_Idle                                  0x860201
#define ANIM_ToadKid_Blue_Walk                                  0x860202
#define ANIM_ToadKid_Blue_Run                                   0x860203
#define ANIM_ToadKid_Blue_Talk                                  0x860204
#define ANIM_ToadKid_Blue_Celebrate                             0x860205
#define ANIM_ToadKid_Blue_Disappointed                          0x860206

#define ANIM_ToadKid_Yellow_Still                               0x860300
#define ANIM_ToadKid_Yellow_Idle                                0x860301
#define ANIM_ToadKid_Yellow_Walk                                0x860302
#define ANIM_ToadKid_Yellow_Run                                 0x860303
#define ANIM_ToadKid_Yellow_Talk                                0x860304
#define ANIM_ToadKid_Yellow_Celebrate                           0x860305
#define ANIM_ToadKid_Yellow_Disappointed                        0x860306

#endif
