// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_TOADGUARD_H_
#define _NPC_SPRITE_TOADGUARD_H_

#include "types.h"

#define SPR_ToadGuard 0x87

#define SPR_PAL_ToadGuard_Red 0x0
#define SPR_PAL_ToadGuard_Green 0x1
#define SPR_PAL_ToadGuard_Blue 0x2
#define SPR_PAL_ToadGuard_Yellow 0x3

#define ANIM_ToadGuard_Red_Still                                0x870000
#define ANIM_ToadGuard_Red_Idle                                 0x870001
#define ANIM_ToadGuard_Red_Walk                                 0x870002
#define ANIM_ToadGuard_Red_Run                                  0x870003
#define ANIM_ToadGuard_Red_Talk                                 0x870004

#define ANIM_ToadGuard_Green_Still                              0x870100
#define ANIM_ToadGuard_Green_Idle                               0x870101
#define ANIM_ToadGuard_Green_Walk                               0x870102
#define ANIM_ToadGuard_Green_Run                                0x870103
#define ANIM_ToadGuard_Green_Talk                               0x870104

#define ANIM_ToadGuard_Blue_Still                               0x870200
#define ANIM_ToadGuard_Blue_Idle                                0x870201
#define ANIM_ToadGuard_Blue_Walk                                0x870202
#define ANIM_ToadGuard_Blue_Run                                 0x870203
#define ANIM_ToadGuard_Blue_Talk                                0x870204

#define ANIM_ToadGuard_Yellow_Still                             0x870300
#define ANIM_ToadGuard_Yellow_Idle                              0x870301
#define ANIM_ToadGuard_Yellow_Walk                              0x870302
#define ANIM_ToadGuard_Yellow_Run                               0x870303
#define ANIM_ToadGuard_Yellow_Talk                              0x870304

#endif
