// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_TOADETTE_H_
#define _NPC_SPRITE_TOADETTE_H_

#include "types.h"

#define SPR_Toadette 0x84

#define SPR_PAL_Toadette_Orange 0x0
#define SPR_PAL_Toadette_Pink 0x1
#define SPR_PAL_Toadette_Green 0x2
#define SPR_PAL_Toadette_Purple 0x3

#define ANIM_Toadette_Orange_Still                              0x840000
#define ANIM_Toadette_Orange_Idle                               0x840001
#define ANIM_Toadette_Orange_Walk                               0x840002
#define ANIM_Toadette_Orange_Run                                0x840003
#define ANIM_Toadette_Orange_Talk                               0x840004
#define ANIM_Toadette_Orange_Celebrate                          0x840005
#define ANIM_Toadette_Orange_Disappointed                       0x840006
#define ANIM_Toadette_Orange_GiveItem                           0x840007

#define ANIM_Toadette_Pink_Still                                0x840100
#define ANIM_Toadette_Pink_Idle                                 0x840101
#define ANIM_Toadette_Pink_Walk                                 0x840102
#define ANIM_Toadette_Pink_Run                                  0x840103
#define ANIM_Toadette_Pink_Talk                                 0x840104
#define ANIM_Toadette_Pink_Celebrate                            0x840105
#define ANIM_Toadette_Pink_Disappointed                         0x840106
#define ANIM_Toadette_Pink_GiveItem                             0x840107

#define ANIM_Toadette_Green_Still                               0x840200
#define ANIM_Toadette_Green_Idle                                0x840201
#define ANIM_Toadette_Green_Walk                                0x840202
#define ANIM_Toadette_Green_Run                                 0x840203
#define ANIM_Toadette_Green_Talk                                0x840204
#define ANIM_Toadette_Green_Celebrate                           0x840205
#define ANIM_Toadette_Green_Disappointed                        0x840206
#define ANIM_Toadette_Green_GiveItem                            0x840207

#define ANIM_Toadette_Purple_Still                              0x840300
#define ANIM_Toadette_Purple_Idle                               0x840301
#define ANIM_Toadette_Purple_Walk                               0x840302
#define ANIM_Toadette_Purple_Run                                0x840303
#define ANIM_Toadette_Purple_Talk                               0x840304
#define ANIM_Toadette_Purple_Celebrate                          0x840305
#define ANIM_Toadette_Purple_Disappointed                       0x840306
#define ANIM_Toadette_Purple_GiveItem                           0x840307

#endif
