// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_TOADMINISTER_H_
#define _NPC_SPRITE_TOADMINISTER_H_

#include "types.h"

#define SPR_ToadMinister 0x89

#define SPR_PAL_ToadMinister 0x0

#define ANIM_ToadMinister_Still                                 0x890000
#define ANIM_ToadMinister_Idle                                  0x890001
#define ANIM_ToadMinister_Walk                                  0x890002
#define ANIM_ToadMinister_Run                                   0x890003
#define ANIM_ToadMinister_Talk                                  0x890004
#define ANIM_ToadMinister_RaiseArm                              0x890005
#define ANIM_ToadMinister_Think                                 0x890006
#define ANIM_ToadMinister_Invite                                0x890007

#endif
