// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_TRAINTOAD_H_
#define _NPC_SPRITE_TRAINTOAD_H_

#include "types.h"

#define SPR_TrainToad 0x8C

#define SPR_PAL_TrainToad 0x0
#define SPR_PAL_TrainToad_Pink 0x1
#define SPR_PAL_TrainToad_Blue 0x2
#define SPR_PAL_TrainToad_Green 0x3
#define SPR_PAL_TrainToad_Red 0x4
#define SPR_PAL_TrainToad_White 0x5

#define ANIM_TrainToad_Still                                    0x8C0000
#define ANIM_TrainToad_Idle                                     0x8C0001
#define ANIM_TrainToad_SadIdle                                  0x8C0002
#define ANIM_TrainToad_Walk                                     0x8C0003
#define ANIM_TrainToad_Talk                                     0x8C0004
#define ANIM_TrainToad_LowerHead                                0x8C0005
#define ANIM_TrainToad_SadTalk                                  0x8C0006

#define ANIM_TrainToad_Pink_Still                               0x8C0100
#define ANIM_TrainToad_Pink_Idle                                0x8C0101
#define ANIM_TrainToad_Pink_SadIdle                             0x8C0102
#define ANIM_TrainToad_Pink_Walk                                0x8C0103
#define ANIM_TrainToad_Pink_Talk                                0x8C0104
#define ANIM_TrainToad_Pink_LowerHead                           0x8C0105
#define ANIM_TrainToad_Pink_SadTalk                             0x8C0106

#define ANIM_TrainToad_Blue_Still                               0x8C0200
#define ANIM_TrainToad_Blue_Idle                                0x8C0201
#define ANIM_TrainToad_Blue_SadIdle                             0x8C0202
#define ANIM_TrainToad_Blue_Walk                                0x8C0203
#define ANIM_TrainToad_Blue_Talk                                0x8C0204
#define ANIM_TrainToad_Blue_LowerHead                           0x8C0205
#define ANIM_TrainToad_Blue_SadTalk                             0x8C0206

#define ANIM_TrainToad_Green_Still                              0x8C0300
#define ANIM_TrainToad_Green_Idle                               0x8C0301
#define ANIM_TrainToad_Green_SadIdle                            0x8C0302
#define ANIM_TrainToad_Green_Walk                               0x8C0303
#define ANIM_TrainToad_Green_Talk                               0x8C0304
#define ANIM_TrainToad_Green_LowerHead                          0x8C0305
#define ANIM_TrainToad_Green_SadTalk                            0x8C0306

#define ANIM_TrainToad_Red_Still                                0x8C0400
#define ANIM_TrainToad_Red_Idle                                 0x8C0401
#define ANIM_TrainToad_Red_SadIdle                              0x8C0402
#define ANIM_TrainToad_Red_Walk                                 0x8C0403
#define ANIM_TrainToad_Red_Talk                                 0x8C0404
#define ANIM_TrainToad_Red_LowerHead                            0x8C0405
#define ANIM_TrainToad_Red_SadTalk                              0x8C0406

#define ANIM_TrainToad_White_Still                              0x8C0500
#define ANIM_TrainToad_White_Idle                               0x8C0501
#define ANIM_TrainToad_White_SadIdle                            0x8C0502
#define ANIM_TrainToad_White_Walk                               0x8C0503
#define ANIM_TrainToad_White_Talk                               0x8C0504
#define ANIM_TrainToad_White_LowerHead                          0x8C0505
#define ANIM_TrainToad_White_SadTalk                            0x8C0506

#endif
