// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_VANNAT_H_
#define _NPC_SPRITE_VANNAT_H_

#include "types.h"

#define SPR_VannaT 0x85

#define SPR_PAL_VannaT 0x0

#define ANIM_VannaT_Still                                       0x850000
#define ANIM_VannaT_Walk                                        0x850001
#define ANIM_VannaT_Happy                                       0x850002
#define ANIM_VannaT_Clap                                        0x850003
#define ANIM_VannaT_Shrug                                       0x850004
#define ANIM_VannaT_Wave                                        0x850005

#endif
