// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_VILLAGELEADER_H_
#define _NPC_SPRITE_VILLAGELEADER_H_

#include "types.h"

#define SPR_VillageLeader 0xC2

#define SPR_PAL_VillageLeader 0x0

#define ANIM_VillageLeader_Still                                0xC20000
#define ANIM_VillageLeader_StillSad                             0xC20001
#define ANIM_VillageLeader_StillSit                             0xC20002
#define ANIM_VillageLeader_Idle                                 0xC20003
#define ANIM_VillageLeader_IdleSad                              0xC20004
#define ANIM_VillageLeader_IdleSit                              0xC20005
#define ANIM_VillageLeader_Walk                                 0xC20006
#define ANIM_VillageLeader_Panic                                0xC20007
#define ANIM_VillageLeader_Run                                  0xC20008
#define ANIM_VillageLeader_Talk                                 0xC20009
#define ANIM_VillageLeader_Shout                                0xC2000A
#define ANIM_VillageLeader_TalkSit                              0xC2000B
#define ANIM_VillageLeader_Celebrate                            0xC2000C
#define ANIM_VillageLeader_CrossArms                            0xC2000D
#define ANIM_VillageLeader_Rummage                              0xC2000E
#define ANIM_VillageLeader_Jump                                 0xC2000F
#define ANIM_VillageLeader_Fall                                 0xC20010
#define ANIM_VillageLeader_Land                                 0xC20011
#define ANIM_VillageLeader_GetUp                                0xC20012

#endif
