// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_WORLDELDSTAR_H_
#define _NPC_SPRITE_WORLDELDSTAR_H_

#include "types.h"

#define SPR_WorldEldstar 0x12

#define SPR_PAL_WorldEldstar 0x0
#define SPR_PAL_WorldEldstar_Glowing 0x1

#define ANIM_WorldEldstar_Still                                 0x120000
#define ANIM_WorldEldstar_Idle                                  0x120001
#define ANIM_WorldEldstar_Wave                                  0x120002
#define ANIM_WorldEldstar_Leap                                  0x120003
#define ANIM_WorldEldstar_Panic                                 0x120004
#define ANIM_WorldEldstar_Angry                                 0x120005
#define ANIM_WorldEldstar_Hurt                                  0x120006
#define ANIM_WorldEldstar_Back                                  0x120007
#define ANIM_WorldEldstar_Talk                                  0x120008

#define ANIM_WorldEldstar_Glowing_Still                         0x120100
#define ANIM_WorldEldstar_Glowing_Idle                          0x120101
#define ANIM_WorldEldstar_Glowing_Wave                          0x120102
#define ANIM_WorldEldstar_Glowing_Leap                          0x120103
#define ANIM_WorldEldstar_Glowing_Panic                         0x120104
#define ANIM_WorldEldstar_Glowing_Angry                         0x120105
#define ANIM_WorldEldstar_Glowing_Hurt                          0x120106
#define ANIM_WorldEldstar_Glowing_Back                          0x120107
#define ANIM_WorldEldstar_Glowing_Talk                          0x120108

#endif
