// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_WORLDKALMAR_H_
#define _NPC_SPRITE_WORLDKALMAR_H_

#include "types.h"

#define SPR_WorldKalmar 0x18

#define SPR_PAL_WorldKalmar 0x0
#define SPR_PAL_WorldKalmar_Glowing 0x1

#define ANIM_WorldKalmar_Still                                  0x180000
#define ANIM_WorldKalmar_Idle                                   0x180001
#define ANIM_WorldKalmar_Talk                                   0x180002
#define ANIM_WorldKalmar_Leap                                   0x180003
#define ANIM_WorldKalmar_LeanLeft                               0x180004
#define ANIM_WorldKalmar_LeanRight                              0x180005
#define ANIM_WorldKalmar_LeanLeftAlt                            0x180006
#define ANIM_WorldKalmar_TalkHappy                              0x180007
#define ANIM_WorldKalmar_Panic                                  0x180008
#define ANIM_WorldKalmar_Back                                   0x180009
#define ANIM_WorldKalmar_Hurt                                   0x18000A

#define ANIM_WorldKalmar_Glowing_Still                          0x180100
#define ANIM_WorldKalmar_Glowing_Idle                           0x180101
#define ANIM_WorldKalmar_Glowing_Talk                           0x180102
#define ANIM_WorldKalmar_Glowing_Leap                           0x180103
#define ANIM_WorldKalmar_Glowing_LeanLeft                       0x180104
#define ANIM_WorldKalmar_Glowing_LeanRight                      0x180105
#define ANIM_WorldKalmar_Glowing_LeanLeftAlt                    0x180106
#define ANIM_WorldKalmar_Glowing_TalkHappy                      0x180107
#define ANIM_WorldKalmar_Glowing_Panic                          0x180108
#define ANIM_WorldKalmar_Glowing_Back                           0x180109
#define ANIM_WorldKalmar_Glowing_Hurt                           0x18010A

#endif
