// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_WORLDLAKILESTER_H_
#define _NPC_SPRITE_WORLDLAKILESTER_H_

#include "types.h"

#define SPR_WorldLakilester 0x08

#define SPR_PAL_WorldLakilester 0x0
#define SPR_PAL_WorldLakilester_Spiny 0x1
#define SPR_PAL_WorldLakilester_Golden 0x2
#define SPR_PAL_WorldLakilester_Poisoned 0x3
#define SPR_PAL_WorldLakilester_Spiny_Poisoned 0x4
#define SPR_PAL_WorldLakilester_Golden_Poisoned 0x5
#define SPR_PAL_WorldLakilester_Inactive 0x6
#define SPR_PAL_WorldLakilester_Dizzy 0x7
#define SPR_PAL_WorldLakilester_Spiny_Dizzy 0x8
#define SPR_PAL_WorldLakilester_Shocked 0x9
#define SPR_PAL_WorldLakilester_Spiny_Shocked 0xA
#define SPR_PAL_WorldLakilester_Golden_Shocked 0xB
#define SPR_PAL_WorldLakilester_Burnt 0xC

#define ANIM_WorldLakilester_Still                              0x080000
#define ANIM_WorldLakilester_Idle                               0x080001
#define ANIM_WorldLakilester_StrainIdle                         0x080002
#define ANIM_WorldLakilester_IdleTough                          0x080003
#define ANIM_WorldLakilester_Tired                              0x080004
#define ANIM_WorldLakilester_Walk                               0x080005
#define ANIM_WorldLakilester_StrainWalk                         0x080006
#define ANIM_WorldLakilester_Run                                0x080007
#define ANIM_WorldLakilester_StrainRun                          0x080008
#define ANIM_WorldLakilester_Talk                               0x080009
#define ANIM_WorldLakilester_TiredTalk                          0x08000A
#define ANIM_WorldLakilester_Shout                              0x08000B
#define ANIM_WorldLakilester_Vanish                             0x08000C
#define ANIM_WorldLakilester_Celebrate                          0x08000D

#define ANIM_WorldLakilester_Spiny_Still                        0x080100
#define ANIM_WorldLakilester_Spiny_Idle                         0x080101
#define ANIM_WorldLakilester_Spiny_StrainIdle                   0x080102
#define ANIM_WorldLakilester_Spiny_IdleTough                    0x080103
#define ANIM_WorldLakilester_Spiny_Tired                        0x080104
#define ANIM_WorldLakilester_Spiny_Walk                         0x080105
#define ANIM_WorldLakilester_Spiny_StrainWalk                   0x080106
#define ANIM_WorldLakilester_Spiny_Run                          0x080107
#define ANIM_WorldLakilester_Spiny_StrainRun                    0x080108
#define ANIM_WorldLakilester_Spiny_Talk                         0x080109
#define ANIM_WorldLakilester_Spiny_TiredTalk                    0x08010A
#define ANIM_WorldLakilester_Spiny_Shout                        0x08010B
#define ANIM_WorldLakilester_Spiny_Vanish                       0x08010C
#define ANIM_WorldLakilester_Spiny_Celebrate                    0x08010D

#define ANIM_WorldLakilester_Golden_Still                       0x080200
#define ANIM_WorldLakilester_Golden_Idle                        0x080201
#define ANIM_WorldLakilester_Golden_StrainIdle                  0x080202
#define ANIM_WorldLakilester_Golden_IdleTough                   0x080203
#define ANIM_WorldLakilester_Golden_Tired                       0x080204
#define ANIM_WorldLakilester_Golden_Walk                        0x080205
#define ANIM_WorldLakilester_Golden_StrainWalk                  0x080206
#define ANIM_WorldLakilester_Golden_Run                         0x080207
#define ANIM_WorldLakilester_Golden_StrainRun                   0x080208
#define ANIM_WorldLakilester_Golden_Talk                        0x080209
#define ANIM_WorldLakilester_Golden_TiredTalk                   0x08020A
#define ANIM_WorldLakilester_Golden_Shout                       0x08020B
#define ANIM_WorldLakilester_Golden_Vanish                      0x08020C
#define ANIM_WorldLakilester_Golden_Celebrate                   0x08020D

#define ANIM_WorldLakilester_Poisoned_Still                     0x080300
#define ANIM_WorldLakilester_Poisoned_Idle                      0x080301
#define ANIM_WorldLakilester_Poisoned_StrainIdle                0x080302
#define ANIM_WorldLakilester_Poisoned_IdleTough                 0x080303
#define ANIM_WorldLakilester_Poisoned_Tired                     0x080304
#define ANIM_WorldLakilester_Poisoned_Walk                      0x080305
#define ANIM_WorldLakilester_Poisoned_StrainWalk                0x080306
#define ANIM_WorldLakilester_Poisoned_Run                       0x080307
#define ANIM_WorldLakilester_Poisoned_StrainRun                 0x080308
#define ANIM_WorldLakilester_Poisoned_Talk                      0x080309
#define ANIM_WorldLakilester_Poisoned_TiredTalk                 0x08030A
#define ANIM_WorldLakilester_Poisoned_Shout                     0x08030B
#define ANIM_WorldLakilester_Poisoned_Vanish                    0x08030C
#define ANIM_WorldLakilester_Poisoned_Celebrate                 0x08030D

#define ANIM_WorldLakilester_Spiny_Poisoned_Still               0x080400
#define ANIM_WorldLakilester_Spiny_Poisoned_Idle                0x080401
#define ANIM_WorldLakilester_Spiny_Poisoned_StrainIdle          0x080402
#define ANIM_WorldLakilester_Spiny_Poisoned_IdleTough           0x080403
#define ANIM_WorldLakilester_Spiny_Poisoned_Tired               0x080404
#define ANIM_WorldLakilester_Spiny_Poisoned_Walk                0x080405
#define ANIM_WorldLakilester_Spiny_Poisoned_StrainWalk          0x080406
#define ANIM_WorldLakilester_Spiny_Poisoned_Run                 0x080407
#define ANIM_WorldLakilester_Spiny_Poisoned_StrainRun           0x080408
#define ANIM_WorldLakilester_Spiny_Poisoned_Talk                0x080409
#define ANIM_WorldLakilester_Spiny_Poisoned_TiredTalk           0x08040A
#define ANIM_WorldLakilester_Spiny_Poisoned_Shout               0x08040B
#define ANIM_WorldLakilester_Spiny_Poisoned_Vanish              0x08040C
#define ANIM_WorldLakilester_Spiny_Poisoned_Celebrate           0x08040D

#define ANIM_WorldLakilester_Golden_Poisoned_Still              0x080500
#define ANIM_WorldLakilester_Golden_Poisoned_Idle               0x080501
#define ANIM_WorldLakilester_Golden_Poisoned_StrainIdle         0x080502
#define ANIM_WorldLakilester_Golden_Poisoned_IdleTough          0x080503
#define ANIM_WorldLakilester_Golden_Poisoned_Tired              0x080504
#define ANIM_WorldLakilester_Golden_Poisoned_Walk               0x080505
#define ANIM_WorldLakilester_Golden_Poisoned_StrainWalk         0x080506
#define ANIM_WorldLakilester_Golden_Poisoned_Run                0x080507
#define ANIM_WorldLakilester_Golden_Poisoned_StrainRun          0x080508
#define ANIM_WorldLakilester_Golden_Poisoned_Talk               0x080509
#define ANIM_WorldLakilester_Golden_Poisoned_TiredTalk          0x08050A
#define ANIM_WorldLakilester_Golden_Poisoned_Shout              0x08050B
#define ANIM_WorldLakilester_Golden_Poisoned_Vanish             0x08050C
#define ANIM_WorldLakilester_Golden_Poisoned_Celebrate          0x08050D

#define ANIM_WorldLakilester_Inactive_Still                     0x080600
#define ANIM_WorldLakilester_Inactive_Idle                      0x080601
#define ANIM_WorldLakilester_Inactive_StrainIdle                0x080602
#define ANIM_WorldLakilester_Inactive_IdleTough                 0x080603
#define ANIM_WorldLakilester_Inactive_Tired                     0x080604
#define ANIM_WorldLakilester_Inactive_Walk                      0x080605
#define ANIM_WorldLakilester_Inactive_StrainWalk                0x080606
#define ANIM_WorldLakilester_Inactive_Run                       0x080607
#define ANIM_WorldLakilester_Inactive_StrainRun                 0x080608
#define ANIM_WorldLakilester_Inactive_Talk                      0x080609
#define ANIM_WorldLakilester_Inactive_TiredTalk                 0x08060A
#define ANIM_WorldLakilester_Inactive_Shout                     0x08060B
#define ANIM_WorldLakilester_Inactive_Vanish                    0x08060C
#define ANIM_WorldLakilester_Inactive_Celebrate                 0x08060D

#define ANIM_WorldLakilester_Dizzy_Still                        0x080700
#define ANIM_WorldLakilester_Dizzy_Idle                         0x080701
#define ANIM_WorldLakilester_Dizzy_StrainIdle                   0x080702
#define ANIM_WorldLakilester_Dizzy_IdleTough                    0x080703
#define ANIM_WorldLakilester_Dizzy_Tired                        0x080704
#define ANIM_WorldLakilester_Dizzy_Walk                         0x080705
#define ANIM_WorldLakilester_Dizzy_StrainWalk                   0x080706
#define ANIM_WorldLakilester_Dizzy_Run                          0x080707
#define ANIM_WorldLakilester_Dizzy_StrainRun                    0x080708
#define ANIM_WorldLakilester_Dizzy_Talk                         0x080709
#define ANIM_WorldLakilester_Dizzy_TiredTalk                    0x08070A
#define ANIM_WorldLakilester_Dizzy_Shout                        0x08070B
#define ANIM_WorldLakilester_Dizzy_Vanish                       0x08070C
#define ANIM_WorldLakilester_Dizzy_Celebrate                    0x08070D

#define ANIM_WorldLakilester_Spiny_Dizzy_Still                  0x080800
#define ANIM_WorldLakilester_Spiny_Dizzy_Idle                   0x080801
#define ANIM_WorldLakilester_Spiny_Dizzy_StrainIdle             0x080802
#define ANIM_WorldLakilester_Spiny_Dizzy_IdleTough              0x080803
#define ANIM_WorldLakilester_Spiny_Dizzy_Tired                  0x080804
#define ANIM_WorldLakilester_Spiny_Dizzy_Walk                   0x080805
#define ANIM_WorldLakilester_Spiny_Dizzy_StrainWalk             0x080806
#define ANIM_WorldLakilester_Spiny_Dizzy_Run                    0x080807
#define ANIM_WorldLakilester_Spiny_Dizzy_StrainRun              0x080808
#define ANIM_WorldLakilester_Spiny_Dizzy_Talk                   0x080809
#define ANIM_WorldLakilester_Spiny_Dizzy_TiredTalk              0x08080A
#define ANIM_WorldLakilester_Spiny_Dizzy_Shout                  0x08080B
#define ANIM_WorldLakilester_Spiny_Dizzy_Vanish                 0x08080C
#define ANIM_WorldLakilester_Spiny_Dizzy_Celebrate              0x08080D

#define ANIM_WorldLakilester_Shocked_Still                      0x080900
#define ANIM_WorldLakilester_Shocked_Idle                       0x080901
#define ANIM_WorldLakilester_Shocked_StrainIdle                 0x080902
#define ANIM_WorldLakilester_Shocked_IdleTough                  0x080903
#define ANIM_WorldLakilester_Shocked_Tired                      0x080904
#define ANIM_WorldLakilester_Shocked_Walk                       0x080905
#define ANIM_WorldLakilester_Shocked_StrainWalk                 0x080906
#define ANIM_WorldLakilester_Shocked_Run                        0x080907
#define ANIM_WorldLakilester_Shocked_StrainRun                  0x080908
#define ANIM_WorldLakilester_Shocked_Talk                       0x080909
#define ANIM_WorldLakilester_Shocked_TiredTalk                  0x08090A
#define ANIM_WorldLakilester_Shocked_Shout                      0x08090B
#define ANIM_WorldLakilester_Shocked_Vanish                     0x08090C
#define ANIM_WorldLakilester_Shocked_Celebrate                  0x08090D

#define ANIM_WorldLakilester_Spiny_Shocked_Still                0x080A00
#define ANIM_WorldLakilester_Spiny_Shocked_Idle                 0x080A01
#define ANIM_WorldLakilester_Spiny_Shocked_StrainIdle           0x080A02
#define ANIM_WorldLakilester_Spiny_Shocked_IdleTough            0x080A03
#define ANIM_WorldLakilester_Spiny_Shocked_Tired                0x080A04
#define ANIM_WorldLakilester_Spiny_Shocked_Walk                 0x080A05
#define ANIM_WorldLakilester_Spiny_Shocked_StrainWalk           0x080A06
#define ANIM_WorldLakilester_Spiny_Shocked_Run                  0x080A07
#define ANIM_WorldLakilester_Spiny_Shocked_StrainRun            0x080A08
#define ANIM_WorldLakilester_Spiny_Shocked_Talk                 0x080A09
#define ANIM_WorldLakilester_Spiny_Shocked_TiredTalk            0x080A0A
#define ANIM_WorldLakilester_Spiny_Shocked_Shout                0x080A0B
#define ANIM_WorldLakilester_Spiny_Shocked_Vanish               0x080A0C
#define ANIM_WorldLakilester_Spiny_Shocked_Celebrate            0x080A0D

#define ANIM_WorldLakilester_Golden_Shocked_Still               0x080B00
#define ANIM_WorldLakilester_Golden_Shocked_Idle                0x080B01
#define ANIM_WorldLakilester_Golden_Shocked_StrainIdle          0x080B02
#define ANIM_WorldLakilester_Golden_Shocked_IdleTough           0x080B03
#define ANIM_WorldLakilester_Golden_Shocked_Tired               0x080B04
#define ANIM_WorldLakilester_Golden_Shocked_Walk                0x080B05
#define ANIM_WorldLakilester_Golden_Shocked_StrainWalk          0x080B06
#define ANIM_WorldLakilester_Golden_Shocked_Run                 0x080B07
#define ANIM_WorldLakilester_Golden_Shocked_StrainRun           0x080B08
#define ANIM_WorldLakilester_Golden_Shocked_Talk                0x080B09
#define ANIM_WorldLakilester_Golden_Shocked_TiredTalk           0x080B0A
#define ANIM_WorldLakilester_Golden_Shocked_Shout               0x080B0B
#define ANIM_WorldLakilester_Golden_Shocked_Vanish              0x080B0C
#define ANIM_WorldLakilester_Golden_Shocked_Celebrate           0x080B0D

#define ANIM_WorldLakilester_Burnt_Still                        0x080C00
#define ANIM_WorldLakilester_Burnt_Idle                         0x080C01
#define ANIM_WorldLakilester_Burnt_StrainIdle                   0x080C02
#define ANIM_WorldLakilester_Burnt_IdleTough                    0x080C03
#define ANIM_WorldLakilester_Burnt_Tired                        0x080C04
#define ANIM_WorldLakilester_Burnt_Walk                         0x080C05
#define ANIM_WorldLakilester_Burnt_StrainWalk                   0x080C06
#define ANIM_WorldLakilester_Burnt_Run                          0x080C07
#define ANIM_WorldLakilester_Burnt_StrainRun                    0x080C08
#define ANIM_WorldLakilester_Burnt_Talk                         0x080C09
#define ANIM_WorldLakilester_Burnt_TiredTalk                    0x080C0A
#define ANIM_WorldLakilester_Burnt_Shout                        0x080C0B
#define ANIM_WorldLakilester_Burnt_Vanish                       0x080C0C
#define ANIM_WorldLakilester_Burnt_Celebrate                    0x080C0D

#endif
