// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_WORLDKLEVAR_H_
#define _NPC_SPRITE_WORLDKLEVAR_H_

#include "types.h"

#define SPR_WorldKlevar 0x17

#define SPR_PAL_WorldKlevar 0x0
#define SPR_PAL_WorldKlevar_Glowing 0x1

#define ANIM_WorldKlevar_Still                                  0x170000
#define ANIM_WorldKlevar_Idle                                   0x170001
#define ANIM_WorldKlevar_IdleHappy                              0x170002
#define ANIM_WorldKlevar_Talk                                   0x170003
#define ANIM_WorldKlevar_Leap                                   0x170004
#define ANIM_WorldKlevar_TalkHappy                              0x170005
#define ANIM_WorldKlevar_Panic                                  0x170006
#define ANIM_WorldKlevar_Back                                   0x170007
#define ANIM_WorldKlevar_Hurt                                   0x170008

#define ANIM_WorldKlevar_Glowing_Still                          0x170100
#define ANIM_WorldKlevar_Glowing_Idle                           0x170101
#define ANIM_WorldKlevar_Glowing_IdleHappy                      0x170102
#define ANIM_WorldKlevar_Glowing_Talk                           0x170103
#define ANIM_WorldKlevar_Glowing_Leap                           0x170104
#define ANIM_WorldKlevar_Glowing_TalkHappy                      0x170105
#define ANIM_WorldKlevar_Glowing_Panic                          0x170106
#define ANIM_WorldKlevar_Glowing_Back                           0x170107
#define ANIM_WorldKlevar_Glowing_Hurt                           0x170108

#endif
