// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_WORLDMISSTAR_H_
#define _NPC_SPRITE_WORLDMISSTAR_H_

#include "types.h"

#define SPR_WorldMisstar 0x16

#define SPR_PAL_WorldMisstar 0x0
#define SPR_PAL_WorldMisstar_Glowing 0x1

#define ANIM_WorldMisstar_Still                                 0x160000
#define ANIM_WorldMisstar_Idle                                  0x160001
#define ANIM_WorldMisstar_Talk                                  0x160002
#define ANIM_WorldMisstar_Leap                                  0x160003
#define ANIM_WorldMisstar_Happy                                 0x160004
#define ANIM_WorldMisstar_Panic                                 0x160005
#define ANIM_WorldMisstar_Hurt                                  0x160006
#define ANIM_WorldMisstar_Back                                  0x160007
#define ANIM_WorldMisstar_IdleAngry                             0x160008
#define ANIM_WorldMisstar_TalkAngry                             0x160009
#define ANIM_WorldMisstar_Fly                                   0x16000A

#define ANIM_WorldMisstar_Glowing_Still                         0x160100
#define ANIM_WorldMisstar_Glowing_Idle                          0x160101
#define ANIM_WorldMisstar_Glowing_Talk                          0x160102
#define ANIM_WorldMisstar_Glowing_Leap                          0x160103
#define ANIM_WorldMisstar_Glowing_Happy                         0x160104
#define ANIM_WorldMisstar_Glowing_Panic                         0x160105
#define ANIM_WorldMisstar_Glowing_Hurt                          0x160106
#define ANIM_WorldMisstar_Glowing_Back                          0x160107
#define ANIM_WorldMisstar_Glowing_IdleAngry                     0x160108
#define ANIM_WorldMisstar_Glowing_TalkAngry                     0x160109
#define ANIM_WorldMisstar_Glowing_Fly                           0x16010A

#endif
