// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_WORLDBOBOMB_H_
#define _NPC_SPRITE_WORLDBOBOMB_H_

#include "types.h"

#define SPR_WorldBobomb 0x91

#define SPR_PAL_WorldBobomb_Green 0x0
#define SPR_PAL_WorldBobomb_Red 0x1
#define SPR_PAL_WorldBobomb_Blue 0x2

#define ANIM_WorldBobomb_Green_Still                            0x910000
#define ANIM_WorldBobomb_Green_Idle                             0x910001
#define ANIM_WorldBobomb_Green_Walk                             0x910002
#define ANIM_WorldBobomb_Green_Run                              0x910003
#define ANIM_WorldBobomb_Green_Talk                             0x910004

#define ANIM_WorldBobomb_Red_Still                              0x910100
#define ANIM_WorldBobomb_Red_Idle                               0x910101
#define ANIM_WorldBobomb_Red_Walk                               0x910102
#define ANIM_WorldBobomb_Red_Run                                0x910103
#define ANIM_WorldBobomb_Red_Talk                               0x910104

#define ANIM_WorldBobomb_Blue_Still                             0x910200
#define ANIM_WorldBobomb_Blue_Idle                              0x910201
#define ANIM_WorldBobomb_Blue_Walk                              0x910202
#define ANIM_WorldBobomb_Blue_Run                               0x910203
#define ANIM_WorldBobomb_Blue_Talk                              0x910204

#endif
