// Auto-generated by tools/gen_all_anims.py
#ifndef _NPC_SPRITE_WORLDMUSKULAR_H_
#define _NPC_SPRITE_WORLDMUSKULAR_H_

#include "types.h"

#define SPR_WorldMuskular 0x15

#define SPR_PAL_WorldMuskular 0x0
#define SPR_PAL_WorldMuskular_Glowing 0x1

#define ANIM_WorldMuskular_Still                                0x150000
#define ANIM_WorldMuskular_Idle                                 0x150001
#define ANIM_WorldMuskular_Talk                                 0x150002
#define ANIM_WorldMuskular_Leap                                 0x150003
#define ANIM_WorldMuskular_Happy                                0x150004
#define ANIM_WorldMuskular_Back                                 0x150005
#define ANIM_WorldMuskular_Hurt                                 0x150006
#define ANIM_WorldMuskular_Panic                                0x150007

#define ANIM_WorldMuskular_Glowing_Still                        0x150100
#define ANIM_WorldMuskular_Glowing_Idle                         0x150101
#define ANIM_WorldMuskular_Glowing_Talk                         0x150102
#define ANIM_WorldMuskular_Glowing_Leap                         0x150103
#define ANIM_WorldMuskular_Glowing_Happy                        0x150104
#define ANIM_WorldMuskular_Glowing_Back                         0x150105
#define ANIM_WorldMuskular_Glowing_Hurt                         0x150106
#define ANIM_WorldMuskular_Glowing_Panic                        0x150107

#endif
