#ifndef WORLD_MAP_H
#define WORLD_MAP_H
/* This file is auto-generated. Do not edit. */

#include "common.h"

Vec2b PauseMapPaths[][32] = {
    { { 1, -10 }, { 1, -8 }, { -9, -2 }, { -8, 0 }, { -8, 0 }, { -7, -3 }, { -5, -3 }, },
    { { -1, 24 }, { 1, -8 }, { 2, -7 }, },
    { { -3, 7 }, { -7, 4 }, { -8, 2 }, },
    { },
    { },
    { { -8, -3 }, { -7, 0 }, { -8, 1 }, { -7, 2 }, },
    { { -9, 0 }, { -6, -1 }, { -7, 0 }, { -8, 1 }, { -1, 8 }, },
    { { 1, 6 }, { -3, 6 }, },
    { { -7, 1 }, { -7, 3 }, { -7, 3 }, { -7, 3 }, { -7, 1 }, { -7, 2 }, { -7, 0 }, },
    { { -9, 3 }, { -8, 0 }, { -8, 0 }, { -9, -2 }, { -7, -4 }, { -7, -4 }, { -6, -5 }, { -5, -6 }, { -1, -7 }, { -3, -6 }, { -3, -6 }, { -7, -4 }, { -7, 0 }, { -8, 0 }, { -8, 0 }, { -8, 0 }, { -8, 0 }, { 0, -6 }, { 0, -6 }, },
    { { -6, 5 }, { -6, 3 }, { -8, 0 }, { -8, -4 }, { -5, -5 }, { -8, -3 }, { -8, 1 }, { -5, 5 }, { -2, 7 }, { 2, 7 }, { 5, 5 }, { 6, 5 }, { 6, 3 }, },
    { { -2, 6 }, { -4, 4 }, },
    { { 4, 6 }, { 4, 5 }, },
    { { -8, -1 }, { -10, -2 }, { -8, -2 }, { -9, -1 }, { -8, -1 }, { -10, 0 }, { -9, 0 }, },
    { { 8, 6 }, },
    { { -7, 4 }, { -7, 5 }, { -7, 4 }, { -7, 5 }, },
    { { -8, 2 }, { -8, 3 }, { -8, 3 }, { -8, 3 }, },
    { { 10, -1 }, },
    { { 6, 6 }, { 6, 6 }, { 8, 2 }, { 7, -1 }, },
    { { 11, 2 }, { 11, 0 }, { 11, -2 }, { 10, -3 }, { 7, -7 }, { 3, -8 }, { 0, -9 }, { -4, -7 }, { -9, -3 }, { -10, -2 }, { -9, -2 }, { -7, -6 }, { -2, -9 }, { 1, -9 }, { 0, -9 }, { -8, -5 }, { -9, -2 }, { 1, -8 }, { 9, -2 }, { 9, -2 }, { 8, -5 }, },
    { { -9, 3 }, { -5, 5 }, },
    { { -5, 6 }, { -2, 9 }, { 2, 8 }, { 7, 6 }, { 7, 4 }, },
    { },
    { { -3, 6 }, { 0, 7 }, { 5, 6 }, { 1, 7 }, },
    { },
    { { -9, -2 }, },
    { { -11, 1 }, { -9, -2 }, },
    { { -7, 3 }, { -6, 5 }, },
    { { 0, 7 }, },
    { { -9, 3 }, { -8, 1 }, { -7, 1 }, { -7, 4 }, { 2, 6 }, { 8, 3 }, },
    { { -3, 6 }, { 2, 6 }, { 8, 3 }, { 6, 5 }, { -2, 6 }, { -6, 3 }, },
    { { -6, 5 }, { -2, 7 }, { 2, 7 }, { 6, 6 }, { 8, 3 }, { 8, 0 }, { 8, -3 }, { 8, -5 }, { 6, -5 }, { 7, -4 }, { 8, -1 }, { 8, 3 }, { 2, 8 }, },
    { { -3, 7 }, { 0, 6 }, { 4, 7 }, },
    { },
};

PauseMapSpace PauseMapSpaces[] = {
    { .id = LOCATION_TOAD_TOWN, .parent = 0, .afterRequirement = STORY_EPILOGUE, .pos = { .x = 116, .y = 185 }, .pathLength = 7, .path = PauseMapPaths[0] },
    { .id = LOCATION_PEACH_CASTLE_GROUNDS, .parent = 0, .afterRequirement = STORY_EPILOGUE, .pos = { .x = 118, .y = 151 }, .pathLength = 3, .path = PauseMapPaths[1] },
    { .id = LOCATION_SHOOTING_STAR_SUMMIT, .parent = 1, .afterRequirement = STORY_CH0_BEGAN_PEACH_MISSION, .pos = { .x = 143, .y = 134 }, .pathLength = 3, .path = PauseMapPaths[2] },
    { .id = LOCATION_TOAD_TOWN_TUNNELS, .parent = 0, .afterRequirement = STORY_NEVER, .pos = { .x = 100, .y = 174 }, .pathLength = 0, .path = PauseMapPaths[3] },
    { .id = LOCATION_GOOMBA_VILLAGE, .parent = 5, .afterRequirement = STORY_CH0_GOOMBARIO_JOINED_PARTY, .pos = { .x = 36, .y = 157 }, .pathLength = 0, .path = PauseMapPaths[4] },
    { .id = LOCATION_GOOMBA_ROAD, .parent = 0, .afterRequirement = STORY_CH0_ARRIVED_AT_TOAD_TOWN, .pos = { .x = 74, .y = 154 }, .pathLength = 4, .path = PauseMapPaths[5] },
    { .id = LOCATION_PLEASANT_PATH, .parent = 0, .afterRequirement = STORY_CH1_STAR_SPRIT_DEPARTED, .pos = { .x = 148, .y = 167 }, .pathLength = 5, .path = PauseMapPaths[6] },
    { .id = LOCATION_KOOPA_VILLAGE, .parent = 6, .afterRequirement = STORY_CH1_KOOPER_JOINED_PARTY, .pos = { .x = 154, .y = 148 }, .pathLength = 2, .path = PauseMapPaths[7] },
    { .id = LOCATION_KOOPA_BROS_FORTRESS, .parent = 6, .afterRequirement = STORY_CH1_STAR_SPRIT_DEPARTED, .pos = { .x = 205, .y = 152 }, .pathLength = 7, .path = PauseMapPaths[8] },
    { .id = LOCATION_MT_RUGGED, .parent = 0, .afterRequirement = STORY_NEVER, .pos = { .x = 227, .y = 243 }, .pathLength = 19, .path = PauseMapPaths[9] },
    { .id = LOCATION_DRY_DRY_DESERT, .parent = 9, .afterRequirement = STORY_CH2_UNCOVERED_DRY_DRY_RUINS, .pos = { .x = 266, .y = 206 }, .pathLength = 13, .path = PauseMapPaths[10] },
    { .id = LOCATION_DRY_DRY_OUTPOST, .parent = 10, .afterRequirement = STORY_NEVER, .pos = { .x = 280, .y = 191 }, .pathLength = 2, .path = PauseMapPaths[11] },
    { .id = LOCATION_DRY_DRY_RUINS, .parent = 10, .afterRequirement = STORY_CH2_BEGAN_PEACH_MISSION, .pos = { .x = 252, .y = 188 }, .pathLength = 2, .path = PauseMapPaths[12] },
    { .id = LOCATION_FOREVER_FOREST, .parent = 0, .afterRequirement = STORY_CH3_ARRIVED_AT_BOOS_MANSION, .pos = { .x = 187, .y = 193 }, .pathLength = 7, .path = PauseMapPaths[13] },
    { .id = LOCATION_BOOS_MANSION, .parent = 13, .afterRequirement = STORY_CH3_UNLOCKED_GUSTY_GULCH, .pos = { .x = 170, .y = 180 }, .pathLength = 1, .path = PauseMapPaths[14] },
    { .id = LOCATION_GUSTY_GULCH, .parent = 13, .afterRequirement = STORY_CH3_BEGAN_PEACH_MISSION, .pos = { .x = 223, .y = 170 }, .pathLength = 4, .path = PauseMapPaths[15] },
    { .id = LOCATION_TUBBAS_MANOR, .parent = 15, .afterRequirement = STORY_CH3_BEGAN_PEACH_MISSION, .pos = { .x = 263, .y = 156 }, .pathLength = 4, .path = PauseMapPaths[16] },
    { .id = LOCATION_WINDY_MILL, .parent = 15, .afterRequirement = STORY_CH3_BEGAN_PEACH_MISSION, .pos = { .x = 203, .y = 171 }, .pathLength = 1, .path = PauseMapPaths[17] },
    { .id = LOCATION_SHY_GUYS_TOYBOX, .parent = 0, .afterRequirement = STORY_CH4_STAR_SPRIT_DEPARTED, .pos = { .x = 79, .y = 173 }, .pathLength = 4, .path = PauseMapPaths[18] },
    { .id = LOCATION_JADE_JUNGLE, .parent = 0, .afterRequirement = STORY_CH5_ZIP_LINE_READY, .pos = { .x = 66, .y = 289 }, .pathLength = 21, .path = PauseMapPaths[19] },
    { .id = LOCATION_YOSHIS_VILLAGE, .parent = 19, .afterRequirement = STORY_NEVER, .pos = { .x = 84, .y = 274 }, .pathLength = 2, .path = PauseMapPaths[20] },
    { .id = LOCATION_MT_LAVALAVA, .parent = 19, .afterRequirement = STORY_CH5_BEGAN_PEACH_MISSION, .pos = { .x = 47, .y = 252 }, .pathLength = 5, .path = PauseMapPaths[21] },
    { .id = LOCATION_FLOWER_FIELDS, .parent = 0, .afterRequirement = STORY_CH6_BEGAN_PEACH_MISSION, .pos = { .x = 59, .y = 126 }, .pathLength = 0, .path = PauseMapPaths[22] },
    { .id = LOCATION_CLOUDY_CLIMB, .parent = 22, .afterRequirement = STORY_CH6_BEGAN_PEACH_MISSION, .pos = { .x = 58, .y = 92 }, .pathLength = 4, .path = PauseMapPaths[23] },
    { .id = LOCATION_SHIVER_CITY, .parent = 3, .afterRequirement = STORY_CH7_MAYOR_MURDER_SOLVED, .pos = { .x = 183, .y = 125 }, .pathLength = 0, .path = PauseMapPaths[24] },
    { .id = LOCATION_SHIVER_SNOWFIELD, .parent = 24, .afterRequirement = STORY_CH7_DEFEATED_MONSTAR, .pos = { .x = 203, .y = 126 }, .pathLength = 1, .path = PauseMapPaths[25] },
    { .id = LOCATION_STARBORN_VALLEY, .parent = 25, .afterRequirement = STORY_CH7_GOT_SNOWMAN_SCARF, .pos = { .x = 234, .y = 128 }, .pathLength = 2, .path = PauseMapPaths[26] },
    { .id = LOCATION_SHIVER_MOUNTAIN, .parent = 25, .afterRequirement = STORY_CH7_STAR_SPRIT_DEPARTED, .pos = { .x = 220, .y = 112 }, .pathLength = 2, .path = PauseMapPaths[27] },
    { .id = LOCATION_CRYSTAL_PALACE, .parent = 27, .afterRequirement = STORY_CH7_STAR_SPRIT_DEPARTED, .pos = { .x = 223, .y = 99 }, .pathLength = 1, .path = PauseMapPaths[28] },
    { .id = LOCATION_STAR_WAY, .parent = 2, .afterRequirement = STORY_NEVER, .pos = { .x = 158, .y = 110 }, .pathLength = 6, .path = PauseMapPaths[29] },
    { .id = LOCATION_STAR_HAVEN, .parent = 29, .afterRequirement = STORY_NEVER, .pos = { .x = 163, .y = 78 }, .pathLength = 6, .path = PauseMapPaths[30] },
    { .id = LOCATION_BOWSERS_CASTLE, .parent = 30, .afterRequirement = STORY_EPILOGUE, .pos = { .x = 96, .y = 49 }, .pathLength = 13, .path = PauseMapPaths[31] },
    { .id = LOCATION_PEACHS_CASTLE, .parent = 31, .afterRequirement = STORY_EPILOGUE, .pos = { .x = 88, .y = 22 }, .pathLength = 3, .path = PauseMapPaths[32] },
    { .id = LOCATION_MARIOS_HOUSE, .parent = 0, .afterRequirement = STORY_NEVER, .pos = { .x = 98, .y = 147 }, .pathLength = 0, .path = PauseMapPaths[33] },
};

#endif // WORLD_MAP_H
