#!/usr/bin/env python3
"""Generate correct sprite animation constants for ALL sprites (player + NPC).

Animation ID format: (sprite_id << 16) | (palette_id << 8) | anim_index
Player sprite IDs start at 1 (with back variants getting their own IDs).
NPC sprite IDs start at 1 (sequential, one per NPC sprite).
"""

import yaml
import sys
import os

DECOMP_DIR = sys.argv[1] if len(sys.argv) > 1 else "../papermario-main"
OUT_DIR = sys.argv[2] if len(sys.argv) > 2 else "include/sprite"

PLAYER_YAML = os.path.join(DECOMP_DIR, "tools/splat_ext/player_sprite_names.yaml")
NPC_YAML = os.path.join(DECOMP_DIR, "tools/splat_ext/npc_sprite_names.yaml")

def gen_pal_name(palette):
    """Extract palette name from YAML entry (can be str or dict)."""
    if isinstance(palette, dict):
        return palette["name"]
    return palette

# ==================== PLAYER SPRITES ====================

with open(PLAYER_YAML) as f:
    player_data = yaml.safe_load(f)

sprites = player_data["player_sprites"]

sprite_id = 1
player_spr_defines = []
player_anim_defines = []

for sprite_name, sprite_info in sprites.items():
    has_back = sprite_info.get("has_back", False)
    palettes = sprite_info.get("palettes", [])
    animations = sprite_info.get("animations", [])

    player_spr_defines.append((f"SPR_{sprite_name}", sprite_id))

    for pal_idx, palette in enumerate(palettes):
        pal_name = gen_pal_name(palette)
        for anim_idx, anim_name in enumerate(animations):
            if pal_idx == 0:
                full_name = f"ANIM_{sprite_name}_{anim_name}"
            else:
                full_name = f"ANIM_{sprite_name}_{pal_name}_{anim_name}"
            anim_value = (sprite_id << 16) | (pal_idx << 8) | anim_idx
            player_anim_defines.append((full_name, anim_value))

    sprite_id += 1
    if has_back:
        player_spr_defines.append((f"SPR_{sprite_name}_Back", sprite_id))
        sprite_id += 1

# Write player header
os.makedirs(OUT_DIR, exist_ok=True)
player_out = os.path.join(OUT_DIR, "player.h")
with open(player_out, "w") as f:
    f.write("// Auto-generated by tools/gen_all_anims.py\n")
    f.write("// DO NOT EDIT - regenerate from player_sprite_names.yaml\n")
    f.write("#ifndef _SPRITE_PLAYER_H_\n")
    f.write("#define _SPRITE_PLAYER_H_\n\n")
    f.write('#include "types.h"\n\n')

    f.write("// Player sprite indices (1-based)\n")
    for name, sid in player_spr_defines:
        f.write(f"#define {name:<24s} 0x{sid:02X}\n")
    f.write(f"\n#define SPR_PLAYER_COLOR_VARIATIONS 7\n")
    f.write(f"#define SPR_PEACH_BTL_PAL_STRIDE 7\n\n")

    f.write("// Player animation IDs: (sprite_id << 16) | (palette_id << 8) | anim_index\n\n")
    current_sprite = None
    for name, value in player_anim_defines:
        sprite = name.split("_")[1]
        if sprite != current_sprite:
            if current_sprite: f.write("\n")
            f.write(f"// {sprite}\n")
            current_sprite = sprite
        f.write(f"#define {name:<55s} 0x{value:06X}\n")

    f.write("\n#endif /* _SPRITE_PLAYER_H_ */\n")

print(f"Player: {len(player_spr_defines)} sprites, {len(player_anim_defines)} animations -> {player_out}")

# ==================== NPC SPRITES ====================

with open(NPC_YAML) as f:
    npc_data = yaml.safe_load(f)

npc_sprite_id = 1
npc_anim_defines = []
npc_spr_defines = []

for sprite_name, sprite_info in npc_data.items():
    if not isinstance(sprite_info, dict):
        continue  # skip comments or non-dict entries

    palettes = sprite_info.get("palettes", ["Default"])
    animations = sprite_info.get("animations", [])

    npc_spr_defines.append((f"SPR_{sprite_name}", npc_sprite_id))

    for pal_idx, palette in enumerate(palettes):
        pal_name = gen_pal_name(palette)
        for anim_idx, anim_name in enumerate(animations):
            if pal_name == "Default":
                full_name = f"ANIM_{sprite_name}_{anim_name}"
            else:
                full_name = f"ANIM_{sprite_name}_{pal_name}_{anim_name}"
            anim_value = (npc_sprite_id << 16) | (pal_idx << 8) | anim_idx
            npc_anim_defines.append((full_name, anim_value))

    npc_sprite_id += 1

# Write NPC header (single combined file for all NPC sprites)
npc_out = os.path.join(OUT_DIR, "npc_all.h")
with open(npc_out, "w") as f:
    f.write("// Auto-generated by tools/gen_all_anims.py\n")
    f.write("// DO NOT EDIT - regenerate from npc_sprite_names.yaml\n")
    f.write("#ifndef _SPRITE_NPC_ALL_H_\n")
    f.write("#define _SPRITE_NPC_ALL_H_\n\n")
    f.write('#include "types.h"\n\n')

    f.write("// NPC sprite indices (1-based)\n")
    for name, sid in npc_spr_defines:
        f.write(f"#define {name:<40s} 0x{sid:02X}\n")

    f.write(f"\n// Total NPC sprites: {npc_sprite_id - 1}\n\n")

    f.write("// NPC animation IDs: (sprite_id << 16) | (palette_id << 8) | anim_index\n\n")
    current_sprite = None
    for name, value in npc_anim_defines:
        # Determine sprite name from ANIM_ define
        parts = name.split("_", 2)  # ANIM, SpriteName, ...
        sprite = parts[1]
        if sprite != current_sprite:
            if current_sprite: f.write("\n")
            f.write(f"// {sprite}\n")
            current_sprite = sprite
        f.write(f"#define {name:<60s} 0x{value:06X}\n")

    f.write("\n#endif /* _SPRITE_NPC_ALL_H_ */\n")

print(f"NPC: {len(npc_spr_defines)} sprites, {len(npc_anim_defines)} animations -> {npc_out}")

# Also write individual NPC headers (for includes like "sprite/npc/WorldGoombario.h")
npc_header_dir = os.path.join(OUT_DIR, "npc")
os.makedirs(npc_header_dir, exist_ok=True)

npc_sprite_id = 1
for sprite_name, sprite_info in npc_data.items():
    if not isinstance(sprite_info, dict):
        continue

    palettes = sprite_info.get("palettes", ["Default"])
    animations = sprite_info.get("animations", [])

    header_path = os.path.join(npc_header_dir, f"{sprite_name}.h")
    guard = f"_NPC_SPRITE_{sprite_name.upper()}_H_"

    with open(header_path, "w") as f:
        f.write(f"// Auto-generated by tools/gen_all_anims.py\n")
        f.write(f"#ifndef {guard}\n")
        f.write(f"#define {guard}\n\n")
        f.write(f'#include "types.h"\n\n')
        f.write(f"#define SPR_{sprite_name} 0x{npc_sprite_id:02X}\n\n")

        for pal_idx, palette in enumerate(palettes):
            pal_name = gen_pal_name(palette)
            if pal_name == "Default":
                f.write(f"#define SPR_PAL_{sprite_name} 0x{pal_idx:X}\n")
            else:
                f.write(f"#define SPR_PAL_{sprite_name}_{pal_name} 0x{pal_idx:X}\n")
        f.write("\n")

        for pal_idx, palette in enumerate(palettes):
            pal_name = gen_pal_name(palette)
            for anim_idx, anim_name in enumerate(animations):
                if pal_name == "Default":
                    full_name = f"ANIM_{sprite_name}_{anim_name}"
                else:
                    full_name = f"ANIM_{sprite_name}_{pal_name}_{anim_name}"
                anim_value = (npc_sprite_id << 16) | (pal_idx << 8) | anim_idx
                f.write(f"#define {full_name:<55s} 0x{anim_value:06X}\n")
            f.write("\n")

        f.write(f"#endif\n")

    npc_sprite_id += 1

print(f"Individual NPC headers: {npc_sprite_id - 1} files -> {npc_header_dir}/")
