#!/usr/bin/env python3
"""Generate correct player sprite animation constants from the decomp's YAML.

Animation ID format: (sprite_id << 16) | (palette_id << 8) | anim_index
Sprite IDs start at 1. Sprites with has_back=True get two IDs (front, back).
"""

import yaml
import sys
import os

YAML_PATH = sys.argv[1] if len(sys.argv) > 1 else "../papermario-main/tools/splat_ext/player_sprite_names.yaml"
OUT_PATH = sys.argv[2] if len(sys.argv) > 2 else "include/sprite/player.h"

with open(YAML_PATH) as f:
    data = yaml.safe_load(f)

sprites = data["player_sprites"]

sprite_id = 1
spr_defines = []  # (name, id)
anim_defines = []  # (name, value)

for sprite_name, sprite_info in sprites.items():
    has_back = sprite_info.get("has_back", False)
    palettes = sprite_info.get("palettes", [])
    animations = sprite_info.get("animations", [])

    spr_defines.append((f"SPR_{sprite_name}", sprite_id))

    # Generate animation IDs for each palette x animation combo
    for pal_idx, palette in enumerate(palettes):
        if isinstance(palette, dict):
            pal_name = palette["name"]
        else:
            pal_name = palette

        for anim_idx, anim_name in enumerate(animations):
            if pal_idx == 0:
                full_name = f"ANIM_{sprite_name}_{anim_name}"
            else:
                full_name = f"ANIM_{sprite_name}_{pal_name}_{anim_name}"

            anim_value = (sprite_id << 16) | (pal_idx << 8) | anim_idx
            anim_defines.append((full_name, anim_value))

    sprite_id += 1

    if has_back:
        spr_defines.append((f"SPR_{sprite_name}_Back", sprite_id))
        sprite_id += 1

os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
with open(OUT_PATH, "w") as f:
    f.write("// Auto-generated by tools/gen_player_anims.py\n")
    f.write("// DO NOT EDIT - regenerate from player_sprite_names.yaml\n")
    f.write("#ifndef _SPRITE_PLAYER_H_\n")
    f.write("#define _SPRITE_PLAYER_H_\n\n")
    f.write('#include "types.h"\n\n')

    # SPR defines
    f.write("// Player sprite indices (1-based, used by SPR_UNPACK_SPR)\n")
    for name, sid in spr_defines:
        f.write(f"#define {name:<24s} 0x{sid:02X}\n")
    f.write(f"\n// Total player sprites: {sprite_id - 1}\n\n")

    # Derived constants
    f.write("#define SPR_PLAYER_COLOR_VARIATIONS 7\n")
    f.write("#define SPR_PEACH_BTL_PAL_STRIDE 7\n\n")

    # Animation defines grouped by sprite
    f.write("// Player animation IDs\n")
    f.write("// Format: (sprite_id << 16) | (palette_id << 8) | anim_index\n\n")

    current_sprite = None
    for name, value in anim_defines:
        # Group by sprite name (everything before the 2nd underscore part)
        parts = name.split("_")
        # ANIM_Mario1_Idle -> sprite = Mario1
        sprite = parts[1]
        if sprite != current_sprite:
            if current_sprite is not None:
                f.write("\n")
            f.write(f"// {sprite}\n")
            current_sprite = sprite

        f.write(f"#define {name:<55s} 0x{value:06X}\n")

    f.write("\n#endif /* _SPRITE_PLAYER_H_ */\n")

print(f"Generated {OUT_PATH} with {len(spr_defines)} sprite defines and {len(anim_defines)} animation defines")
